server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:8090"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: content-service
          uri: lb://content-service
          predicates:
            - Path=/api/content/**
          filters:
            - StripPrefix=2
            - JwtAuthFilter

        - id: exercises-service
          uri: lb://content-service
          predicates:
            - Path=/api/exercises/**
          filters:
            - StripPrefix=1
            - JwtAuthFilter

        - id: progress-service
          uri: lb://progress-service
          predicates:
            - Path=/api/progress/**
          filters:
            - StripPrefix=1
            - JwtAuthFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: ${JWT_SECRET}
