package com.dojo.monolith.frontend.controller.guia;

import java.util.*;
import static com.dojo.monolith.frontend.controller.guia.GuiaHelper.*;

public class GuiaCapitulo13 {

    public static Map<String, Object> getPaso() {
        return crearPaso(
            13, "Ejercicios de Código", "bi-code-slash",
            "Los ejercicios de código van un paso más allá de las flashcards y quizzes: "
            + "el usuario escribe Java directamente en un editor dentro de la app. "
            + "No se ejecuta el código (no hay sandbox Java en el backend), pero se valida "
            + "que contenga las keywords necesarias. Es una forma simple pero efectiva de practicar.",
            List.of(

                section("1. ¿Cómo funciona la validación?",
                    "<p>La validación es por <b>keywords</b> (palabras clave), no por ejecución:</p>"
                    + "<pre><code>Ejercicio: \"Crea un controller REST\"\n"
                    + "Keywords requeridas: @RestController, @GetMapping, ResponseEntity\n"
                    + "\n"
                    + "El usuario escribe:\n"
                    + "  @RestController\n"
                    + "  public class MyController {\n"
                    + "      @GetMapping(\"/hello\")\n"
                    + "      public ResponseEntity&lt;String&gt; hello() {\n"
                    + "          return ResponseEntity.ok(\"Hello\");\n"
                    + "      }\n"
                    + "  }\n"
                    + "\n"
                    + "Validación:\n"
                    + "  ✅ @RestController → encontrado\n"
                    + "  ✅ @GetMapping     → encontrado\n"
                    + "  ✅ ResponseEntity  → encontrado\n"
                    + "  → Resultado: PASSED (100%)</code></pre>"
                    + "<p><b>¿Por qué no ejecutar el código?</b></p>"
                    + "<ul>"
                    + "<li>Ejecutar Java requiere un sandbox seguro (compilador, JVM aislada) — complejidad enorme</li>"
                    + "<li>La validación por keywords verifica que el usuario sabe <b>qué anotaciones y clases usar</b></li>"
                    + "<li>Para un proyecto de aprendizaje es más que suficiente</li>"
                    + "<li>Plataformas como HackerRank/LeetCode sí ejecutan código, pero tienen infraestructura dedicada</li>"
                    + "</ul>"),

                section("2. Entity: CodeExercise.java",
                    "<p><b>Ruta</b>: <code>content-service/src/main/java/com/dojo/content/entity/CodeExercise.java</code></p>"
                    + "<pre><code>@Entity\n"
                    + "@Table(name = \"code_exercises\")\n"
                    + "public class CodeExercise {\n"
                    + "\n"
                    + "    @Id\n"
                    + "    @GeneratedValue(strategy = GenerationType.IDENTITY)\n"
                    + "    private Long id;\n"
                    + "\n"
                    + "    @Column(nullable = false)\n"
                    + "    private String title;        // \"Crea un Controller REST\"\n"
                    + "\n"
                    + "    @Column(nullable = false, length = 2000)\n"
                    + "    private String description;   // Enunciado detallado\n"
                    + "\n"
                    + "    @Column(nullable = false)\n"
                    + "    private String belt;           // BLANCO, AMARILLO...\n"
                    + "\n"
                    + "    @Column(nullable = false, length = 3000)\n"
                    + "    private String starterCode;    // Código inicial (plantilla)\n"
                    + "\n"
                    + "    @Column(nullable = false, length = 3000)\n"
                    + "    private String solution;       // Solución completa\n"
                    + "\n"
                    + "    @Column(nullable = false, length = 1000)\n"
                    + "    private String requiredKeywords;  // \"@RestController,@GetMapping,ResponseEntity\"\n"
                    + "\n"
                    + "    @Column(length = 1000)\n"
                    + "    private String hints;          // Pistas para el usuario\n"
                    + "\n"
                    + "    @Column(name = \"created_at\", nullable = false, updatable = false)\n"
                    + "    private LocalDateTime createdAt;\n"
                    + "\n"
                    + "    @PrePersist\n"
                    + "    protected void onCreate() {\n"
                    + "        this.createdAt = LocalDateTime.now();\n"
                    + "    }\n"
                    + "\n"
                    + "    // Constructor vacío + constructor completo + getters/setters\n"
                    + "}</code></pre>"
                    + "<p><b>Campos clave:</b></p>"
                    + "<ul>"
                    + "<li><code>starterCode</code> — El código que aparece en el editor al abrir el ejercicio (plantilla con huecos)</li>"
                    + "<li><code>solution</code> — La solución completa (se puede mostrar al pulsar \"Ver solución\")</li>"
                    + "<li><code>requiredKeywords</code> — String separado por comas: <code>\"@RestController,@GetMapping,ResponseEntity\"</code>. "
                    + "El validador busca que el código del usuario contenga TODAS estas palabras</li>"
                    + "<li><code>hints</code> — Pistas que se muestran al pulsar \"Pistas\" (ocultas por defecto)</li>"
                    + "</ul>"),

                section("3. CodeExerciseService — La validación",
                    "<p><b>Ruta</b>: <code>.../service/CodeExerciseService.java</code></p>"
                    + "<pre><code>@Service\n"
                    + "public class CodeExerciseService {\n"
                    + "\n"
                    + "    private final CodeExerciseRepository repository;\n"
                    + "\n"
                    + "    // Constructor...\n"
                    + "\n"
                    + "    public Map&lt;String, Object&gt; validateCode(\n"
                    + "            Long id, String userCode) {\n"
                    + "\n"
                    + "        CodeExercise exercise = findById(id);\n"
                    + "\n"
                    + "        // Dividir keywords por coma\n"
                    + "        String[] keywords = exercise\n"
                    + "            .getRequiredKeywords().split(\",\");\n"
                    + "\n"
                    + "        List&lt;String&gt; missing = new ArrayList&lt;&gt;();\n"
                    + "        List&lt;String&gt; found = new ArrayList&lt;&gt;();\n"
                    + "\n"
                    + "        for (String keyword : keywords) {\n"
                    + "            String kw = keyword.trim();\n"
                    + "            if (userCode.contains(kw)) {\n"
                    + "                found.add(kw);\n"
                    + "            } else {\n"
                    + "                missing.add(kw);\n"
                    + "            }\n"
                    + "        }\n"
                    + "\n"
                    + "        boolean passed = missing.isEmpty();\n"
                    + "        int score = keywords.length > 0\n"
                    + "            ? (found.size() * 100) / keywords.length : 0;\n"
                    + "\n"
                    + "        Map&lt;String, Object&gt; result = new LinkedHashMap&lt;&gt;();\n"
                    + "        result.put(\"passed\", passed);\n"
                    + "        result.put(\"score\", score);\n"
                    + "        result.put(\"foundKeywords\", found);\n"
                    + "        result.put(\"missingKeywords\", missing);\n"
                    + "        result.put(\"message\", passed\n"
                    + "            ? \"¡Correcto! Tu código contiene todos \"\n"
                    + "            + \"los elementos necesarios. 🥋\"\n"
                    + "            : \"Faltan algunos elementos clave. \"\n"
                    + "            + \"Revisa las pistas e inténtalo de nuevo.\");\n"
                    + "\n"
                    + "        return result;\n"
                    + "    }\n"
                    + "}</code></pre>"
                    + "<p>La validación es sencilla: para cada keyword, comprueba si está en el código con <code>String.contains()</code>. "
                    + "Si faltan → devuelve cuáles faltan. Si están todas → 100%.</p>"),

                section("4. CodeExerciseController",
                    "<p><b>Ruta</b>: <code>.../controller/CodeExerciseController.java</code></p>"
                    + "<pre><code>@RestController\n"
                    + "@RequestMapping(\"/exercises\")\n"
                    + "public class CodeExerciseController {\n"
                    + "\n"
                    + "    private final CodeExerciseService service;\n"
                    + "\n"
                    + "    // Constructor...\n"
                    + "\n"
                    + "    @GetMapping\n"
                    + "    public ResponseEntity&lt;List&lt;CodeExercise&gt;&gt; getAll() {\n"
                    + "        return ResponseEntity.ok(service.findAll());\n"
                    + "    }\n"
                    + "\n"
                    + "    @GetMapping(\"/{id}\")\n"
                    + "    public ResponseEntity&lt;CodeExercise&gt; getById(\n"
                    + "            @PathVariable Long id) {\n"
                    + "        return ResponseEntity.ok(service.findById(id));\n"
                    + "    }\n"
                    + "\n"
                    + "    @GetMapping(\"/belt/{belt}\")\n"
                    + "    public ResponseEntity&lt;List&lt;CodeExercise&gt;&gt; getByBelt(\n"
                    + "            @PathVariable String belt) {\n"
                    + "        return ResponseEntity.ok(service.findByBelt(belt));\n"
                    + "    }\n"
                    + "\n"
                    + "    // 🔑 Validar código del usuario\n"
                    + "    @PostMapping(\"/{id}/validate\")\n"
                    + "    public ResponseEntity&lt;Map&lt;String, Object&gt;&gt; validate(\n"
                    + "            @PathVariable Long id,\n"
                    + "            @RequestBody Map&lt;String, String&gt; body) {\n"
                    + "        String userCode = body.getOrDefault(\"code\", \"\");\n"
                    + "        return ResponseEntity.ok(\n"
                    + "            service.validateCode(id, userCode));\n"
                    + "    }\n"
                    + "}</code></pre>"
                    + "<table class='table table-sm table-dark'>"
                    + "<thead><tr><th>Endpoint</th><th>Qué hace</th></tr></thead>"
                    + "<tbody>"
                    + "<tr><td><code>GET /exercises</code></td><td>Listar todos los ejercicios</td></tr>"
                    + "<tr><td><code>GET /exercises/5</code></td><td>Un ejercicio por ID</td></tr>"
                    + "<tr><td><code>GET /exercises/belt/BLANCO</code></td><td>Ejercicios de un cinturón</td></tr>"
                    + "<tr><td><code>POST /exercises/5/validate</code></td><td>Validar código → devuelve passed, score, missing</td></tr>"
                    + "</tbody></table>"
                    + "<p>📌 La ruta del Gateway para ejercicios es <code>/api/exercises/**</code> con StripPrefix=1, "
                    + "así que <code>/api/exercises/5/validate</code> llega a content-service como <code>/exercises/5/validate</code>.</p>"),

                section("5. Frontend — exercises.html (listado)",
                    "<p>La página de listado muestra los ejercicios agrupados por cinturón:</p>"
                    + "<pre><code>&lt;!-- Agrupados por cinturón --&gt;\n"
                    + "&lt;div th:each=\"entry : ${exercisesByBelt}\" class=\"mb-4\"&gt;\n"
                    + "\n"
                    + "  &lt;!-- Badge del cinturón con color --&gt;\n"
                    + "  &lt;h4&gt;\n"
                    + "    &lt;span th:switch=\"${entry.key}\"&gt;\n"
                    + "      &lt;span th:case=\"'BLANCO'\" class=\"badge\"\n"
                    + "          style=\"background:#f0f0f0;color:#333\"&gt;\n"
                    + "          ⬜ Blanco&lt;/span&gt;\n"
                    + "      &lt;!-- ... otros cinturones --&gt;\n"
                    + "    &lt;/span&gt;\n"
                    + "  &lt;/h4&gt;\n"
                    + "\n"
                    + "  &lt;!-- Tarjetas de ejercicios --&gt;\n"
                    + "  &lt;div th:each=\"ex : ${entry.value}\" class=\"col-md-4\"&gt;\n"
                    + "    &lt;div class=\"card bg-secondary text-light\"&gt;\n"
                    + "      &lt;h5 th:text=\"${ex['title']}\"&gt;Título&lt;/h5&gt;\n"
                    + "      &lt;p th:text=\"${#strings.abbreviate(\n"
                    + "          ex['description'], 120)}\"&gt;Desc&lt;/p&gt;\n"
                    + "      &lt;a th:href=\"@{/exercises/{id}(id=${ex['id']})}\"&gt;\n"
                    + "        Resolver\n"
                    + "      &lt;/a&gt;\n"
                    + "    &lt;/div&gt;\n"
                    + "  &lt;/div&gt;\n"
                    + "&lt;/div&gt;</code></pre>"
                    + "<p><code>#strings.abbreviate(text, 120)</code> — Función de Thymeleaf que trunca el texto a 120 caracteres con \"...\".</p>"
                    + "<p><code>th:switch / th:case</code> — Thymeleaf switch-case para asignar colores por cinturón.</p>"),

                section("6. Frontend — exercise-detail.html (editor)",
                    "<p>La página de detalle es la más interactiva del proyecto:</p>"
                    + "<pre><code>&lt;!-- Editor de código --&gt;\n"
                    + "&lt;form th:action=\"@{/exercises/{id}/validate(\n"
                    + "    id=${exercise['id']})}\" method=\"post\"&gt;\n"
                    + "\n"
                    + "  &lt;textarea name=\"code\"\n"
                    + "    class=\"form-control bg-dark text-success\"\n"
                    + "    rows=\"14\"\n"
                    + "    style=\"font-family:'Courier New',monospace;\n"
                    + "           font-size:14px;tab-size:4;\"\n"
                    + "    th:text=\"${userCode != null\n"
                    + "        ? userCode : exercise['starterCode']}\"\n"
                    + "    spellcheck=\"false\"&gt;&lt;/textarea&gt;\n"
                    + "\n"
                    + "  &lt;button type=\"submit\" class=\"btn btn-warning\"&gt;\n"
                    + "    ✅ Validar\n"
                    + "  &lt;/button&gt;\n"
                    + "  &lt;button onclick=\"toggle('hints')\"&gt;\n"
                    + "    💡 Pistas\n"
                    + "  &lt;/button&gt;\n"
                    + "  &lt;button onclick=\"toggle('solution')\"&gt;\n"
                    + "    👁 Ver solución\n"
                    + "  &lt;/button&gt;\n"
                    + "&lt;/form&gt;\n"
                    + "\n"
                    + "&lt;!-- Pistas (ocultas por defecto) --&gt;\n"
                    + "&lt;div id=\"hints\" class=\"d-none alert alert-info\"&gt;\n"
                    + "  &lt;p th:text=\"${exercise['hints']}\"&gt;&lt;/p&gt;\n"
                    + "&lt;/div&gt;\n"
                    + "\n"
                    + "&lt;!-- Solución (oculta por defecto) --&gt;\n"
                    + "&lt;div id=\"solution\" class=\"d-none\"&gt;\n"
                    + "  &lt;pre th:text=\"${exercise['solution']}\"&gt;&lt;/pre&gt;\n"
                    + "&lt;/div&gt;</code></pre>"
                    + "<p>El editor es un simple <code>&lt;textarea&gt;</code> con estilo monospace y fondo oscuro. "
                    + "No es un IDE completo (sin syntax highlighting), pero cumple su función.</p>"
                    + "<p><b>Resultado de la validación</b> (panel lateral):</p>"
                    + "<pre><code>&lt;!-- Panel de resultado (verde si passed, rojo si no) --&gt;\n"
                    + "&lt;div th:if=\"${result}\"\n"
                    + "     th:classappend=\"${result['passed']}\n"
                    + "         ? 'bg-success' : 'bg-danger'\"&gt;\n"
                    + "  &lt;h5 th:text=\"${result['passed']}\n"
                    + "      ? '✅ ¡Correcto!' : '❌ Incorrecto'\"&gt;&lt;/h5&gt;\n"
                    + "  &lt;p th:text=\"${result['message']}\"&gt;&lt;/p&gt;\n"
                    + "  &lt;p&gt;Puntuación: &lt;span th:text=\"${result['score']}\n"
                    + "      + '%'\"&gt;&lt;/span&gt;&lt;/p&gt;\n"
                    + "\n"
                    + "  &lt;!-- Keywords que faltan --&gt;\n"
                    + "  &lt;div th:if=\"${!result['missingKeywords'].isEmpty()}\"&gt;\n"
                    + "    &lt;strong&gt;Te falta:&lt;/strong&gt;\n"
                    + "    &lt;ul&gt;\n"
                    + "      &lt;li th:each=\"kw : ${result['missingKeywords']}\"&gt;\n"
                    + "        &lt;code th:text=\"${kw}\"&gt;&lt;/code&gt;\n"
                    + "      &lt;/li&gt;\n"
                    + "    &lt;/ul&gt;\n"
                    + "  &lt;/div&gt;\n"
                    + "&lt;/div&gt;</code></pre>"
                    + "<p>Si fallas, te dice <b>exactamente qué keywords te faltan</b> — así sabes qué añadir.</p>"),

                section("7. Datos iniciales en el DataSeeder",
                    "<p>Añade ejercicios al <code>DataSeeder</code> de content-service:</p>"
                    + "<pre><code>@Bean\n"
                    + "CommandLineRunner seedExercises(CodeExerciseRepository repo) {\n"
                    + "    return args -> {\n"
                    + "        if (repo.count() == 0) {\n"
                    + "            repo.saveAll(List.of(\n"
                    + "                new CodeExercise(\n"
                    + "                    \"Crea un Controller REST\",\n"
                    + "                    \"Crea un controlador REST que tenga \"\n"
                    + "                    + \"un endpoint GET en /hello que \"\n"
                    + "                    + \"devuelva un ResponseEntity con \"\n"
                    + "                    + \"un saludo.\",\n"
                    + "                    \"BLANCO\",\n"
                    + "                    // Starter code (plantilla)\n"
                    + "                    \"// Añade la anotación del controller\\n\"\n"
                    + "                    + \"public class HelloController {\\n\"\n"
                    + "                    + \"    // Añade el endpoint GET\\n\"\n"
                    + "                    + \"    public ??? hello() {\\n\"\n"
                    + "                    + \"        // Devuelve un saludo\\n\"\n"
                    + "                    + \"    }\\n\"\n"
                    + "                    + \"}\",\n"
                    + "                    // Solución\n"
                    + "                    \"@RestController\\n\"\n"
                    + "                    + \"public class HelloController {\\n\"\n"
                    + "                    + \"    @GetMapping(\\\"/hello\\\")\\n\"\n"
                    + "                    + \"    public ResponseEntity&lt;String&gt; \"\n"
                    + "                    + \"hello() {\\n\"\n"
                    + "                    + \"        return ResponseEntity\"\n"
                    + "                    + \".ok(\\\"Hello World!\\\");\\n\"\n"
                    + "                    + \"    }\\n\"\n"
                    + "                    + \"}\",\n"
                    + "                    // Keywords requeridas\n"
                    + "                    \"@RestController,@GetMapping,\"\n"
                    + "                    + \"ResponseEntity\",\n"
                    + "                    // Pistas\n"
                    + "                    \"Usa @RestController para la clase. \"\n"
                    + "                    + \"@GetMapping para el endpoint. \"\n"
                    + "                    + \"ResponseEntity.ok() para la respuesta.\"\n"
                    + "                )\n"
                    + "                // ... más ejercicios por cinturón\n"
                    + "            ));\n"
                    + "        }\n"
                    + "    };\n"
                    + "}</code></pre>"),

                section("⚠️ Errores comunes",
                    "<table class='table table-sm table-dark'>"
                    + "<thead><tr><th>Error</th><th>Causa</th><th>Solución</th></tr></thead>"
                    + "<tbody>"
                    + "<tr><td>El editor no muestra el starterCode</td>"
                    + "<td>El campo <code>starterCode</code> tiene caracteres especiales no escapados</td>"
                    + "<td>Usa <code>th:text</code> en el textarea (no <code>th:value</code>). Thymeleaf escapa HTML automáticamente</td></tr>"
                    + "<tr><td>Validación siempre falla</td>"
                    + "<td>Las keywords tienen espacios extra (del <code>.split(\",\")</code>)</td>"
                    + "<td>Usa <code>keyword.trim()</code> después del split para eliminar espacios</td></tr>"
                    + "<tr><td>El código del usuario se pierde al validar</td>"
                    + "<td>No se devuelve el <code>userCode</code> al template después del POST</td>"
                    + "<td>En el controller, haz <code>model.addAttribute(\"userCode\", code)</code> para mantener lo que escribió</td></tr>"
                    + "<tr><td>Tab no funciona en el textarea</td>"
                    + "<td>Por defecto Tab cambia el foco del campo</td>"
                    + "<td>Añade JavaScript para capturar Tab e insertar espacios/tabs. O usa <code>tab-size: 4</code> en CSS</td></tr>"
                    + "</tbody></table>"),

                section("💡 Conceptos para la entrevista",
                    "<ul>"
                    + "<li><b>Validación estática vs dinámica</b> — Estática = buscar patrones en texto (lo que hacemos). "
                    + "Dinámica = compilar y ejecutar. Estática es más segura y simple</li>"
                    + "<li><b>String.contains()</b> — Case-sensitive. Si quisieras case-insensitive: "
                    + "<code>userCode.toLowerCase().contains(kw.toLowerCase())</code></li>"
                    + "<li><b>@RequestBody Map</b> — Puedes recibir JSON como <code>Map&lt;String, String&gt;</code> "
                    + "en vez de crear un DTO dedicado. Útil para endpoints simples con pocos campos</li>"
                    + "<li><b>Mejoras posibles</b> — Syntax highlighting (CodeMirror/Monaco editor), "
                    + "ejecución real en sandbox Docker, tests unitarios como validación</li>"
                    + "</ul>"),

                section("✅ Checklist antes de continuar",
                    "<ul>"
                    + "<li>☐ <code>CodeExercise.java</code> en content-service</li>"
                    + "<li>☐ <code>CodeExerciseRepository.java</code></li>"
                    + "<li>☐ <code>CodeExerciseService.java</code> con <code>validateCode()</code></li>"
                    + "<li>☐ <code>CodeExerciseController.java</code> con 4 endpoints</li>"
                    + "<li>☐ DataSeeder carga ejercicios de ejemplo</li>"
                    + "<li>☐ Frontend: <code>exercises.html</code> (listado) + <code>exercise-detail.html</code> (editor)</li>"
                    + "<li>☐ Puedes escribir código y validar → feedback con keywords</li>"
                    + "<li>☐ Commit: <code>git commit -m \"Add code exercises with validation\"</code></li>"
                    + "</ul>"
                    + "<p>¡Ejercicios de código listos! 💻 Ahora algo meta: la <b>Guía Integrada</b> — "
                    + "esta misma guía dentro de la app. 📖</p>")
            ));
    }
}
