package com.dojo.monolith.frontend.controller.guia;

import java.util.*;
import static com.dojo.monolith.frontend.controller.guia.GuiaHelper.*;

public class GuiaCapitulo12 {

    public static Map<String, Object> getPaso() {
        return crearPaso(
            12, "Sistema de Cinturones", "bi-trophy",
            "Los cinturones dan estructura al aprendizaje: empiezas por el Blanco (fundamentos) "
            + "y vas subiendo hasta el Negro (arquitectura avanzada). Cada cinturón se desbloquea "
            + "cuando dominas el anterior. Este sistema se implementa conectando el Progress Service "
            + "con el Dashboard del frontend.",
            List.of(

                section("1. Los 6 cinturones",
                    "<table class='table table-sm table-dark'>"
                    + "<thead><tr><th>Cinturón</th><th>Código</th><th>Temas</th><th>Requisito</th></tr></thead>"
                    + "<tbody>"
                    + "<tr><td>⬜ Blanco</td><td>BLANCO</td><td>Fundamentos Spring, IoC, DI, beans</td><td>Siempre desbloqueado</td></tr>"
                    + "<tr><td>🟡 Amarillo</td><td>AMARILLO</td><td>REST APIs, controllers, HTTP</td><td>Dominar Blanco</td></tr>"
                    + "<tr><td>🟠 Naranja</td><td>NARANJA</td><td>JPA, base de datos, entidades</td><td>Dominar Amarillo</td></tr>"
                    + "<tr><td>🟢 Verde</td><td>VERDE</td><td>Security, JWT, autenticación</td><td>Dominar Naranja</td></tr>"
                    + "<tr><td>🟤 Marrón</td><td>MARRON</td><td>Microservicios, Eureka, Gateway</td><td>Dominar Verde</td></tr>"
                    + "<tr><td>⬛ Negro</td><td>NEGRO</td><td>Docker, testing, arquitectura avanzada</td><td>Dominar Marrón</td></tr>"
                    + "</tbody></table>"
                    + "<p><b>\"Dominar\"</b> = ≥80% de acierto con mínimo 10 intentos en ese cinturón (lo calculamos en Progress Service).</p>"),

                section("2. Lógica de desbloqueo en el DashboardController",
                    "<p>El desbloqueo se calcula en el <b>frontend</b>, no en el backend. ¿Por qué? "
                    + "Porque es solo lógica de visualización — qué botones mostrar y cuáles desactivar. "
                    + "Los datos vienen del Progress Service.</p>"
                    + "<pre><code>// En DashboardController.java\n"
                    + "\n"
                    + "// Orden de cinturones (array constante)\n"
                    + "private static final String[] BELT_ORDER =\n"
                    + "    {\"BLANCO\",\"AMARILLO\",\"NARANJA\",\"VERDE\",\"MARRON\",\"NEGRO\"};\n"
                    + "\n"
                    + "// Después de obtener el progreso del Progress Service:\n"
                    + "Map&lt;String, Boolean&gt; unlockedMap = new LinkedHashMap&lt;&gt;();\n"
                    + "Map&lt;String, Boolean&gt; masteredMap = new LinkedHashMap&lt;&gt;();\n"
                    + "Map&lt;String, Integer&gt; percentageMap = new LinkedHashMap&lt;&gt;();\n"
                    + "\n"
                    + "boolean previousMastered = true; // BLANCO siempre desbloqueado\n"
                    + "\n"
                    + "for (String beltCode : BELT_ORDER) {\n"
                    + "    // Un cinturón se desbloquea si el anterior está dominado\n"
                    + "    boolean unlocked = previousMastered;\n"
                    + "    unlockedMap.put(beltCode, unlocked);\n"
                    + "\n"
                    + "    // Obtener datos del Progress Service\n"
                    + "    Map&lt;String, Object&gt; bp = beltProgressMap.get(beltCode);\n"
                    + "    boolean mastered = false;\n"
                    + "    int percentage = 0;\n"
                    + "\n"
                    + "    if (bp != null) {\n"
                    + "        int correctCount =\n"
                    + "            ((Number) bp.getOrDefault(\"correctCount\", 0))\n"
                    + "            .intValue();\n"
                    + "        int attemptCount =\n"
                    + "            ((Number) bp.getOrDefault(\"attemptCount\", 0))\n"
                    + "            .intValue();\n"
                    + "        mastered = bp.get(\"mastered\") != null\n"
                    + "            && (Boolean) bp.get(\"mastered\");\n"
                    + "        percentage = attemptCount > 0\n"
                    + "            ? (correctCount * 100) / attemptCount : 0;\n"
                    + "    }\n"
                    + "\n"
                    + "    masteredMap.put(beltCode, mastered);\n"
                    + "    percentageMap.put(beltCode, percentage);\n"
                    + "\n"
                    + "    // Para el siguiente cinturón\n"
                    + "    previousMastered = mastered;\n"
                    + "}\n"
                    + "\n"
                    + "model.addAttribute(\"unlockedMap\", unlockedMap);\n"
                    + "model.addAttribute(\"masteredMap\", masteredMap);\n"
                    + "model.addAttribute(\"percentageMap\", percentageMap);</code></pre>"
                    + "<p><b>La clave es <code>previousMastered</code>:</b> arranca en <code>true</code> (Blanco siempre desbloqueado), "
                    + "y para cada cinturón siguiente, solo se desbloquea si el anterior está dominado. "
                    + "Es un recorrido lineal del array de cinturones.</p>"),

                section("3. Cómo se obtienen los datos del Progress Service",
                    "<p>El DashboardController llama al Gateway para obtener el progreso:</p>"
                    + "<pre><code>// Llamar al Progress Service vía Gateway\n"
                    + "try {\n"
                    + "    var response = restTemplate.exchange(\n"
                    + "        gatewayUrl + \"/api/progress/\" + username,\n"
                    + "        HttpMethod.GET, entity,\n"
                    + "        new ParameterizedTypeReference\n"
                    + "            &lt;Map&lt;String, Object&gt;&gt;() {});\n"
                    + "\n"
                    + "    Map&lt;String, Object&gt; progressData = response.getBody();\n"
                    + "\n"
                    + "    // progressData contiene:\n"
                    + "    // {\n"
                    + "    //   \"userProgress\": {\n"
                    + "    //     \"totalCorrect\": 45,\n"
                    + "    //     \"totalAttempted\": 60,\n"
                    + "    //     \"currentStreak\": 3,\n"
                    + "    //     \"bestStreak\": 5\n"
                    + "    //   },\n"
                    + "    //   \"beltProgress\": [\n"
                    + "    //     {\"beltLevel\":\"BLANCO\",\"correctCount\":20,\n"
                    + "    //      \"attemptCount\":22,\"mastered\":true},\n"
                    + "    //     {\"beltLevel\":\"AMARILLO\",\"correctCount\":5,\n"
                    + "    //      \"attemptCount\":8,\"mastered\":false}\n"
                    + "    //   ]\n"
                    + "    // }\n"
                    + "\n"
                    + "} catch (Exception ignored) {\n"
                    + "    // Si Progress Service no está disponible,\n"
                    + "    // todo queda en 0 — el dashboard funciona igual\n"
                    + "}</code></pre>"
                    + "<p>📌 El <code>catch</code> vacío es intencional: si Progress Service está caído, "
                    + "el Dashboard muestra todo en 0 pero sigue funcionando. No es crítico.</p>"),

                section("4. Renderizado en dashboard.html",
                    "<p>Cada tarjeta de cinturón usa las 3 maps para mostrar el estado:</p>"
                    + "<pre><code>&lt;div th:each=\"belt : ${belts}\" class=\"col-md-4\"&gt;\n"
                    + "  &lt;div class=\"card belt-card\"\n"
                    + "    th:with=\"\n"
                    + "      beltUnlocked=${unlockedMap != null\n"
                    + "        ? unlockedMap.getOrDefault(belt[0], true) : true},\n"
                    + "      beltMastered=${masteredMap != null\n"
                    + "        ? masteredMap.getOrDefault(belt[0], false) : false},\n"
                    + "      beltPct=${percentageMap != null\n"
                    + "        ? percentageMap.getOrDefault(belt[0], 0) : 0}\"\n"
                    + "    th:classappend=\"${!beltUnlocked} ? ' opacity-50' : ''\"&gt;\n"
                    + "\n"
                    + "    &lt;!-- Badge: ⭐ Mastered o 🔒 Locked --&gt;\n"
                    + "    &lt;span th:if=\"${beltMastered}\"\n"
                    + "      class=\"badge bg-success\"&gt;\n"
                    + "      ⭐ Mastered&lt;/span&gt;\n"
                    + "    &lt;span th:if=\"${!beltUnlocked}\"\n"
                    + "      class=\"badge bg-secondary\"&gt;\n"
                    + "      🔒 Locked&lt;/span&gt;\n"
                    + "\n"
                    + "    &lt;!-- Barra de progreso --&gt;\n"
                    + "    &lt;div class=\"progress\"&gt;\n"
                    + "      &lt;div class=\"progress-bar\"\n"
                    + "        th:classappend=\"${beltMastered} ? 'bg-success'\n"
                    + "          : (${beltPct >= 50} ? 'bg-warning' : 'bg-primary')\"\n"
                    + "        th:style=\"'width: ' + ${beltPct} + '%'\"&gt;\n"
                    + "      &lt;/div&gt;\n"
                    + "    &lt;/div&gt;\n"
                    + "\n"
                    + "    &lt;!-- Botones: Study + Quiz o Locked --&gt;\n"
                    + "    &lt;div th:if=\"${beltUnlocked}\"&gt;\n"
                    + "      &lt;a th:href=\"@{/study(difficulty=${belt[0]})}\"&gt;Study&lt;/a&gt;\n"
                    + "      &lt;a th:href=\"@{/quiz(difficulty=${belt[0]})}\"&gt;Quiz&lt;/a&gt;\n"
                    + "    &lt;/div&gt;\n"
                    + "    &lt;div th:unless=\"${beltUnlocked}\"&gt;\n"
                    + "      &lt;button disabled&gt;🔒 Master previous belt&lt;/button&gt;\n"
                    + "    &lt;/div&gt;\n"
                    + "  &lt;/div&gt;\n"
                    + "&lt;/div&gt;</code></pre>"
                    + "<p><b>Thymeleaf: <code>th:with</code></b> — Crea variables locales dentro de un elemento. "
                    + "Así no repites <code>unlockedMap.getOrDefault(belt[0], true)</code> en cada uso.</p>"
                    + "<p><b>Colores de la barra:</b></p>"
                    + "<ul>"
                    + "<li>Dominado (mastered) → <span style='color:#198754'><b>Verde</b></span></li>"
                    + "<li>≥50% → <span style='color:#ffc107'><b>Amarillo</b></span> (warning)</li>"
                    + "<li>&lt;50% → <span style='color:#0d6efd'><b>Azul</b></span> (primary)</li>"
                    + "</ul>"),

                section("5. El flujo completo de progresión",
                    "<pre><code>1. Usuario nuevo → todo en 0\n"
                    + "   BLANCO: 🔓 desbloqueado (siempre)\n"
                    + "   AMARILLO → NEGRO: 🔒 bloqueados\n"
                    + "\n"
                    + "2. Estudia flashcards BLANCO, hace quizzes\n"
                    + "   → Progress Service registra cada respuesta\n"
                    + "   → BeltProgress BLANCO: correctCount=15, attemptCount=18\n"
                    + "   → percentage = 83% → mastered = true ✅\n"
                    + "\n"
                    + "3. Refresca el Dashboard\n"
                    + "   → Frontend pide GET /api/progress/berto\n"
                    + "   → Calcula: BLANCO mastered → AMARILLO se desbloquea 🔓\n"
                    + "   → AMARILLO aparece con botones activos\n"
                    + "\n"
                    + "4. Estudia AMARILLO...\n"
                    + "   → Cuando mastered=true → NARANJA se desbloquea\n"
                    + "   → Y así hasta NEGRO\n"
                    + "\n"
                    + "5. Todos mastered → ¡Cinturón Negro! 🥋⬛</code></pre>"),

                section("6. Integración: todas las piezas juntas",
                    "<p>El sistema de cinturones conecta <b>3 servicios</b>:</p>"
                    + "<pre><code>┌─────────────────┐\n"
                    + "│ Content Service  │  Tiene las flashcards/quizzes\n"
                    + "│ (:8083)          │  por cinturón (difficulty)\n"
                    + "└────────┬────────┘\n"
                    + "         │\n"
                    + "         │ Flashcards del cinturón X\n"
                    + "         │\n"
                    + "┌────────▼────────┐\n"
                    + "│ Frontend (:8090) │  Muestra tarjetas, calcula\n"
                    + "│                  │  desbloqueo, renderiza UI\n"
                    + "└────────┬────────┘\n"
                    + "         │\n"
                    + "         │ Registra respuesta + pide progreso\n"
                    + "         │\n"
                    + "┌────────▼────────┐\n"
                    + "│ Progress Service │  Calcula mastered (80%/10+)\n"
                    + "│ (:8084)          │  Guarda racha, aciertos\n"
                    + "└─────────────────┘</code></pre>"
                    + "<p>Cada servicio hace una cosa. Ninguno sabe de los otros directamente — "
                    + "se comunican a través del Gateway.</p>"),

                section("⚠️ Errores comunes",
                    "<table class='table table-sm table-dark'>"
                    + "<thead><tr><th>Error</th><th>Causa</th><th>Solución</th></tr></thead>"
                    + "<tbody>"
                    + "<tr><td>Todos los cinturones desbloqueados</td>"
                    + "<td>Progress Service no está corriendo → todo fallback a defaults</td>"
                    + "<td>Arranca progress-service. Sin él, <code>unlockedMap</code> no se llena y todo queda desbloqueado por defecto</td></tr>"
                    + "<tr><td>Barra de progreso siempre en 0%</td>"
                    + "<td>Las respuestas no se registran en progress-service</td>"
                    + "<td>Verifica que Study y Quiz llaman a <code>POST /api/progress/record</code></td></tr>"
                    + "<tr><td>Cinturón no se desbloquea con 80%</td>"
                    + "<td>Menos de 10 intentos</td>"
                    + "<td>Necesitas ≥10 intentos. Haz más quizzes o estudia más flashcards de ese cinturón</td></tr>"
                    + "<tr><td><code>ClassCastException</code> en <code>(Boolean) bp.get(\"mastered\")</code></td>"
                    + "<td>El JSON devuelve mastered como String en vez de boolean</td>"
                    + "<td>Usa <code>Boolean.valueOf(bp.get(\"mastered\").toString())</code> como defensa</td></tr>"
                    + "</tbody></table>"),

                section("💡 Conceptos para la entrevista",
                    "<ul>"
                    + "<li><b>Gamificación</b> — Aplicar mecánicas de juego (progresión, desbloqueo, rachas) al aprendizaje. "
                    + "Mejora la motivación y retención</li>"
                    + "<li><b>LinkedHashMap</b> — Un HashMap que mantiene el <b>orden de inserción</b>. "
                    + "Importante aquí porque los cinturones deben estar en orden (Blanco→Negro)</li>"
                    + "<li><b>Separación de responsabilidades</b> — Content Service no sabe nada de progreso. "
                    + "Progress Service no sabe nada de flashcards. El frontend orquesta ambos</li>"
                    + "<li><b>Graceful degradation</b> — Si Progress Service cae, el Dashboard sigue funcionando "
                    + "(con todo en 0). Esto es un patrón de resiliencia en microservicios</li>"
                    + "</ul>"),

                section("✅ Checklist antes de continuar",
                    "<ul>"
                    + "<li>☐ DashboardController calcula unlockedMap, masteredMap, percentageMap</li>"
                    + "<li>☐ dashboard.html muestra badges (Mastered/Locked) y barras de progreso</li>"
                    + "<li>☐ Cinturones bloqueados tienen opacity-50 y botón desactivado</li>"
                    + "<li>☐ BLANCO siempre desbloqueado</li>"
                    + "<li>☐ Con ≥80% y ≥10 intentos en un cinturón → se marca mastered → siguiente se desbloquea</li>"
                    + "<li>☐ Si Progress Service está caído → Dashboard funciona con defaults</li>"
                    + "<li>☐ Commit: <code>git commit -m \"Add belt unlock system\"</code></li>"
                    + "</ul>"
                    + "<p>¡Sistema de cinturones completo! 🥋 Ahora vamos con los <b>Ejercicios de Código</b> — "
                    + "para practicar escribiendo Java directamente en la app. 💻</p>")
            ));
    }
}
