server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: false
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: false
