spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dojo_content
    username: ${DB_USER:dojo}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    defer-datasource-initialization: false
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: false
