package com.dojo.frontend.controller.guia;

import java.util.*;
import static com.dojo.frontend.controller.guia.GuiaHelper.*;

public class GuiaCapitulo09 {

    public static Map<String, Object> getPaso() {
        return crearPaso(
            9, "Sistema de Quizzes", "bi-patch-question",
                "Los quizzes son preguntas tipo test con 4 opciones (A, B, C, D). "
                + "A diferencia del modo estudio (flashcards), los quizzes evalúan al usuario con puntuación, "
                + "feedback inmediato por pregunta y una página de resultados al final. "
                + "La implementación usa la sesión HTTP del servidor para mantener el estado del quiz.",
                List.of(

                    section("1. Flujo del Quiz",
                        "<p>El quiz tiene <b>3 pantallas</b> y un flujo con estado en sesión:</p>"
                        + "<pre><code>Dashboard → [Start Quiz]\n"
                        + "         → GET /quiz?difficulty=BLANCO\n"
                        + "         → (carga preguntas en sesión)\n"
                        + "         → redirect → GET /quiz/question\n"
                        + "\n"
                        + "Pregunta → quiz.html (muestra pregunta + 4 opciones)\n"
                        + "         → POST /quiz/answer (selectedOption=2)\n"
                        + "         → quiz-feedback.html (✅ o ❌ + respuesta correcta)\n"
                        + "         → GET /quiz/next\n"
                        + "         → redirect → GET /quiz/question (siguiente pregunta)\n"
                        + "\n"
                        + "Última pregunta → [See Results]\n"
                        + "                → GET /quiz/results\n"
                        + "                → quiz-result.html (% + revisión)</code></pre>"
                        + "<p>📌 El estado del quiz (preguntas, índice actual, aciertos) se guarda en la <b>HttpSession</b> del servidor. "
                        + "No se guarda en base de datos ni en el cliente.</p>"),

                    section("2. QuizController del frontend (resumen)",
                        "<p><b>Ruta</b>: <code>.../controller/QuizController.java</code></p>"
                        + "<p>Este controller tiene 5 endpoints. Es el más largo del proyecto:</p>"
                        + "<table class='table table-sm table-dark'>"
                        + "<thead><tr><th>Endpoint</th><th>Qué hace</th></tr></thead>"
                        + "<tbody>"
                        + "<tr><td><code>GET /quiz?difficulty=BLANCO</code></td>"
                        + "<td>Carga quizzes desde el Gateway, los guarda en sesión, redirige a /quiz/question</td></tr>"
                        + "<tr><td><code>GET /quiz/question</code></td>"
                        + "<td>Muestra la pregunta actual (lee el índice de sesión)</td></tr>"
                        + "<tr><td><code>POST /quiz/answer</code></td>"
                        + "<td>Recibe la respuesta, compara con la correcta, registra en progress-service, muestra feedback</td></tr>"
                        + "<tr><td><code>GET /quiz/next</code></td>"
                        + "<td>Incrementa el índice y redirige a /quiz/question</td></tr>"
                        + "<tr><td><code>GET /quiz/results</code></td>"
                        + "<td>Muestra resultados finales, limpia la sesión del quiz</td></tr>"
                        + "</tbody></table>"),

                    section("3. Iniciar el quiz — GET /quiz",
                        "<pre><code>@GetMapping(\"/quiz\")\n"
                        + "public String startQuiz(@RequestParam String difficulty,\n"
                        + "        HttpSession session, Model model) {\n"
                        + "    String token = (String) session.getAttribute(\"token\");\n"
                        + "    if (token == null) return \"redirect:/login\";\n"
                        + "\n"
                        + "    // Pedir quizzes al Gateway\n"
                        + "    HttpHeaders headers = new HttpHeaders();\n"
                        + "    headers.set(\"Authorization\", \"Bearer \" + token);\n"
                        + "    HttpEntity&lt;Void&gt; entity = new HttpEntity&lt;&gt;(headers);\n"
                        + "\n"
                        + "    var response = restTemplate.exchange(\n"
                        + "        gatewayUrl + \"/api/content/quizzes?difficulty=\" + difficulty,\n"
                        + "        HttpMethod.GET, entity,\n"
                        + "        new ParameterizedTypeReference\n"
                        + "            &lt;List&lt;Map&lt;String, Object&gt;&gt;&gt;() {});\n"
                        + "\n"
                        + "    List&lt;Map&lt;String, Object&gt;&gt; quizzes = response.getBody();\n"
                        + "\n"
                        + "    // Guardar estado del quiz en sesión\n"
                        + "    session.setAttribute(\"quizQuestions\", quizzes);\n"
                        + "    session.setAttribute(\"quizDifficulty\", difficulty);\n"
                        + "    session.setAttribute(\"quizCurrentIndex\", 0);\n"
                        + "    session.setAttribute(\"quizCorrect\", 0);\n"
                        + "    session.setAttribute(\"quizTotal\", 0);\n"
                        + "    session.setAttribute(\"quizAnswers\", new ArrayList&lt;&gt;());\n"
                        + "\n"
                        + "    return \"redirect:/quiz/question\";\n"
                        + "}</code></pre>"
                        + "<p>Carga todas las preguntas de una vez y las guarda en sesión. "
                        + "Así no necesitamos llamar al Gateway pregunta por pregunta.</p>"),

                    section("4. Mostrar pregunta — GET /quiz/question",
                        "<pre><code>@GetMapping(\"/quiz/question\")\n"
                        + "public String showQuestion(HttpSession session, Model model) {\n"
                        + "    List&lt;Map&lt;String, Object&gt;&gt; quizzes =\n"
                        + "        (List&lt;Map&lt;String, Object&gt;&gt;)\n"
                        + "        session.getAttribute(\"quizQuestions\");\n"
                        + "    Integer currentIndex =\n"
                        + "        (Integer) session.getAttribute(\"quizCurrentIndex\");\n"
                        + "\n"
                        + "    if (quizzes == null || currentIndex == null)\n"
                        + "        return \"redirect:/dashboard\";\n"
                        + "\n"
                        + "    // ¿Ya acabó?\n"
                        + "    if (currentIndex >= quizzes.size())\n"
                        + "        return \"redirect:/quiz/results\";\n"
                        + "\n"
                        + "    Map&lt;String, Object&gt; currentQuiz = quizzes.get(currentIndex);\n"
                        + "\n"
                        + "    model.addAttribute(\"quiz\", currentQuiz);\n"
                        + "    model.addAttribute(\"questionNumber\", currentIndex + 1);\n"
                        + "    model.addAttribute(\"totalQuestions\", quizzes.size());\n"
                        + "    model.addAttribute(\"correct\",\n"
                        + "        session.getAttribute(\"quizCorrect\"));\n"
                        + "\n"
                        + "    return \"quiz\";\n"
                        + "}</code></pre>"),

                    section("5. Responder — POST /quiz/answer",
                        "<pre><code>@PostMapping(\"/quiz/answer\")\n"
                        + "public String submitAnswer(@RequestParam int selectedOption,\n"
                        + "        HttpSession session, Model model) {\n"
                        + "    // Leer estado de sesión\n"
                        + "    List&lt;Map&lt;String, Object&gt;&gt; quizzes = ...;\n"
                        + "    Integer currentIndex = ...;\n"
                        + "\n"
                        + "    Map&lt;String, Object&gt; currentQuiz = quizzes.get(currentIndex);\n"
                        + "    int correctOption =\n"
                        + "        ((Number) currentQuiz.get(\"correctOption\")).intValue();\n"
                        + "    boolean isCorrect = selectedOption == correctOption;\n"
                        + "\n"
                        + "    // Actualizar contador\n"
                        + "    if (isCorrect) {\n"
                        + "        session.setAttribute(\"quizCorrect\",\n"
                        + "            (Integer) session.getAttribute(\"quizCorrect\") + 1);\n"
                        + "    }\n"
                        + "    session.setAttribute(\"quizTotal\",\n"
                        + "        (Integer) session.getAttribute(\"quizTotal\") + 1);\n"
                        + "\n"
                        + "    // Registrar en progress-service (best-effort)\n"
                        + "    try {\n"
                        + "        restTemplate.postForEntity(\n"
                        + "            gatewayUrl + \"/api/progress/record\",\n"
                        + "            Map.of(\"username\", username,\n"
                        + "                   \"beltLevel\", difficulty,\n"
                        + "                   \"correct\", isCorrect),\n"
                        + "            Object.class);\n"
                        + "    } catch (Exception ignored) {}\n"
                        + "\n"
                        + "    // Guardar respuesta para la revisión final\n"
                        + "    answers.add(Map.of(\n"
                        + "        \"question\", currentQuiz.get(\"question\"),\n"
                        + "        \"correct\", isCorrect,\n"
                        + "        \"correctAnswer\", \"A: \" + correctOptionText));\n"
                        + "\n"
                        + "    // Pasar datos al template de feedback\n"
                        + "    model.addAttribute(\"isCorrect\", isCorrect);\n"
                        + "    model.addAttribute(\"selectedOption\", selectedOption);\n"
                        + "    model.addAttribute(\"correctOption\", correctOption);\n"
                        + "    model.addAttribute(\"hasNext\",\n"
                        + "        currentIndex + 1 < quizzes.size());\n"
                        + "\n"
                        + "    return \"quiz-feedback\";\n"
                        + "}</code></pre>"
                        + "<p><b>Puntos clave:</b></p>"
                        + "<ul>"
                        + "<li>Compara <code>selectedOption</code> (del formulario) con <code>correctOption</code> (del quiz)</li>"
                        + "<li>Actualiza contadores en sesión sin tocar base de datos</li>"
                        + "<li>Registra en progress-service como <b>best-effort</b> (si falla, no importa — el quiz sigue)</li>"
                        + "<li>Guarda cada respuesta en una lista para la revisión final</li>"
                        + "</ul>"),

                    section("6. quiz.html — Pantalla de pregunta",
                        "<p>Muestra la pregunta con 4 opciones como radio buttons:</p>"
                        + "<pre><code>&lt;form action=\"/quiz/answer\" method=\"post\"&gt;\n"
                        + "  &lt;div class=\"list-group mb-4\"&gt;\n"
                        + "\n"
                        + "    &lt;label class=\"list-group-item list-group-item-action\"&gt;\n"
                        + "      &lt;input type=\"radio\" name=\"selectedOption\"\n"
                        + "             value=\"0\" required&gt;\n"
                        + "      &lt;span class=\"badge bg-secondary\"&gt;A&lt;/span&gt;\n"
                        + "      &lt;span th:text=\"${quiz['optionA']}\"&gt;Option A&lt;/span&gt;\n"
                        + "    &lt;/label&gt;\n"
                        + "\n"
                        + "    &lt;!-- Repetir para B (value=1), C (value=2), D (value=3) --&gt;\n"
                        + "\n"
                        + "  &lt;/div&gt;\n"
                        + "  &lt;button type=\"submit\" class=\"btn btn-primary btn-lg\"&gt;\n"
                        + "    Submit Answer\n"
                        + "  &lt;/button&gt;\n"
                        + "&lt;/form&gt;</code></pre>"
                        + "<p>Incluye una barra de progreso arriba (<code>Question 3 / 5</code>) y un contador de aciertos.</p>"),

                    section("7. quiz-feedback.html — Feedback inmediato",
                        "<p>Después de cada respuesta, muestra si acertó o falló:</p>"
                        + "<pre><code>&lt;!-- Header verde (correcto) o rojo (incorrecto) --&gt;\n"
                        + "&lt;div class=\"card-header\"\n"
                        + "     th:classappend=\"${isCorrect}\n"
                        + "         ? 'bg-success text-white'\n"
                        + "         : 'bg-danger text-white'\"&gt;\n"
                        + "  &lt;h5&gt;\n"
                        + "    &lt;span th:text=\"${isCorrect}\n"
                        + "        ? 'Correct!' : 'Incorrect'\"&gt;&lt;/span&gt;\n"
                        + "  &lt;/h5&gt;\n"
                        + "&lt;/div&gt;\n"
                        + "\n"
                        + "&lt;!-- Lista de opciones con colores --&gt;\n"
                        + "&lt;div th:each=\"opt, iter : ${optionKeys}\"\n"
                        + "     class=\"list-group-item\"\n"
                        + "     th:classappend=\"\n"
                        + "         ${iter.index == correctOption}\n"
                        + "             ? ' list-group-item-success'\n"
                        + "         : (${iter.index == selectedOption and !isCorrect}\n"
                        + "             ? ' list-group-item-danger' : '')\"&gt;\n"
                        + "  &lt;span th:text=\"${quiz[opt]}\"&gt;Option&lt;/span&gt;\n"
                        + "  &lt;i th:if=\"${iter.index == correctOption}\"\n"
                        + "     class=\"bi bi-check-lg text-success\"&gt;&lt;/i&gt;\n"
                        + "  &lt;i th:if=\"${iter.index == selectedOption and !isCorrect}\"\n"
                        + "     class=\"bi bi-x-lg text-danger\"&gt;&lt;/i&gt;\n"
                        + "&lt;/div&gt;\n"
                        + "\n"
                        + "&lt;!-- Botón siguiente o ver resultados --&gt;\n"
                        + "&lt;a th:if=\"${hasNext}\" href=\"/quiz/next\"\n"
                        + "   class=\"btn btn-primary\"&gt;Next Question&lt;/a&gt;\n"
                        + "&lt;a th:unless=\"${hasNext}\" href=\"/quiz/results\"\n"
                        + "   class=\"btn btn-success\"&gt;See Results&lt;/a&gt;</code></pre>"
                        + "<p>La respuesta correcta se pinta <span style='color:#198754'><b>verde</b></span>, "
                        + "la incorrecta seleccionada se pinta <span style='color:#dc3545'><b>roja</b></span>. "
                        + "Todas las opciones se muestran para que aprendas de los errores.</p>"),

                    section("8. quiz-result.html — Resultados finales",
                        "<p>La pantalla final del quiz muestra:</p>"
                        + "<ul>"
                        + "<li><b>Porcentaje</b> grande y coloreado (verde ≥80%, amarillo ≥50%, rojo &lt;50%)</li>"
                        + "<li><b>Barra de progreso</b> visual</li>"
                        + "<li><b>Mensaje motivacional</b> según el resultado</li>"
                        + "<li><b>Botones</b>: Retry Quiz, Study Flashcards, Dashboard</li>"
                        + "<li><b>Revisión de respuestas</b> — lista de todas las preguntas con ✅/❌ y la respuesta correcta</li>"
                        + "</ul>"
                        + "<pre><code>&lt;!-- Porcentaje grande --&gt;\n"
                        + "&lt;div class=\"display-1 fw-bold\"\n"
                        + "     th:classappend=\"${percentage >= 80}\n"
                        + "         ? 'text-success'\n"
                        + "         : (${percentage >= 50}\n"
                        + "             ? 'text-warning' : 'text-danger')\"&gt;\n"
                        + "  &lt;span th:text=\"${percentage}\"&gt;0&lt;/span&gt;%\n"
                        + "&lt;/div&gt;\n"
                        + "\n"
                        + "&lt;!-- Mensaje según resultado --&gt;\n"
                        + "&lt;div th:if=\"${percentage >= 80}\" class=\"alert alert-success\"&gt;\n"
                        + "  ⭐ Excellent! You're mastering this belt level!\n"
                        + "&lt;/div&gt;\n"
                        + "&lt;div th:if=\"${percentage >= 50 and percentage < 80}\"\n"
                        + "     class=\"alert alert-warning\"&gt;\n"
                        + "  ⚡ Good effort! Keep practicing.\n"
                        + "&lt;/div&gt;\n"
                        + "&lt;div th:if=\"${percentage < 50}\" class=\"alert alert-info\"&gt;\n"
                        + "  📚 Review the flashcards and try again!\n"
                        + "&lt;/div&gt;</code></pre>"
                        + "<p>La revisión de respuestas usa <code>th:each</code> sobre la lista <code>answers</code> que se fue "
                        + "construyendo pregunta a pregunta. El controller limpia la sesión al mostrar los resultados.</p>"),

                    section("9. Gestión de estado con HttpSession",
                        "<p>Los quizzes usan la sesión HTTP para mantener el estado entre peticiones. "
                        + "Es un patrón importante de entender:</p>"
                        + "<table class='table table-sm table-dark'>"
                        + "<thead><tr><th>Atributo de sesión</th><th>Tipo</th><th>Para qué</th></tr></thead>"
                        + "<tbody>"
                        + "<tr><td><code>quizQuestions</code></td><td>List&lt;Map&gt;</td><td>Todas las preguntas cargadas</td></tr>"
                        + "<tr><td><code>quizCurrentIndex</code></td><td>Integer</td><td>Índice de la pregunta actual (0-based)</td></tr>"
                        + "<tr><td><code>quizCorrect</code></td><td>Integer</td><td>Contador de aciertos</td></tr>"
                        + "<tr><td><code>quizTotal</code></td><td>Integer</td><td>Contador de intentos</td></tr>"
                        + "<tr><td><code>quizDifficulty</code></td><td>String</td><td>Cinturón actual (BLANCO, etc.)</td></tr>"
                        + "<tr><td><code>quizAnswers</code></td><td>List&lt;Map&gt;</td><td>Historial para la revisión final</td></tr>"
                        + "</tbody></table>"
                        + "<p><b>¿Por qué sesión y no base de datos?</b></p>"
                        + "<ul>"
                        + "<li>El quiz es <b>efímero</b> — solo importa mientras lo estás haciendo</li>"
                        + "<li>Lo que sí se persiste es el <b>progreso</b> (vía progress-service) — aciertos, racha, cinturones</li>"
                        + "<li>Si cierras el navegador a mitad del quiz, se pierde. No es un problema — empiezas otro</li>"
                        + "</ul>"
                        + "<p>📌 En una app de producción podrías usar Redis para sesiones distribuidas. "
                        + "Aquí usamos la sesión en memoria de Tomcat (que viene con spring-boot-starter-web).</p>"),

                    section("⚠️ Errores comunes",
                        "<table class='table table-sm table-dark'>"
                        + "<thead><tr><th>Error</th><th>Causa</th><th>Solución</th></tr></thead>"
                        + "<tbody>"
                        + "<tr><td>Redirige al dashboard al entrar al quiz</td>"
                        + "<td>No hay quizzes para ese cinturón en el DataSeeder</td>"
                        + "<td>Verifica que <code>seedQuizzes()</code> tiene datos para ese nivel de dificultad</td></tr>"
                        + "<tr><td>Siempre dice \"Incorrect\" aunque aciertes</td>"
                        + "<td>El <code>correctOption</code> no coincide con el índice del radio button</td>"
                        + "<td>Las opciones van de 0 a 3 (A=0, B=1, C=2, D=3). Revisa que el DataSeeder pone el índice correcto</td></tr>"
                        + "<tr><td>El porcentaje final es NaN o raro</td>"
                        + "<td>División por cero si no hay preguntas</td>"
                        + "<td>El controller calcula <code>(correct * 100) / total</code>. Si total=0, devuelve 0</td></tr>"
                        + "<tr><td>La sesión se pierde entre preguntas</td>"
                        + "<td>Cookies deshabilitadas en el navegador</td>"
                        + "<td>La sesión HTTP depende de una cookie (<code>JSESSIONID</code>). Verifica que las cookies están activas</td></tr>"
                        + "</tbody></table>"),

                    section("💡 Conceptos para la entrevista",
                        "<ul>"
                        + "<li><b>HttpSession</b> — Almacenamiento por usuario en el servidor. Se identifica con una cookie (JSESSIONID). "
                        + "Útil para datos temporales que no merecen persistirse</li>"
                        + "<li><b>PRG pattern (Post-Redirect-Get)</b> — Después de un POST (/quiz/answer), "
                        + "redirigimos con GET (/quiz/next → /quiz/question). Esto evita que al refrescar el navegador se reenvíe el POST</li>"
                        + "<li><b>Best-effort</b> — El registro en progress-service está en try-catch con catch vacío. "
                        + "Si falla, el quiz sigue funcionando. Es un patrón válido cuando la acción secundaria no es crítica</li>"
                        + "</ul>"),

                    section("✅ Checklist antes de continuar",
                        "<ul>"
                        + "<li>☐ QuizController.java creado (5 endpoints)</li>"
                        + "<li>☐ quiz.html — muestra pregunta con 4 opciones</li>"
                        + "<li>☐ quiz-feedback.html — feedback verde/rojo por pregunta</li>"
                        + "<li>☐ quiz-result.html — resultados finales con revisión</li>"
                        + "<li>☐ Puedes hacer un quiz completo: Dashboard → Quiz → responder → ver resultados</li>"
                        + "<li>☐ Commit: <code>git commit -m \"Add quiz system with feedback and results\"</code></li>"
                        + "</ul>"
                        + "<p>¡Sistema de quizzes completo! 📝 Ahora vamos con el <b>Progress Service</b> — "
                        + "para que los aciertos, rachas y cinturones se persistan. 📊</p>")
                ));

    }
}
