package com.dojo.frontend.controller.guia;

import java.util.*;
import static com.dojo.frontend.controller.guia.GuiaHelper.*;

public class GuiaCapitulo14 {

    public static Map<String, Object> getPaso() {
        return crearPaso(
            14, "Guía Integrada (esta guía)", "bi-book",
            "Sí, esta guía que estás leyendo ahora mismo está dentro de la propia aplicación. "
            + "Es un capítulo meta: vamos a documentar cómo se construyó el sistema de la guía. "
            + "Así si en el futuro quieres añadir capítulos o modificar contenido, sabes exactamente cómo hacerlo.",
            List.of(

                section("1. Arquitectura de la guía",
                    "<p>La guía NO usa archivos markdown ni base de datos — todo el contenido está <b>en código Java</b>:</p>"
                    + "<pre><code>controller/\n"
                    + "├── GuiaController.java          ← Routing + carga de pasos\n"
                    + "└── guia/\n"
                    + "    ├── GuiaHelper.java           ← Métodos crearPaso() y section()\n"
                    + "    ├── GuiaCapitulo01.java       ← Preparación\n"
                    + "    ├── GuiaCapitulo02.java       ← Estructura\n"
                    + "    ├── ...\n"
                    + "    └── GuiaCapitulo16.java       ← Arranque\n"
                    + "\n"
                    + "templates/\n"
                    + "└── guia.html                     ← Template que renderiza</code></pre>"
                    + "<p><b>¿Por qué en Java y no en markdown o BD?</b></p>"
                    + "<ul>"
                    + "<li>Un solo JAR con todo — no necesitas archivos externos</li>"
                    + "<li>Se compila — si hay errores de sintaxis, los detectas al compilar</li>"
                    + "<li>Fácil de refactorizar con IntelliJ (buscar, reemplazar, renombrar)</li>"
                    + "<li>La desventaja: editar HTML dentro de strings Java es verboso. Pero funciona</li>"
                    + "</ul>"),

                section("2. GuiaController.java (57 líneas)",
                    "<p>El controller es minimalista — solo carga los pasos y los pasa al template:</p>"
                    + "<pre><code>@Controller\n"
                    + "public class GuiaController {\n"
                    + "\n"
                    + "    private static final List&lt;Map&lt;String, Object&gt;&gt;\n"
                    + "        PASOS = new ArrayList&lt;&gt;();\n"
                    + "\n"
                    + "    static {\n"
                    + "        PASOS.add(GuiaCapitulo01.getPaso());\n"
                    + "        PASOS.add(GuiaCapitulo02.getPaso());\n"
                    + "        // ... hasta GuiaCapitulo16\n"
                    + "    }\n"
                    + "\n"
                    + "    @GetMapping(\"/guia\")\n"
                    + "    public String guia(HttpSession session, Model model,\n"
                    + "            @RequestParam(defaultValue = \"0\") int paso) {\n"
                    + "\n"
                    + "        String token = (String) session.getAttribute(\"token\");\n"
                    + "        if (token == null) return \"redirect:/login\";\n"
                    + "\n"
                    + "        model.addAttribute(\"pasos\", PASOS);\n"
                    + "        model.addAttribute(\"pasoActual\", paso);\n"
                    + "        model.addAttribute(\"totalPasos\", PASOS.size());\n"
                    + "\n"
                    + "        if (paso >= 0 && paso < PASOS.size()) {\n"
                    + "            model.addAttribute(\"detalle\", PASOS.get(paso));\n"
                    + "        }\n"
                    + "\n"
                    + "        return \"guia\";\n"
                    + "    }\n"
                    + "}</code></pre>"
                    + "<p>URL: <code>/guia?paso=0</code> (0-indexed). Sin parámetro → paso 0 (primer capítulo).</p>"),

                section("3. GuiaHelper.java — Utilidades",
                    "<pre><code>public class GuiaHelper {\n"
                    + "\n"
                    + "    // Crea un paso completo\n"
                    + "    public static Map&lt;String, Object&gt; crearPaso(\n"
                    + "            int num, String title, String icon,\n"
                    + "            String intro,\n"
                    + "            List&lt;Map&lt;String, String&gt;&gt; sections) {\n"
                    + "        Map&lt;String, Object&gt; paso = new LinkedHashMap&lt;&gt;();\n"
                    + "        paso.put(\"num\", num);\n"
                    + "        paso.put(\"title\", title);\n"
                    + "        paso.put(\"icon\", icon);\n"
                    + "        paso.put(\"intro\", intro);\n"
                    + "        paso.put(\"sections\", sections);\n"
                    + "        return paso;\n"
                    + "    }\n"
                    + "\n"
                    + "    // Crea una sección dentro de un paso\n"
                    + "    public static Map&lt;String, String&gt; section(\n"
                    + "            String title, String content) {\n"
                    + "        Map&lt;String, String&gt; s = new LinkedHashMap&lt;&gt;();\n"
                    + "        s.put(\"title\", title);\n"
                    + "        s.put(\"content\", content);\n"
                    + "        return s;\n"
                    + "    }\n"
                    + "}</code></pre>"
                    + "<p>Dos métodos estáticos que se importan con <code>import static</code> en cada capítulo.</p>"),

                section("4. Estructura de un capítulo",
                    "<p>Cada capítulo (<code>GuiaCapituloXX.java</code>) sigue este patrón:</p>"
                    + "<pre><code>package com.dojo.frontend.controller.guia;\n"
                    + "\n"
                    + "import java.util.*;\n"
                    + "import static com.dojo.frontend.controller.guia\n"
                    + "    .GuiaHelper.*;\n"
                    + "\n"
                    + "public class GuiaCapitulo01 {\n"
                    + "\n"
                    + "    public static Map&lt;String, Object&gt; getPaso() {\n"
                    + "        return crearPaso(\n"
                    + "            1,                           // Número\n"
                    + "            \"Título del Capítulo\",      // Título\n"
                    + "            \"bi-tools\",                 // Icono Bootstrap\n"
                    + "            \"Texto de introducción...\", // Intro\n"
                    + "            List.of(\n"
                    + "                section(\"1. Sección\",\n"
                    + "                    \"&lt;p&gt;HTML aquí&lt;/p&gt;\"),\n"
                    + "                section(\"2. Otra sección\",\n"
                    + "                    \"&lt;pre&gt;&lt;code&gt;código&lt;/code&gt;&lt;/pre&gt;\")\n"
                    + "            ));\n"
                    + "    }\n"
                    + "}</code></pre>"
                    + "<p><b>Reglas del contenido HTML:</b></p>"
                    + "<ul>"
                    + "<li>Se renderiza con <code>th:utext</code> → acepta HTML crudo</li>"
                    + "<li>Código: <code>&lt;pre&gt;&lt;code&gt;...&lt;/code&gt;&lt;/pre&gt;</code></li>"
                    + "<li>Listas: <code>&lt;ul&gt;&lt;li&gt;...&lt;/li&gt;&lt;/ul&gt;</code></li>"
                    + "<li>Tablas: <code>&lt;table class='table table-sm table-dark'&gt;</code></li>"
                    + "<li>Escapar <code>&lt;</code> y <code>&gt;</code> en código Java/XML: usar <code>&amp;lt;</code> y <code>&amp;gt;</code></li>"
                    + "<li>Comillas en Java strings: escapar con <code>\\\"</code> o usar comillas simples en el HTML</li>"
                    + "</ul>"),

                section("5. Template guia.html",
                    "<p>El template tiene 3 zonas:</p>"
                    + "<pre><code>&lt;div class=\"row\"&gt;\n"
                    + "  &lt;!-- SIDEBAR (col-md-3) --&gt;\n"
                    + "  &lt;div class=\"col-md-3\"&gt;\n"
                    + "    &lt;div class=\"list-group\"&gt;\n"
                    + "      &lt;a th:each=\"p, iter : ${pasos}\"\n"
                    + "         th:href=\"@{/guia(paso=${iter.index})}\"\n"
                    + "         th:classappend=\"${iter.index == pasoActual}\n"
                    + "             ? ' active' : ''\"\n"
                    + "         class=\"list-group-item\"&gt;\n"
                    + "        &lt;i th:class=\"${p['icon']}\"&gt;&lt;/i&gt;\n"
                    + "        &lt;span th:text=\"${p['title']}\"&gt;&lt;/span&gt;\n"
                    + "      &lt;/a&gt;\n"
                    + "    &lt;/div&gt;\n"
                    + "  &lt;/div&gt;\n"
                    + "\n"
                    + "  &lt;!-- CONTENIDO (col-md-9) --&gt;\n"
                    + "  &lt;div class=\"col-md-9\"&gt;\n"
                    + "    &lt;!-- Intro --&gt;\n"
                    + "    &lt;div class=\"alert alert-info\"\n"
                    + "         th:utext=\"${detalle['intro']}\"&gt;&lt;/div&gt;\n"
                    + "\n"
                    + "    &lt;!-- Secciones --&gt;\n"
                    + "    &lt;div th:each=\"sec : ${detalle['sections']}\"&gt;\n"
                    + "      &lt;h5 class=\"text-warning\"\n"
                    + "          th:text=\"${sec['title']}\"&gt;&lt;/h5&gt;\n"
                    + "      &lt;div class=\"guia-content\"\n"
                    + "           th:utext=\"${sec['content']}\"&gt;&lt;/div&gt;\n"
                    + "    &lt;/div&gt;\n"
                    + "\n"
                    + "    &lt;!-- Navegación Anterior/Siguiente --&gt;\n"
                    + "    &lt;div class=\"d-flex justify-content-between\"&gt;\n"
                    + "      &lt;a th:if=\"${pasoActual > 0}\"\n"
                    + "         th:href=\"@{/guia(paso=${pasoActual - 1})}\"&gt;\n"
                    + "         ← Anterior&lt;/a&gt;\n"
                    + "      &lt;a th:if=\"${pasoActual < totalPasos - 1}\"\n"
                    + "         th:href=\"@{/guia(paso=${pasoActual + 1})}\"&gt;\n"
                    + "         Siguiente →&lt;/a&gt;\n"
                    + "    &lt;/div&gt;\n"
                    + "  &lt;/div&gt;\n"
                    + "&lt;/div&gt;</code></pre>"
                    + "<p><code>th:utext</code> vs <code>th:text</code>: "
                    + "<code>th:text</code> escapa HTML (seguro). <code>th:utext</code> NO escapa (renderiza HTML crudo). "
                    + "Usamos <code>th:utext</code> porque el contenido incluye tags HTML intencionalmente.</p>"),

                section("6. Estilos del tema oscuro",
                    "<p>Los estilos están inline en <code>guia.html</code>:</p>"
                    + "<pre><code>&lt;style&gt;\n"
                    + ".guia-content {\n"
                    + "    color: #ffffff !important;\n"
                    + "}\n"
                    + ".guia-content pre code {\n"
                    + "    color: #8be9fd !important;  /* Cyan tipo Dracula */\n"
                    + "    background: #000;\n"
                    + "}\n"
                    + ".guia-content a {\n"
                    + "    color: #58a6ff !important;   /* Azul tipo GitHub */\n"
                    + "}\n"
                    + ".guia-content h5 {\n"
                    + "    color: #ffc107 !important;   /* Amarillo warning */\n"
                    + "}\n"
                    + "&lt;/style&gt;</code></pre>"),

                section("7. Cómo añadir un capítulo nuevo",
                    "<ol>"
                    + "<li>Crea <code>GuiaCapituloXX.java</code> en el paquete <code>guia/</code></li>"
                    + "<li>Sigue el patrón: <code>getPaso()</code> con <code>crearPaso()</code> y <code>section()</code></li>"
                    + "<li>En <code>GuiaController.java</code>, añade: <code>PASOS.add(GuiaCapituloXX.getPaso());</code></li>"
                    + "<li>Compila: <code>mvn compile</code></li>"
                    + "<li>Reinicia el frontend</li>"
                    + "<li>El nuevo capítulo aparece automáticamente en el sidebar</li>"
                    + "</ol>"
                    + "<p>📌 Los capítulos se añaden en orden al <code>PASOS</code> list. El número de paso en la URL "
                    + "es el índice del array (0-based), no el número del capítulo.</p>"),

                section("8. Documentación de referencia",
                    "<p>Para más detalles sobre cómo funciona y modificar la guía, consulta:</p>"
                    + "<p><b><code>GUIA-DESARROLLO.md</code></b> — En la raíz del proyecto. Contiene:</p>"
                    + "<ul>"
                    + "<li>Estructura de datos de cada paso</li>"
                    + "<li>Iconos Bootstrap disponibles</li>"
                    + "<li>Reglas de contenido HTML</li>"
                    + "<li>Cómo añadir, modificar y eliminar pasos</li>"
                    + "<li>Estilos CSS del tema oscuro</li>"
                    + "<li>Historial de versiones de la guía</li>"
                    + "</ul>"),

                section("✅ Checklist antes de continuar",
                    "<ul>"
                    + "<li>☐ Entiendes la estructura: GuiaController → GuiaCapituloXX → GuiaHelper</li>"
                    + "<li>☐ Entiendes el template: sidebar + contenido + navegación</li>"
                    + "<li>☐ Sabes la diferencia entre <code>th:text</code> y <code>th:utext</code></li>"
                    + "<li>☐ Sabrías añadir un capítulo nuevo</li>"
                    + "<li>☐ Has consultado <code>GUIA-DESARROLLO.md</code></li>"
                    + "<li>☐ Commit: <code>git commit -m \"Document guide system\"</code></li>"
                    + "</ul>"
                    + "<p>¡Capítulo meta completado! 📖 Ahora vamos con <b>Docker Compose</b> — containerizar toda la arquitectura. 🐳</p>")
            ));
    }
}
