package com.dojo.frontend.controller.guia;

import java.util.*;
import static com.dojo.frontend.controller.guia.GuiaHelper.*;

public class GuiaCapitulo02 {

    public static Map<String, Object> getPaso() {
        return crearPaso(
            2, "Estructura del Proyecto", "bi-folder2-open",
                "Vamos a crear la estructura base: una carpeta raíz que contenga todos los microservicios como proyectos independientes. "
                + "Cada servicio tiene su propio pom.xml y se puede compilar y arrancar por separado. "
                + "Esto es lo más parecido a cómo se trabaja en el mundo real con microservicios.",
                List.of(

                    section("1. Crear la carpeta del proyecto",
                        "<p>En tu terminal (o desde el explorador de archivos), crea la carpeta raíz:</p>"
                        + "<pre><code># Crea la carpeta principal\nmkdir spring-boot-dojo\ncd spring-boot-dojo\n\n# Inicializa Git desde el principio\ngit init</code></pre>"
                        + "<p>Esta carpeta <b>no es un proyecto Maven en sí</b> — es simplemente el contenedor que agrupa todos los servicios. "
                        + "Cada microservicio será un proyecto Spring Boot independiente dentro de esta carpeta.</p>"),

                    section("2. Crear cada microservicio con Spring Initializr",
                        "<p>Vamos a crear cada servicio usando <a href='https://start.spring.io/' target='_blank'>Spring Initializr</a> "
                        + "(la herramienta oficial de Spring para generar proyectos). Puedes hacerlo desde la web o desde IntelliJ:</p>"
                        + "<p><b>Desde IntelliJ:</b></p>"
                        + "<ol>"
                        + "<li><b>File → New → Module</b> (si ya abriste la carpeta spring-boot-dojo) o <b>File → New → Project</b></li>"
                        + "<li>Selecciona <b>Spring Initializr</b> en el panel izquierdo</li>"
                        + "<li>Server URL: <code>https://start.spring.io</code></li>"
                        + "<li>Rellena: Group = <code>com.dojo</code>, Artifact = <code>eureka-server</code> (o el nombre del servicio)</li>"
                        + "<li>Type: <b>Maven</b></li>"
                        + "<li>Language: <b>Java</b></li>"
                        + "<li>Java version: <b>17</b></li>"
                        + "<li>Spring Boot version: <b>3.2.0</b></li>"
                        + "<li>Next → Selecciona las dependencias necesarias (las veremos servicio por servicio)</li>"
                        + "<li>Create → Se genera dentro de spring-boot-dojo/</li>"
                        + "</ol>"
                        + "<p><b>Desde la web</b> (<a href='https://start.spring.io/' target='_blank'>start.spring.io</a>):</p>"
                        + "<ol>"
                        + "<li>Configura lo mismo que arriba</li>"
                        + "<li>Click en <b>Generate</b> → descarga un .zip</li>"
                        + "<li>Descomprime dentro de <code>spring-boot-dojo/</code></li>"
                        + "</ol>"),

                    section("3. Estructura final de carpetas",
                        "<p>Cuando tengamos todos los servicios creados, la estructura será:</p>"
                        + "<pre><code>spring-boot-dojo/\n"
                        + "├── eureka-server/          ← Service Discovery (puerto 8761)\n"
                        + "│   ├── src/\n"
                        + "│   │   └── main/\n"
                        + "│   │       ├── java/com/dojo/eureka/\n"
                        + "│   │       └── resources/\n"
                        + "│   │           └── application.yml\n"
                        + "│   └── pom.xml\n"
                        + "│\n"
                        + "├── auth-service/           ← Autenticación JWT (puerto 8081)\n"
                        + "│   ├── src/main/java/com/dojo/auth/\n"
                        + "│   │   ├── config/\n"
                        + "│   │   ├── controller/\n"
                        + "│   │   ├── dto/\n"
                        + "│   │   ├── entity/\n"
                        + "│   │   ├── repository/\n"
                        + "│   │   └── service/\n"
                        + "│   └── pom.xml\n"
                        + "│\n"
                        + "├── content-service/        ← Contenido: flashcards, quizzes (puerto 8083)\n"
                        + "│   ├── src/main/java/com/dojo/content/\n"
                        + "│   │   ├── config/         ← DataSeeder.java (datos iniciales)\n"
                        + "│   │   ├── controller/\n"
                        + "│   │   ├── dto/\n"
                        + "│   │   ├── entity/\n"
                        + "│   │   ├── repository/\n"
                        + "│   │   └── service/\n"
                        + "│   └── pom.xml\n"
                        + "│\n"
                        + "├── progress-service/       ← Progreso del usuario (puerto 8084)\n"
                        + "│   ├── src/main/java/com/dojo/progress/\n"
                        + "│   │   ├── controller/\n"
                        + "│   │   ├── dto/\n"
                        + "│   │   ├── entity/\n"
                        + "│   │   ├── repository/\n"
                        + "│   │   └── service/\n"
                        + "│   └── pom.xml\n"
                        + "│\n"
                        + "├── api-gateway/            ← Punto de entrada único (puerto 8080)\n"
                        + "│   ├── src/main/java/com/dojo/gateway/\n"
                        + "│   │   └── filter/         ← JwtAuthFilter.java\n"
                        + "│   └── pom.xml\n"
                        + "│\n"
                        + "├── dojo-frontend/          ← Frontend web (puerto 8090)\n"
                        + "│   ├── src/main/java/com/dojo/frontend/\n"
                        + "│   │   ├── config/\n"
                        + "│   │   ├── controller/\n"
                        + "│   │   └── dto/\n"
                        + "│   ├── src/main/resources/\n"
                        + "│   │   ├── templates/      ← HTMLs (Thymeleaf)\n"
                        + "│   │   ├── static/css/     ← Estilos\n"
                        + "│   │   └── application.yml\n"
                        + "│   └── pom.xml\n"
                        + "│\n"
                        + "├── docker-compose.yml\n"
                        + "├── start-all.sh            ← Script para arrancar todo\n"
                        + "├── .gitignore\n"
                        + "└── PROYECTO.md</code></pre>"
                        + "<p>Cada carpeta es un proyecto Spring Boot completo e independiente. "
                        + "No hay un pom.xml padre — cada servicio gestiona sus propias dependencias.</p>"),

                    section("4. El pom.xml de cada servicio (estructura base)",
                        "<p>Todos los servicios comparten esta estructura base en su pom.xml. "
                        + "Lo que cambia son las dependencias específicas de cada uno:</p>"
                        + "<pre><code>&lt;?xml version=\"1.0\" encoding=\"UTF-8\"?&gt;\n"
                        + "&lt;project xmlns=\"http://maven.apache.org/POM/4.0.0\"\n"
                        + "         xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n"
                        + "         xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0\n"
                        + "         https://maven.apache.org/xsd/maven-4.0.0.xsd\"&gt;\n"
                        + "    &lt;modelVersion&gt;4.0.0&lt;/modelVersion&gt;\n"
                        + "\n"
                        + "    &lt;!-- Hereda de Spring Boot --&gt;\n"
                        + "    &lt;parent&gt;\n"
                        + "        &lt;groupId&gt;org.springframework.boot&lt;/groupId&gt;\n"
                        + "        &lt;artifactId&gt;spring-boot-starter-parent&lt;/artifactId&gt;\n"
                        + "        &lt;version&gt;3.2.0&lt;/version&gt;\n"
                        + "        &lt;relativePath/&gt;\n"
                        + "    &lt;/parent&gt;\n"
                        + "\n"
                        + "    &lt;groupId&gt;com.dojo&lt;/groupId&gt;\n"
                        + "    &lt;artifactId&gt;nombre-del-servicio&lt;/artifactId&gt;\n"
                        + "    &lt;version&gt;0.0.1-SNAPSHOT&lt;/version&gt;\n"
                        + "\n"
                        + "    &lt;properties&gt;\n"
                        + "        &lt;java.version&gt;17&lt;/java.version&gt;\n"
                        + "        &lt;spring-cloud.version&gt;2023.0.0&lt;/spring-cloud.version&gt;\n"
                        + "    &lt;/properties&gt;\n"
                        + "\n"
                        + "    &lt;dependencies&gt;\n"
                        + "        &lt;!-- Dependencias específicas del servicio aquí --&gt;\n"
                        + "    &lt;/dependencies&gt;\n"
                        + "\n"
                        + "    &lt;!-- Gestión de versiones de Spring Cloud --&gt;\n"
                        + "    &lt;dependencyManagement&gt;\n"
                        + "        &lt;dependencies&gt;\n"
                        + "            &lt;dependency&gt;\n"
                        + "                &lt;groupId&gt;org.springframework.cloud&lt;/groupId&gt;\n"
                        + "                &lt;artifactId&gt;spring-cloud-dependencies&lt;/artifactId&gt;\n"
                        + "                &lt;version&gt;${spring-cloud.version}&lt;/version&gt;\n"
                        + "                &lt;type&gt;pom&lt;/type&gt;\n"
                        + "                &lt;scope&gt;import&lt;/scope&gt;\n"
                        + "            &lt;/dependency&gt;\n"
                        + "        &lt;/dependencies&gt;\n"
                        + "    &lt;/dependencyManagement&gt;\n"
                        + "\n"
                        + "    &lt;build&gt;\n"
                        + "        &lt;plugins&gt;\n"
                        + "            &lt;plugin&gt;\n"
                        + "                &lt;groupId&gt;org.springframework.boot&lt;/groupId&gt;\n"
                        + "                &lt;artifactId&gt;spring-boot-maven-plugin&lt;/artifactId&gt;\n"
                        + "            &lt;/plugin&gt;\n"
                        + "        &lt;/plugins&gt;\n"
                        + "    &lt;/build&gt;\n"
                        + "&lt;/project&gt;</code></pre>"),

                    section("5. Crear el .gitignore",
                        "<p>Crea el archivo <code>.gitignore</code> en la raíz de <code>spring-boot-dojo/</code>. "
                        + "Esto evita subir archivos compilados, configuración del IDE y logs a Git:</p>"
                        + "<pre><code># Compilados\n"
                        + "**/target/\n"
                        + "**/*.class\n"
                        + "**/*.jar\n"
                        + "**/*.war\n"
                        + "\n"
                        + "# Maven wrapper (si no lo usas)\n"
                        + "**/.mvn/\n"
                        + "**/mvnw\n"
                        + "**/mvnw.cmd\n"
                        + "\n"
                        + "# IntelliJ IDEA\n"
                        + "**/*.iml\n"
                        + "**/.idea/\n"
                        + "\n"
                        + "# Eclipse\n"
                        + "**/.settings/\n"
                        + "**/.classpath\n"
                        + "**/.project\n"
                        + "**/.factorypath\n"
                        + "\n"
                        + "# Logs\n"
                        + "**/logs/\n"
                        + "**/*.log\n"
                        + "\n"
                        + "# H2 Database files\n"
                        + "**/*.db\n"
                        + "**/*.mv.db\n"
                        + "**/*.trace.db</code></pre>"
                        + "<p>Para crear el archivo con el plugin <b>.ignore</b> de IntelliJ:</p>"
                        + "<ol>"
                        + "<li>Click derecho en la raíz del proyecto → New → .ignore File → .gitignore</li>"
                        + "<li>Selecciona las plantillas: <b>Java, Maven, IntelliJ</b></li>"
                        + "<li>Genera el archivo y ajústalo con el contenido de arriba</li>"
                        + "</ol>"),

                    section("6. Abrir el proyecto en IntelliJ",
                        "<p>Ahora abre la carpeta <code>spring-boot-dojo/</code> en IntelliJ:</p>"
                        + "<ol>"
                        + "<li><b>File → Open</b> → selecciona la carpeta <code>spring-boot-dojo/</code></li>"
                        + "<li>IntelliJ preguntará si quieres abrir como proyecto — di que <b>sí</b></li>"
                        + "<li>Si detecta archivos pom.xml dentro, preguntará si quieres importarlos como Maven — di que <b>sí</b></li>"
                        + "<li>Espera a que Maven descargue todas las dependencias (primera vez tarda unos minutos)</li>"
                        + "</ol>"
                        + "<p>En el panel izquierdo (Project) deberías ver todas las carpetas de los microservicios. "
                        + "Si alguna no se reconoce como módulo Maven, haz click derecho → <b>Add as Maven Project</b>.</p>"
                        + "<p>⚠️ <b>Si ves errores rojos en todos los imports:</b> Es que Maven no descargó las dependencias. "
                        + "Abre la pestaña <b>Maven</b> (panel derecho) → click en el botón de <b>Reload</b> (🔄).</p>"),

                    section("7. Primer commit",
                        "<p>Antes de empezar a crear servicios, haz tu primer commit con la estructura base:</p>"
                        + "<pre><code>cd spring-boot-dojo\ngit add .\ngit commit -m \"Estructura inicial del proyecto\"</code></pre>"
                        + "<p>O desde IntelliJ: <b>VCS → Commit</b> (o Ctrl+K), selecciona todos los archivos y escribe el mensaje.</p>"
                        + "<p>💡 <b>Consejo</b>: Haz commits frecuentes. Después de cada paso de esta guía que funcione, commitea. "
                        + "Así si algo se rompe más adelante, puedes volver atrás fácilmente.</p>"),

                    section("💡 ¿Por qué no usamos un pom.xml padre multi-módulo?",
                        "<p>En muchos tutoriales verás que se crea un <b>pom.xml padre</b> con <code>&lt;packaging&gt;pom&lt;/packaging&gt;</code> "
                        + "y <code>&lt;modules&gt;</code> que lista todos los servicios. Esto permite compilar todo con un solo <code>mvn clean install</code>.</p>"
                        + "<p>En este proyecto <b>cada servicio es completamente independiente</b>. ¿Por qué?</p>"
                        + "<ul>"
                        + "<li><b>Más realista</b> — En producción, cada microservicio suele tener su propio repositorio Git</li>"
                        + "<li><b>Independencia</b> — Puedes actualizar Spring Boot en un servicio sin afectar a los demás</li>"
                        + "<li><b>Despliegue independiente</b> — Cada servicio se compila y despliega por separado</li>"
                        + "<li><b>Menos acoplamiento</b> — No hay dependencias entre los pom.xml</li>"
                        + "</ul>"
                        + "<p>La desventaja es que tienes que gestionar versiones en cada pom.xml por separado. "
                        + "Para un proyecto de aprendizaje con 6 servicios, es perfectamente manejable.</p>"
                        + "<p>Si en el futuro quisieras un pom padre, solo tendrías que crear un pom.xml en la raíz con "
                        + "<code>&lt;modules&gt;</code> y cambiar el <code>&lt;parent&gt;</code> de cada servicio para que apunte a él.</p>"),

                    section("✅ Checklist antes de continuar",
                        "<ul>"
                        + "<li>☐ Carpeta <code>spring-boot-dojo/</code> creada</li>"
                        + "<li>☐ <code>git init</code> hecho</li>"
                        + "<li>☐ <code>.gitignore</code> creado</li>"
                        + "<li>☐ Proyecto abierto en IntelliJ</li>"
                        + "<li>☐ Entiendes la estructura de carpetas que vamos a crear</li>"
                        + "<li>☐ Primer commit hecho</li>"
                        + "</ul>"
                        + "<p>Ahora sí, vamos a crear el primer microservicio: <b>Eureka Server</b>. 🚀</p>")
                ));

    }
}
