package com.dojo.frontend.controller.guia;

import java.util.*;
import static com.dojo.frontend.controller.guia.GuiaHelper.*;

public class GuiaCapitulo04 {

    public static Map<String, Object> getPaso() {
        return crearPaso(
            4, "Auth Service (Seguridad + JWT)", "bi-shield-lock",
                "Este es el servicio más importante y complejo de la arquitectura. Gestiona el registro de usuarios, "
                + "login y generación de tokens JWT. Cuando un usuario se identifica correctamente, recibe un token "
                + "que debe enviar en cada petición posterior. El Gateway valida ese token sin consultar la base de datos.",
                List.of(

                    section("1. ¿Qué es JWT y cómo funciona?",
                        "<p><b>JWT (JSON Web Token)</b> es un estándar para transmitir información de forma segura entre dos partes. "
                        + "Es un string codificado que contiene tres partes separadas por puntos:</p>"
                        + "<pre><code>eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiZXJ0byJ9.firma_aqui\n"
                        + "│                      │                      │\n"
                        + "└─ Header (algoritmo)  └─ Payload (datos)    └─ Firma (verificación)</code></pre>"
                        + "<p><b>Flujo completo:</b></p>"
                        + "<ol>"
                        + "<li>El usuario envía <code>username + password</code> a <code>/auth/login</code></li>"
                        + "<li>Auth Service busca el usuario en la base de datos</li>"
                        + "<li>Compara la contraseña con BCrypt (hash seguro)</li>"
                        + "<li>Si es correcta, genera un <b>JWT firmado</b> con una clave secreta</li>"
                        + "<li>Devuelve el token al cliente</li>"
                        + "<li>El cliente guarda el token y lo envía en el header <code>Authorization: Bearer &lt;token&gt;</code></li>"
                        + "<li>El Gateway valida el token <b>sin llamar a Auth Service</b> — solo necesita la misma clave secreta</li>"
                        + "</ol>"
                        + "<p>💡 <b>¿Por qué no sesiones?</b> En microservicios, cada servicio es independiente. "
                        + "Las sesiones requieren un servidor centralizado o compartir estado. "
                        + "JWT es <b>stateless</b> — toda la info necesaria va dentro del token.</p>"),

                    section("2. Crear el proyecto auth-service",
                        "<p><b>Spring Initializr</b> (IntelliJ o web) con estas dependencias:</p>"
                        + "<table class='table table-sm table-dark'>"
                        + "<thead><tr><th>Dependencia</th><th>Para qué</th></tr></thead>"
                        + "<tbody>"
                        + "<tr><td><b>Spring Web</b></td><td>API REST (controllers, endpoints HTTP)</td></tr>"
                        + "<tr><td><b>Spring Security</b></td><td>Proteger endpoints, encriptar contraseñas</td></tr>"
                        + "<tr><td><b>Spring Data JPA</b></td><td>Acceso a base de datos con entidades y repositorios</td></tr>"
                        + "<tr><td><b>H2 Database</b></td><td>Base de datos en memoria para desarrollo</td></tr>"
                        + "<tr><td><b>Validation</b></td><td>Validar datos de entrada (@NotBlank, @Email, @Size)</td></tr>"
                        + "<tr><td><b>Eureka Discovery Client</b></td><td>Registrarse en Eureka</td></tr>"
                        + "</tbody></table>"
                        + "<p>⚠️ <b>JJWT no está en Initializr</b> — hay que añadirla manualmente al pom.xml. "
                        + "Es la librería que genera y valida los tokens JWT.</p>"),

                    section("3. El pom.xml completo",
                        "<p><b>Ruta</b>: <code>auth-service/pom.xml</code></p>"
                        + "<pre><code>&lt;?xml version=\"1.0\" encoding=\"UTF-8\"?&gt;\n"
                        + "&lt;project ...&gt;\n"
                        + "    &lt;modelVersion&gt;4.0.0&lt;/modelVersion&gt;\n"
                        + "\n"
                        + "    &lt;parent&gt;\n"
                        + "        &lt;groupId&gt;org.springframework.boot&lt;/groupId&gt;\n"
                        + "        &lt;artifactId&gt;spring-boot-starter-parent&lt;/artifactId&gt;\n"
                        + "        &lt;version&gt;3.2.0&lt;/version&gt;\n"
                        + "        &lt;relativePath/&gt;\n"
                        + "    &lt;/parent&gt;\n"
                        + "\n"
                        + "    &lt;groupId&gt;com.dojo&lt;/groupId&gt;\n"
                        + "    &lt;artifactId&gt;auth-service&lt;/artifactId&gt;\n"
                        + "    &lt;version&gt;0.0.1-SNAPSHOT&lt;/version&gt;\n"
                        + "    &lt;name&gt;auth-service&lt;/name&gt;\n"
                        + "    &lt;description&gt;JWT Authentication Service - Spring Boot Dojo&lt;/description&gt;\n"
                        + "\n"
                        + "    &lt;properties&gt;\n"
                        + "        &lt;java.version&gt;17&lt;/java.version&gt;\n"
                        + "        &lt;spring-cloud.version&gt;2023.0.0&lt;/spring-cloud.version&gt;\n"
                        + "        &lt;jjwt.version&gt;0.12.3&lt;/jjwt.version&gt;\n"
                        + "    &lt;/properties&gt;\n"
                        + "\n"
                        + "    &lt;dependencies&gt;\n"
                        + "        &lt;!-- API REST --&gt;\n"
                        + "        &lt;dependency&gt;\n"
                        + "            &lt;groupId&gt;org.springframework.boot&lt;/groupId&gt;\n"
                        + "            &lt;artifactId&gt;spring-boot-starter-web&lt;/artifactId&gt;\n"
                        + "        &lt;/dependency&gt;\n"
                        + "\n"
                        + "        &lt;!-- Seguridad --&gt;\n"
                        + "        &lt;dependency&gt;\n"
                        + "            &lt;groupId&gt;org.springframework.boot&lt;/groupId&gt;\n"
                        + "            &lt;artifactId&gt;spring-boot-starter-security&lt;/artifactId&gt;\n"
                        + "        &lt;/dependency&gt;\n"
                        + "\n"
                        + "        &lt;!-- Base de datos --&gt;\n"
                        + "        &lt;dependency&gt;\n"
                        + "            &lt;groupId&gt;org.springframework.boot&lt;/groupId&gt;\n"
                        + "            &lt;artifactId&gt;spring-boot-starter-data-jpa&lt;/artifactId&gt;\n"
                        + "        &lt;/dependency&gt;\n"
                        + "\n"
                        + "        &lt;!-- Validación --&gt;\n"
                        + "        &lt;dependency&gt;\n"
                        + "            &lt;groupId&gt;org.springframework.boot&lt;/groupId&gt;\n"
                        + "            &lt;artifactId&gt;spring-boot-starter-validation&lt;/artifactId&gt;\n"
                        + "        &lt;/dependency&gt;\n"
                        + "\n"
                        + "        &lt;!-- H2: BD en memoria para desarrollo --&gt;\n"
                        + "        &lt;dependency&gt;\n"
                        + "            &lt;groupId&gt;com.h2database&lt;/groupId&gt;\n"
                        + "            &lt;artifactId&gt;h2&lt;/artifactId&gt;\n"
                        + "            &lt;scope&gt;runtime&lt;/scope&gt;\n"
                        + "        &lt;/dependency&gt;\n"
                        + "\n"
                        + "        &lt;!-- Eureka Client --&gt;\n"
                        + "        &lt;dependency&gt;\n"
                        + "            &lt;groupId&gt;org.springframework.cloud&lt;/groupId&gt;\n"
                        + "            &lt;artifactId&gt;spring-cloud-starter-netflix-eureka-client&lt;/artifactId&gt;\n"
                        + "        &lt;/dependency&gt;\n"
                        + "\n"
                        + "        &lt;!-- JWT (3 librerías: API + implementación + serialización) --&gt;\n"
                        + "        &lt;dependency&gt;\n"
                        + "            &lt;groupId&gt;io.jsonwebtoken&lt;/groupId&gt;\n"
                        + "            &lt;artifactId&gt;jjwt-api&lt;/artifactId&gt;\n"
                        + "            &lt;version&gt;${jjwt.version}&lt;/version&gt;\n"
                        + "        &lt;/dependency&gt;\n"
                        + "        &lt;dependency&gt;\n"
                        + "            &lt;groupId&gt;io.jsonwebtoken&lt;/groupId&gt;\n"
                        + "            &lt;artifactId&gt;jjwt-impl&lt;/artifactId&gt;\n"
                        + "            &lt;version&gt;${jjwt.version}&lt;/version&gt;\n"
                        + "            &lt;scope&gt;runtime&lt;/scope&gt;\n"
                        + "        &lt;/dependency&gt;\n"
                        + "        &lt;dependency&gt;\n"
                        + "            &lt;groupId&gt;io.jsonwebtoken&lt;/groupId&gt;\n"
                        + "            &lt;artifactId&gt;jjwt-jackson&lt;/artifactId&gt;\n"
                        + "            &lt;version&gt;${jjwt.version}&lt;/version&gt;\n"
                        + "            &lt;scope&gt;runtime&lt;/scope&gt;\n"
                        + "        &lt;/dependency&gt;\n"
                        + "\n"
                        + "        &lt;!-- Testing --&gt;\n"
                        + "        &lt;dependency&gt;\n"
                        + "            &lt;groupId&gt;org.springframework.boot&lt;/groupId&gt;\n"
                        + "            &lt;artifactId&gt;spring-boot-starter-test&lt;/artifactId&gt;\n"
                        + "            &lt;scope&gt;test&lt;/scope&gt;\n"
                        + "        &lt;/dependency&gt;\n"
                        + "    &lt;/dependencies&gt;\n"
                        + "\n"
                        + "    &lt;dependencyManagement&gt;\n"
                        + "        &lt;dependencies&gt;\n"
                        + "            &lt;dependency&gt;\n"
                        + "                &lt;groupId&gt;org.springframework.cloud&lt;/groupId&gt;\n"
                        + "                &lt;artifactId&gt;spring-cloud-dependencies&lt;/artifactId&gt;\n"
                        + "                &lt;version&gt;${spring-cloud.version}&lt;/version&gt;\n"
                        + "                &lt;type&gt;pom&lt;/type&gt;\n"
                        + "                &lt;scope&gt;import&lt;/scope&gt;\n"
                        + "            &lt;/dependency&gt;\n"
                        + "        &lt;/dependencies&gt;\n"
                        + "    &lt;/dependencyManagement&gt;\n"
                        + "\n"
                        + "    &lt;build&gt;\n"
                        + "        &lt;plugins&gt;\n"
                        + "            &lt;plugin&gt;\n"
                        + "                &lt;groupId&gt;org.springframework.boot&lt;/groupId&gt;\n"
                        + "                &lt;artifactId&gt;spring-boot-maven-plugin&lt;/artifactId&gt;\n"
                        + "            &lt;/plugin&gt;\n"
                        + "        &lt;/plugins&gt;\n"
                        + "    &lt;/build&gt;\n"
                        + "&lt;/project&gt;</code></pre>"
                        + "<p>📌 <b>¿Por qué 3 dependencias de JJWT?</b></p>"
                        + "<ul>"
                        + "<li><code>jjwt-api</code> — La interfaz pública (lo que usas en tu código)</li>"
                        + "<li><code>jjwt-impl</code> — La implementación (runtime, no la usas directamente)</li>"
                        + "<li><code>jjwt-jackson</code> — Serialización JSON del token (runtime)</li>"
                        + "</ul>"
                        + "<p>La versión se define en <code>&lt;properties&gt;</code> con <code>${jjwt.version}</code> "
                        + "para no repetirla tres veces.</p>"),

                    section("4. Estructura de carpetas del auth-service",
                        "<p>Crea estos paquetes dentro de <code>src/main/java/com/dojo/auth/</code>:</p>"
                        + "<pre><code>com.dojo.auth/\n"
                        + "├── AuthServiceApplication.java  ← Clase principal\n"
                        + "├── config/\n"
                        + "│   └── SecurityConfig.java       ← Configuración de seguridad\n"
                        + "├── controller/\n"
                        + "│   └── AuthController.java       ← Endpoints REST\n"
                        + "├── dto/\n"
                        + "│   ├── LoginRequest.java          ← Datos de login\n"
                        + "│   ├── RegisterRequest.java       ← Datos de registro\n"
                        + "│   └── AuthResponse.java          ← Respuesta con token\n"
                        + "├── entity/\n"
                        + "│   └── User.java                  ← Entidad JPA (tabla users)\n"
                        + "├── repository/\n"
                        + "│   └── UserRepository.java        ← Acceso a BD\n"
                        + "└── service/\n"
                        + "    ├── AuthService.java            ← Lógica de negocio\n"
                        + "    └── JwtService.java             ← Generar/validar tokens</code></pre>"
                        + "<p>En IntelliJ: click derecho en <code>com.dojo.auth</code> → <b>New → Package</b> → escribe <code>config</code>, "
                        + "luego repite para <code>controller</code>, <code>dto</code>, <code>entity</code>, <code>repository</code>, <code>service</code>.</p>"),

                    section("5. Clase principal: AuthServiceApplication.java",
                        "<p><b>Ruta</b>: <code>auth-service/src/main/java/com/dojo/auth/AuthServiceApplication.java</code></p>"
                        + "<pre><code>package com.dojo.auth;\n"
                        + "\n"
                        + "import org.springframework.boot.SpringApplication;\n"
                        + "import org.springframework.boot.autoconfigure.SpringBootApplication;\n"
                        + "import org.springframework.cloud.client.discovery.EnableDiscoveryClient;\n"
                        + "\n"
                        + "@SpringBootApplication\n"
                        + "@EnableDiscoveryClient  // ← Se registra en Eureka al arrancar\n"
                        + "public class AuthServiceApplication {\n"
                        + "\n"
                        + "    public static void main(String[] args) {\n"
                        + "        SpringApplication.run(AuthServiceApplication.class, args);\n"
                        + "    }\n"
                        + "}</code></pre>"
                        + "<p><code>@EnableDiscoveryClient</code> le dice a Spring que este servicio se registre automáticamente en Eureka. "
                        + "Cuando arranque, verás <code>AUTH-SERVICE</code> aparecer en el dashboard de Eureka (<a href='http://localhost:8761'>localhost:8761</a>).</p>"),

                    section("6. Entidad User (entity/User.java)",
                        "<p><b>Ruta</b>: <code>auth-service/src/main/java/com/dojo/auth/entity/User.java</code></p>"
                        + "<pre><code>package com.dojo.auth.entity;\n"
                        + "\n"
                        + "import jakarta.persistence.*;\n"
                        + "\n"
                        + "@Entity\n"
                        + "@Table(name = \"users\")  // Nombre de la tabla en la BD\n"
                        + "public class User {\n"
                        + "\n"
                        + "    @Id\n"
                        + "    @GeneratedValue(strategy = GenerationType.IDENTITY)\n"
                        + "    private Long id;\n"
                        + "\n"
                        + "    @Column(nullable = false, unique = true)\n"
                        + "    private String username;\n"
                        + "\n"
                        + "    @Column(nullable = false, unique = true)\n"
                        + "    private String email;\n"
                        + "\n"
                        + "    @Column(nullable = false)\n"
                        + "    private String password;  // Se guarda encriptada con BCrypt\n"
                        + "\n"
                        + "    @Column(nullable = false)\n"
                        + "    private String role;  // \"USER\" o \"ADMIN\"\n"
                        + "\n"
                        + "    // Constructor vacío — OBLIGATORIO para JPA\n"
                        + "    public User() {}\n"
                        + "\n"
                        + "    public User(String username, String email, String password, String role) {\n"
                        + "        this.username = username;\n"
                        + "        this.email = email;\n"
                        + "        this.password = password;\n"
                        + "        this.role = role;\n"
                        + "    }\n"
                        + "\n"
                        + "    // Getters y setters\n"
                        + "    public Long getId() { return id; }\n"
                        + "    public void setId(Long id) { this.id = id; }\n"
                        + "    public String getUsername() { return username; }\n"
                        + "    public void setUsername(String username) { this.username = username; }\n"
                        + "    public String getEmail() { return email; }\n"
                        + "    public void setEmail(String email) { this.email = email; }\n"
                        + "    public String getPassword() { return password; }\n"
                        + "    public void setPassword(String password) { this.password = password; }\n"
                        + "    public String getRole() { return role; }\n"
                        + "    public void setRole(String role) { this.role = role; }\n"
                        + "}</code></pre>"
                        + "<p><b>Anotaciones clave:</b></p>"
                        + "<ul>"
                        + "<li><code>@Entity</code> — Marca esta clase como una tabla de BD. JPA crea la tabla automáticamente</li>"
                        + "<li><code>@Table(name = \"users\")</code> — Nombre de la tabla. Sin esto, usaría \"User\" que es palabra reservada en algunos SQL</li>"
                        + "<li><code>@Id + @GeneratedValue(IDENTITY)</code> — Clave primaria auto-incremental</li>"
                        + "<li><code>@Column(unique = true)</code> — No puede haber dos usuarios con el mismo username o email</li>"
                        + "<li><code>Constructor vacío</code> — JPA lo necesita para crear instancias por reflexión</li>"
                        + "</ul>"),

                    section("7. DTOs (dto/)",
                        "<p>Los DTOs (Data Transfer Objects) son clases simples que representan los datos que viajan por la API. "
                        + "Nunca expones la entidad directamente — podrías filtrar el hash del password sin querer.</p>"
                        + "<p><b>LoginRequest.java</b>:</p>"
                        + "<pre><code>package com.dojo.auth.dto;\n"
                        + "\n"
                        + "import jakarta.validation.constraints.NotBlank;\n"
                        + "\n"
                        + "public class LoginRequest {\n"
                        + "\n"
                        + "    @NotBlank  // No puede estar vacío ni ser solo espacios\n"
                        + "    private String username;\n"
                        + "\n"
                        + "    @NotBlank\n"
                        + "    private String password;\n"
                        + "\n"
                        + "    public String getUsername() { return username; }\n"
                        + "    public void setUsername(String username) { this.username = username; }\n"
                        + "    public String getPassword() { return password; }\n"
                        + "    public void setPassword(String password) { this.password = password; }\n"
                        + "}</code></pre>"
                        + "<p><b>RegisterRequest.java</b>:</p>"
                        + "<pre><code>package com.dojo.auth.dto;\n"
                        + "\n"
                        + "import jakarta.validation.constraints.Email;\n"
                        + "import jakarta.validation.constraints.NotBlank;\n"
                        + "import jakarta.validation.constraints.Size;\n"
                        + "\n"
                        + "public class RegisterRequest {\n"
                        + "\n"
                        + "    @NotBlank\n"
                        + "    @Size(min = 3, max = 50)  // Mínimo 3 caracteres\n"
                        + "    private String username;\n"
                        + "\n"
                        + "    @NotBlank\n"
                        + "    @Email  // Valida formato email\n"
                        + "    private String email;\n"
                        + "\n"
                        + "    @NotBlank\n"
                        + "    @Size(min = 6, max = 100)  // Mínimo 6 caracteres\n"
                        + "    private String password;\n"
                        + "\n"
                        + "    public String getUsername() { return username; }\n"
                        + "    public void setUsername(String username) { this.username = username; }\n"
                        + "    public String getEmail() { return email; }\n"
                        + "    public void setEmail(String email) { this.email = email; }\n"
                        + "    public String getPassword() { return password; }\n"
                        + "    public void setPassword(String password) { this.password = password; }\n"
                        + "}</code></pre>"
                        + "<p><b>AuthResponse.java</b>:</p>"
                        + "<pre><code>package com.dojo.auth.dto;\n"
                        + "\n"
                        + "public class AuthResponse {\n"
                        + "\n"
                        + "    private String token;     // El JWT\n"
                        + "    private String username;  // Nombre del usuario\n"
                        + "    private String role;      // \"USER\" o \"ADMIN\"\n"
                        + "\n"
                        + "    public AuthResponse(String token, String username, String role) {\n"
                        + "        this.token = token;\n"
                        + "        this.username = username;\n"
                        + "        this.role = role;\n"
                        + "    }\n"
                        + "\n"
                        + "    public String getToken() { return token; }\n"
                        + "    public void setToken(String token) { this.token = token; }\n"
                        + "    public String getUsername() { return username; }\n"
                        + "    public void setUsername(String username) { this.username = username; }\n"
                        + "    public String getRole() { return role; }\n"
                        + "    public void setRole(String role) { this.role = role; }\n"
                        + "}</code></pre>"
                        + "<p>📌 Las anotaciones <code>@NotBlank</code>, <code>@Email</code>, <code>@Size</code> son de "
                        + "<b>Bean Validation</b> (dependencia <code>spring-boot-starter-validation</code>). "
                        + "Se activan cuando usas <code>@Valid</code> en el controller.</p>"),

                    section("8. Repository (repository/UserRepository.java)",
                        "<p><b>Ruta</b>: <code>auth-service/src/main/java/com/dojo/auth/repository/UserRepository.java</code></p>"
                        + "<pre><code>package com.dojo.auth.repository;\n"
                        + "\n"
                        + "import com.dojo.auth.entity.User;\n"
                        + "import org.springframework.data.jpa.repository.JpaRepository;\n"
                        + "\n"
                        + "import java.util.Optional;\n"
                        + "\n"
                        + "public interface UserRepository extends JpaRepository&lt;User, Long&gt; {\n"
                        + "\n"
                        + "    Optional&lt;User&gt; findByUsername(String username);\n"
                        + "\n"
                        + "    boolean existsByUsername(String username);\n"
                        + "\n"
                        + "    boolean existsByEmail(String email);\n"
                        + "}</code></pre>"
                        + "<p><b>¿Cómo funciona esto?</b> Spring Data JPA es MAGIA:</p>"
                        + "<ul>"
                        + "<li>Solo defines una <b>interface</b> (no una clase) que extiende <code>JpaRepository</code></li>"
                        + "<li>Spring genera la implementación automáticamente al arrancar</li>"
                        + "<li>Ya tienes gratis: <code>save()</code>, <code>findById()</code>, <code>findAll()</code>, <code>delete()</code>, etc.</li>"
                        + "<li>Los métodos con nombre especial generan queries: <code>findByUsername</code> → <code>SELECT * FROM users WHERE username = ?</code></li>"
                        + "<li><code>existsByEmail</code> → <code>SELECT COUNT(*) > 0 FROM users WHERE email = ?</code></li>"
                        + "</ul>"
                        + "<p>No escribes SQL. Spring lo deduce del nombre del método. Esto se llama <b>Derived Query Methods</b>.</p>"),

                    section("9. JwtService (service/JwtService.java)",
                        "<p><b>Ruta</b>: <code>auth-service/src/main/java/com/dojo/auth/service/JwtService.java</code></p>"
                        + "<pre><code>package com.dojo.auth.service;\n"
                        + "\n"
                        + "import io.jsonwebtoken.Claims;\n"
                        + "import io.jsonwebtoken.Jwts;\n"
                        + "import io.jsonwebtoken.security.Keys;\n"
                        + "import org.springframework.beans.factory.annotation.Value;\n"
                        + "import org.springframework.stereotype.Service;\n"
                        + "\n"
                        + "import javax.crypto.SecretKey;\n"
                        + "import java.nio.charset.StandardCharsets;\n"
                        + "import java.util.Date;\n"
                        + "\n"
                        + "@Service\n"
                        + "public class JwtService {\n"
                        + "\n"
                        + "    private final SecretKey key;\n"
                        + "    private final long expiration;\n"
                        + "\n"
                        + "    public JwtService(@Value(\"${jwt.secret}\") String secret,\n"
                        + "                     @Value(\"${jwt.expiration}\") long expiration) {\n"
                        + "        this.key = Keys.hmacShaKeyFor(secret.getBytes(StandardCharsets.UTF_8));\n"
                        + "        this.expiration = expiration;\n"
                        + "    }\n"
                        + "\n"
                        + "    public String generateToken(String username, String role) {\n"
                        + "        return Jwts.builder()\n"
                        + "                .subject(username)           // Quién es\n"
                        + "                .claim(\"role\", role)        // Rol del usuario\n"
                        + "                .issuedAt(new Date())        // Cuándo se creó\n"
                        + "                .expiration(new Date(        // Cuándo expira\n"
                        + "                    System.currentTimeMillis() + expiration))\n"
                        + "                .signWith(key)               // Firma con clave secreta\n"
                        + "                .compact();                  // Genera el string\n"
                        + "    }\n"
                        + "\n"
                        + "    public Claims extractClaims(String token) {\n"
                        + "        return Jwts.parser()\n"
                        + "                .verifyWith(key)             // Verifica la firma\n"
                        + "                .build()\n"
                        + "                .parseSignedClaims(token)\n"
                        + "                .getPayload();\n"
                        + "    }\n"
                        + "\n"
                        + "    public String extractUsername(String token) {\n"
                        + "        return extractClaims(token).getSubject();\n"
                        + "    }\n"
                        + "\n"
                        + "    public boolean isTokenValid(String token) {\n"
                        + "        try {\n"
                        + "            extractClaims(token);\n"
                        + "            return true;\n"
                        + "        } catch (Exception e) {\n"
                        + "            return false;  // Token expirado, firma inválida, etc.\n"
                        + "        }\n"
                        + "    }\n"
                        + "}</code></pre>"
                        + "<p><b>Puntos clave:</b></p>"
                        + "<ul>"
                        + "<li><code>@Value(\"${jwt.secret}\")</code> — Lee la clave secreta del <code>application.yml</code></li>"
                        + "<li><code>Keys.hmacShaKeyFor()</code> — Convierte el string en una clave criptográfica. "
                        + "La clave debe tener al menos 256 bits (32 caracteres) para HMAC-SHA256</li>"
                        + "<li><code>generateToken()</code> — Crea el JWT con el username, rol, fecha de creación y expiración</li>"
                        + "<li><code>isTokenValid()</code> — Intenta parsear el token. Si falla (expirado, firma incorrecta), devuelve false</li>"
                        + "</ul>"),

                    section("10. AuthService (service/AuthService.java)",
                        "<p><b>Ruta</b>: <code>auth-service/src/main/java/com/dojo/auth/service/AuthService.java</code></p>"
                        + "<pre><code>package com.dojo.auth.service;\n"
                        + "\n"
                        + "import com.dojo.auth.dto.AuthResponse;\n"
                        + "import com.dojo.auth.dto.LoginRequest;\n"
                        + "import com.dojo.auth.dto.RegisterRequest;\n"
                        + "import com.dojo.auth.entity.User;\n"
                        + "import com.dojo.auth.repository.UserRepository;\n"
                        + "import org.springframework.security.crypto.password.PasswordEncoder;\n"
                        + "import org.springframework.stereotype.Service;\n"
                        + "\n"
                        + "@Service\n"
                        + "public class AuthService {\n"
                        + "\n"
                        + "    private final UserRepository userRepository;\n"
                        + "    private final PasswordEncoder passwordEncoder;\n"
                        + "    private final JwtService jwtService;\n"
                        + "\n"
                        + "    // Inyección por constructor (las 3 dependencias)\n"
                        + "    public AuthService(UserRepository userRepository,\n"
                        + "                      PasswordEncoder passwordEncoder,\n"
                        + "                      JwtService jwtService) {\n"
                        + "        this.userRepository = userRepository;\n"
                        + "        this.passwordEncoder = passwordEncoder;\n"
                        + "        this.jwtService = jwtService;\n"
                        + "    }\n"
                        + "\n"
                        + "    public AuthResponse register(RegisterRequest request) {\n"
                        + "        // Validar que no exista el usuario\n"
                        + "        if (userRepository.existsByUsername(request.getUsername())) {\n"
                        + "            throw new IllegalArgumentException(\"Username already exists\");\n"
                        + "        }\n"
                        + "        if (userRepository.existsByEmail(request.getEmail())) {\n"
                        + "            throw new IllegalArgumentException(\"Email already exists\");\n"
                        + "        }\n"
                        + "\n"
                        + "        // Crear usuario con contraseña encriptada\n"
                        + "        User user = new User(\n"
                        + "                request.getUsername(),\n"
                        + "                request.getEmail(),\n"
                        + "                passwordEncoder.encode(request.getPassword()),  // ← BCrypt\n"
                        + "                \"USER\"\n"
                        + "        );\n"
                        + "        userRepository.save(user);\n"
                        + "\n"
                        + "        // Generar token y responder\n"
                        + "        String token = jwtService.generateToken(user.getUsername(), user.getRole());\n"
                        + "        return new AuthResponse(token, user.getUsername(), user.getRole());\n"
                        + "    }\n"
                        + "\n"
                        + "    public AuthResponse login(LoginRequest request) {\n"
                        + "        // Buscar usuario\n"
                        + "        User user = userRepository.findByUsername(request.getUsername())\n"
                        + "                .orElseThrow(() -> new IllegalArgumentException(\"Invalid credentials\"));\n"
                        + "\n"
                        + "        // Verificar contraseña\n"
                        + "        if (!passwordEncoder.matches(request.getPassword(), user.getPassword())) {\n"
                        + "            throw new IllegalArgumentException(\"Invalid credentials\");\n"
                        + "        }\n"
                        + "\n"
                        + "        String token = jwtService.generateToken(user.getUsername(), user.getRole());\n"
                        + "        return new AuthResponse(token, user.getUsername(), user.getRole());\n"
                        + "    }\n"
                        + "\n"
                        + "    public boolean validateToken(String token) {\n"
                        + "        return jwtService.isTokenValid(token);\n"
                        + "    }\n"
                        + "}</code></pre>"
                        + "<p>📌 <b>¿Qué hace <code>passwordEncoder.encode()</code>?</b></p>"
                        + "<p>BCrypt genera un hash irreversible de la contraseña. Si la contraseña es \"1234\", "
                        + "se guarda algo como <code>$2a$10$N9qo8uLOickgx2ZMRZoMye...</code>. "
                        + "Nunca se guarda la contraseña en texto plano. "
                        + "<code>passwordEncoder.matches()</code> compara la contraseña introducida contra el hash guardado.</p>"),

                    section("11. AuthController (controller/AuthController.java)",
                        "<p><b>Ruta</b>: <code>auth-service/src/main/java/com/dojo/auth/controller/AuthController.java</code></p>"
                        + "<pre><code>package com.dojo.auth.controller;\n"
                        + "\n"
                        + "import com.dojo.auth.dto.AuthResponse;\n"
                        + "import com.dojo.auth.dto.LoginRequest;\n"
                        + "import com.dojo.auth.dto.RegisterRequest;\n"
                        + "import com.dojo.auth.service.AuthService;\n"
                        + "import jakarta.validation.Valid;\n"
                        + "import org.springframework.http.HttpStatus;\n"
                        + "import org.springframework.http.ResponseEntity;\n"
                        + "import org.springframework.web.bind.annotation.*;\n"
                        + "\n"
                        + "import java.util.Map;\n"
                        + "\n"
                        + "@RestController\n"
                        + "@RequestMapping(\"/auth\")\n"
                        + "public class AuthController {\n"
                        + "\n"
                        + "    private final AuthService authService;\n"
                        + "\n"
                        + "    public AuthController(AuthService authService) {\n"
                        + "        this.authService = authService;\n"
                        + "    }\n"
                        + "\n"
                        + "    @PostMapping(\"/register\")\n"
                        + "    public ResponseEntity&lt;AuthResponse&gt; register(\n"
                        + "            @Valid @RequestBody RegisterRequest request) {\n"
                        + "        return ResponseEntity.status(HttpStatus.CREATED)\n"
                        + "                .body(authService.register(request));\n"
                        + "    }\n"
                        + "\n"
                        + "    @PostMapping(\"/login\")\n"
                        + "    public ResponseEntity&lt;AuthResponse&gt; login(\n"
                        + "            @Valid @RequestBody LoginRequest request) {\n"
                        + "        return ResponseEntity.ok(authService.login(request));\n"
                        + "    }\n"
                        + "\n"
                        + "    @GetMapping(\"/validate\")\n"
                        + "    public ResponseEntity&lt;Map&lt;String, Boolean&gt;&gt; validateToken(\n"
                        + "            @RequestParam String token) {\n"
                        + "        boolean valid = authService.validateToken(token);\n"
                        + "        return ResponseEntity.ok(Map.of(\"valid\", valid));\n"
                        + "    }\n"
                        + "\n"
                        + "    @ExceptionHandler(IllegalArgumentException.class)\n"
                        + "    public ResponseEntity&lt;Map&lt;String, String&gt;&gt; handleIllegalArgument(\n"
                        + "            IllegalArgumentException e) {\n"
                        + "        return ResponseEntity.badRequest()\n"
                        + "                .body(Map.of(\"error\", e.getMessage()));\n"
                        + "    }\n"
                        + "}</code></pre>"
                        + "<p><b>Anotaciones clave:</b></p>"
                        + "<ul>"
                        + "<li><code>@Valid</code> — Activa las validaciones de los DTOs (@NotBlank, @Email, @Size). Sin @Valid, las anotaciones no hacen nada</li>"
                        + "<li><code>@RequestBody</code> — Lee el JSON del cuerpo de la petición y lo convierte en el DTO</li>"
                        + "<li><code>ResponseEntity.status(CREATED)</code> — Devuelve código 201 (Created) en vez de 200</li>"
                        + "<li><code>@ExceptionHandler</code> — Captura excepciones de este controller y devuelve un error limpio en JSON</li>"
                        + "</ul>"),

                    section("12. SecurityConfig (config/SecurityConfig.java)",
                        "<p><b>Ruta</b>: <code>auth-service/src/main/java/com/dojo/auth/config/SecurityConfig.java</code></p>"
                        + "<pre><code>package com.dojo.auth.config;\n"
                        + "\n"
                        + "import org.springframework.context.annotation.Bean;\n"
                        + "import org.springframework.context.annotation.Configuration;\n"
                        + "import org.springframework.security.config.annotation.web.builders.HttpSecurity;\n"
                        + "import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;\n"
                        + "import org.springframework.security.config.http.SessionCreationPolicy;\n"
                        + "import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;\n"
                        + "import org.springframework.security.crypto.password.PasswordEncoder;\n"
                        + "import org.springframework.security.web.SecurityFilterChain;\n"
                        + "\n"
                        + "@Configuration\n"
                        + "@EnableWebSecurity\n"
                        + "public class SecurityConfig {\n"
                        + "\n"
                        + "    @Bean\n"
                        + "    public SecurityFilterChain securityFilterChain(HttpSecurity http)\n"
                        + "            throws Exception {\n"
                        + "        http\n"
                        + "            .csrf(csrf -> csrf.disable())              // 1\n"
                        + "            .sessionManagement(session -> session\n"
                        + "                .sessionCreationPolicy(\n"
                        + "                    SessionCreationPolicy.STATELESS))  // 2\n"
                        + "            .authorizeHttpRequests(auth -> auth\n"
                        + "                .requestMatchers(\"/auth/register\",\n"
                        + "                    \"/auth/login\",\n"
                        + "                    \"/auth/validate\").permitAll()     // 3\n"
                        + "                .requestMatchers(\"/h2-console/**\")\n"
                        + "                    .permitAll()                       // 4\n"
                        + "                .anyRequest().authenticated())         // 5\n"
                        + "            .headers(headers -> headers\n"
                        + "                .frameOptions(frame -> frame.disable())); // 6\n"
                        + "\n"
                        + "        return http.build();\n"
                        + "    }\n"
                        + "\n"
                        + "    @Bean\n"
                        + "    public PasswordEncoder passwordEncoder() {\n"
                        + "        return new BCryptPasswordEncoder();  // 7\n"
                        + "    }\n"
                        + "}</code></pre>"
                        + "<p><b>Explicación de cada punto:</b></p>"
                        + "<ol>"
                        + "<li><b>CSRF desactivado</b> — CSRF protege contra ataques en formularios web con sesión. "
                        + "Nosotros usamos JWT (stateless), así que no necesitamos CSRF</li>"
                        + "<li><b>Stateless</b> — No crear sesiones HTTP. Cada petición se autentica por JWT</li>"
                        + "<li><b>Rutas públicas</b> — Login, registro y validación no requieren token (obvio, aún no lo tienes)</li>"
                        + "<li><b>H2 Console</b> — Permitir acceso a la consola de la BD en desarrollo</li>"
                        + "<li><b>Todo lo demás requiere auth</b> — Cualquier otra ruta necesita estar autenticado</li>"
                        + "<li><b>Frame Options desactivado</b> — La consola H2 usa iframes. Sin esto, el navegador los bloquea</li>"
                        + "<li><b>BCryptPasswordEncoder</b> — El bean que se inyecta en AuthService para encriptar contraseñas</li>"
                        + "</ol>"),

                    section("13. application.yml",
                        "<p><b>Ruta</b>: <code>auth-service/src/main/resources/application.yml</code></p>"
                        + "<pre><code>server:\n"
                        + "  port: 8081\n"
                        + "\n"
                        + "spring:\n"
                        + "  application:\n"
                        + "    name: auth-service\n"
                        + "  datasource:\n"
                        + "    url: jdbc:h2:mem:authdb       # BD en memoria\n"
                        + "    driver-class-name: org.h2.Driver\n"
                        + "    username: sa\n"
                        + "    password:                      # Sin contraseña\n"
                        + "  jpa:\n"
                        + "    hibernate:\n"
                        + "      ddl-auto: create-drop        # Crea tablas al arrancar, borra al parar\n"
                        + "    show-sql: true                  # Muestra las queries SQL en consola\n"
                        + "  h2:\n"
                        + "    console:\n"
                        + "      enabled: true                 # Consola web de H2\n"
                        + "\n"
                        + "eureka:\n"
                        + "  client:\n"
                        + "    service-url:\n"
                        + "      defaultZone: http://localhost:8761/eureka/\n"
                        + "\n"
                        + "jwt:\n"
                        + "  secret: dojo-secret-key-that-is-at-least-256-bits-long-for-hs256-algorithm-security\n"
                        + "  expiration: 86400000              # 24 horas en milisegundos</code></pre>"
                        + "<p><b>Propiedades importantes:</b></p>"
                        + "<ul>"
                        + "<li><code>jdbc:h2:mem:authdb</code> — Base de datos <b>en memoria</b>. Los datos se pierden al reiniciar. "
                        + "Para persistir: <code>jdbc:h2:file:./data/authdb</code></li>"
                        + "<li><code>ddl-auto: create-drop</code> — Hibernate crea las tablas automáticamente a partir de las entidades @Entity. "
                        + "En producción usarías <code>validate</code> + migraciones Flyway</li>"
                        + "<li><code>show-sql: true</code> — Muy útil para depurar. Ves cada query que ejecuta JPA en la consola</li>"
                        + "<li><code>jwt.secret</code> — La clave para firmar tokens. DEBE ser la misma en Auth Service y en el API Gateway. "
                        + "Mínimo 32 caracteres para HS256</li>"
                        + "<li><code>86400000</code> — 24h × 60min × 60seg × 1000ms = 86.400.000 milisegundos</li>"
                        + "</ul>"),

                    section("14. Arrancar y probar",
                        "<p>⚠️ <b>Eureka debe estar corriendo</b> antes de arrancar Auth Service.</p>"
                        + "<pre><code># Terminal 1 (si no está corriendo)\ncd eureka-server && mvn spring-boot:run\n\n# Terminal 2\ncd auth-service && mvn spring-boot:run</code></pre>"
                        + "<p>Cuando veas <code>Started AuthServiceApplication</code>, prueba con curl:</p>"
                        + "<pre><code># 1. Registrar un usuario\n"
                        + "curl -s -X POST http://localhost:8081/auth/register \\\n"
                        + "  -H 'Content-Type: application/json' \\\n"
                        + "  -d '{\"username\":\"berto\",\"email\":\"berto@test.com\",\"password\":\"123456\"}'\n"
                        + "\n"
                        + "# Respuesta:\n"
                        + "# {\"token\":\"eyJhbGci...\",\"username\":\"berto\",\"role\":\"USER\"}\n"
                        + "\n"
                        + "# 2. Login\n"
                        + "curl -s -X POST http://localhost:8081/auth/login \\\n"
                        + "  -H 'Content-Type: application/json' \\\n"
                        + "  -d '{\"username\":\"berto\",\"password\":\"123456\"}'\n"
                        + "\n"
                        + "# 3. Validar un token\n"
                        + "curl -s 'http://localhost:8081/auth/validate?token=TU_TOKEN_AQUI'</code></pre>"
                        + "<p><b>Consola H2</b>: Abre <a href='http://localhost:8081/h2-console' target='_blank'>localhost:8081/h2-console</a></p>"
                        + "<ul>"
                        + "<li>JDBC URL: <code>jdbc:h2:mem:authdb</code></li>"
                        + "<li>User: <code>sa</code> / Password: (vacío)</li>"
                        + "<li>Click Connect → Puedes ejecutar: <code>SELECT * FROM USERS;</code></li>"
                        + "</ul>"
                        + "<p>También verifica que aparece en <b>Eureka</b>: abre <a href='http://localhost:8761'>localhost:8761</a> "
                        + "y busca <code>AUTH-SERVICE</code> en la lista de instancias registradas.</p>"),

                    section("⚠️ Errores comunes",
                        "<table class='table table-sm table-dark'>"
                        + "<thead><tr><th>Error</th><th>Causa</th><th>Solución</th></tr></thead>"
                        + "<tbody>"
                        + "<tr><td><code>403 Forbidden</code> en /auth/register o /auth/login</td>"
                        + "<td>Spring Security bloquea todo por defecto</td>"
                        + "<td>Revisa que <code>SecurityConfig</code> tiene <code>.requestMatchers(\"/auth/register\", \"/auth/login\").permitAll()</code></td></tr>"
                        + "<tr><td><code>There is no PasswordEncoder mapped</code></td>"
                        + "<td>Falta el bean <code>PasswordEncoder</code></td>"
                        + "<td>Añade el <code>@Bean passwordEncoder()</code> en SecurityConfig</td></tr>"
                        + "<tr><td><code>io.jsonwebtoken.security.WeakKeyException</code></td>"
                        + "<td>La clave JWT es demasiado corta</td>"
                        + "<td>El secret debe tener al menos 32 caracteres (256 bits) para HS256</td></tr>"
                        + "<tr><td>Los datos se pierden al reiniciar</td>"
                        + "<td>H2 en memoria (<code>mem:authdb</code>) se borra al parar</td>"
                        + "<td>Normal en desarrollo. Para persistir: <code>jdbc:h2:file:./data/authdb</code></td></tr>"
                        + "<tr><td><code>H2 console: 404</code></td>"
                        + "<td>La consola H2 no está habilitada</td>"
                        + "<td>Asegúrate de tener <code>h2.console.enabled: true</code> en application.yml</td></tr>"
                        + "<tr><td>No aparece en Eureka</td>"
                        + "<td>Eureka no está arrancado o la URL es incorrecta</td>"
                        + "<td>Verifica que Eureka está en :8761 y que <code>defaultZone</code> es correcto</td></tr>"
                        + "</tbody></table>"),

                    section("💡 Conceptos para la entrevista",
                        "<ul>"
                        + "<li><b>JWT vs Sesiones</b> — JWT es stateless (info en el token), sesiones son stateful (info en el servidor). "
                        + "JWT escala mejor en microservicios</li>"
                        + "<li><b>BCrypt</b> — Algoritmo de hash con salt. Cada vez que encriptas \"1234\" genera un hash diferente. "
                        + "Es unidireccional: no puedes desencriptar, solo comparar</li>"
                        + "<li><b>@EnableWebSecurity</b> — Activa la configuración de seguridad personalizada en Spring Boot 3</li>"
                        + "<li><b>SecurityFilterChain</b> — Reemplaza al antiguo <code>WebSecurityConfigurerAdapter</code> (deprecado en Spring Security 6)</li>"
                        + "<li><b>CSRF</b> — Cross-Site Request Forgery. Se desactiva en APIs REST stateless porque no hay cookies de sesión que robar</li>"
                        + "<li><b>PasswordEncoder</b> — Nunca guardar contraseñas en texto plano. BCrypt es el estándar actual</li>"
                        + "</ul>"),

                    section("✅ Checklist antes de continuar",
                        "<ul>"
                        + "<li>☐ Proyecto <code>auth-service</code> creado con todas las dependencias</li>"
                        + "<li>☐ Todos los archivos creados: Entity, DTOs, Repository, Services, Controller, SecurityConfig</li>"
                        + "<li>☐ application.yml configurado (puerto 8081, H2, Eureka, JWT)</li>"
                        + "<li>☐ Arranca sin errores (con Eureka corriendo)</li>"
                        + "<li>☐ Registro funciona con curl → devuelve token</li>"
                        + "<li>☐ Login funciona con curl → devuelve token</li>"
                        + "<li>☐ Aparece en el dashboard de Eureka como AUTH-SERVICE</li>"
                        + "<li>☐ Puedes acceder a la consola H2 y ver la tabla USERS</li>"
                        + "<li>☐ Commit: <code>git commit -m \"Add auth-service with JWT\"</code></li>"
                        + "</ul>"
                        + "<p>¡Servicio de autenticación listo! 🔐 Ahora vamos con el <b>Content Service</b> — donde vive todo el contenido de aprendizaje. 📚</p>")
                ));

    }
}
