package com.dojo.frontend.controller.guia;

import java.util.*;
import static com.dojo.frontend.controller.guia.GuiaHelper.*;

public class GuiaCapitulo08 {

    public static Map<String, Object> getPaso() {
        return crearPaso(
            8, "Dashboard + Estudio de Flashcards", "bi-speedometer2",
                "Con el login funcionando, ahora toca la página principal: el Dashboard. Aquí el usuario ve sus estadísticas, "
                + "las tarjetas de cinturones con barras de progreso, y puede entrar a estudiar flashcards o hacer quizzes. "
                + "Es la página con más lógica del frontend — conecta con Content Service y Progress Service.",
                List.of(

                    section("1. DashboardController.java",
                        "<p><b>Ruta</b>: <code>.../controller/DashboardController.java</code></p>"
                        + "<p>Este controller hace varias llamadas al Gateway para montar la vista:</p>"
                        + "<pre><code>package com.dojo.frontend.controller;\n"
                        + "\n"
                        + "import jakarta.servlet.http.HttpSession;\n"
                        + "import org.springframework.beans.factory.annotation.Value;\n"
                        + "import org.springframework.core.ParameterizedTypeReference;\n"
                        + "import org.springframework.http.*;\n"
                        + "import org.springframework.stereotype.Controller;\n"
                        + "import org.springframework.ui.Model;\n"
                        + "import org.springframework.web.bind.annotation.GetMapping;\n"
                        + "import org.springframework.web.client.RestTemplate;\n"
                        + "import java.util.*;\n"
                        + "\n"
                        + "@Controller\n"
                        + "public class DashboardController {\n"
                        + "\n"
                        + "    private final RestTemplate restTemplate;\n"
                        + "    private final String gatewayUrl;\n"
                        + "\n"
                        + "    // Orden de cinturones\n"
                        + "    private static final String[] BELT_ORDER =\n"
                        + "        {\"BLANCO\",\"AMARILLO\",\"NARANJA\",\"VERDE\",\"MARRON\",\"NEGRO\"};\n"
                        + "\n"
                        + "    public DashboardController(RestTemplate restTemplate,\n"
                        + "            @Value(\"${gateway.url}\") String gatewayUrl) {\n"
                        + "        this.restTemplate = restTemplate;\n"
                        + "        this.gatewayUrl = gatewayUrl;\n"
                        + "    }\n"
                        + "\n"
                        + "    @GetMapping(\"/dashboard\")\n"
                        + "    public String dashboard(HttpSession session, Model model) {\n"
                        + "        String token = (String) session.getAttribute(\"token\");\n"
                        + "        if (token == null) return \"redirect:/login\";\n"
                        + "\n"
                        + "        String username = (String) session.getAttribute(\"username\");\n"
                        + "        model.addAttribute(\"username\", username);\n"
                        + "\n"
                        + "        // Definir los cinturones\n"
                        + "        String[][] belts = {\n"
                        + "            {\"BLANCO\",  \"White Belt\",  \"bg-light text-dark\"},\n"
                        + "            {\"AMARILLO\",\"Yellow Belt\", \"bg-warning text-dark\"},\n"
                        + "            {\"NARANJA\", \"Orange Belt\", \"bg-orange\"},\n"
                        + "            {\"VERDE\",   \"Green Belt\",  \"bg-success\"},\n"
                        + "            {\"MARRON\",  \"Brown Belt\",  \"bg-brown\"},\n"
                        + "            {\"NEGRO\",   \"Black Belt\",  \"bg-dark\"}\n"
                        + "        };\n"
                        + "        model.addAttribute(\"belts\", belts);\n"
                        + "\n"
                        + "        // Headers con JWT\n"
                        + "        HttpHeaders headers = new HttpHeaders();\n"
                        + "        headers.set(\"Authorization\", \"Bearer \" + token);\n"
                        + "        HttpEntity&lt;Void&gt; entity = new HttpEntity&lt;&gt;(headers);\n"
                        + "\n"
                        + "        // Fetch flashcards para cada cinturón\n"
                        + "        for (String[] belt : belts) {\n"
                        + "            try {\n"
                        + "                var response = restTemplate.exchange(\n"
                        + "                    gatewayUrl + \"/api/content/flashcards?difficulty=\"\n"
                        + "                    + belt[0], HttpMethod.GET, entity,\n"
                        + "                    new ParameterizedTypeReference\n"
                        + "                        &lt;List&lt;Map&lt;String, Object&gt;&gt;&gt;() {});\n"
                        + "                model.addAttribute(\"flashcards_\" + belt[0],\n"
                        + "                    response.getBody());\n"
                        + "            } catch (Exception e) {\n"
                        + "                model.addAttribute(\"flashcards_\" + belt[0],\n"
                        + "                    Collections.emptyList());\n"
                        + "            }\n"
                        + "        }\n"
                        + "\n"
                        + "        // Fetch progreso del usuario\n"
                        + "        // (más adelante en el capítulo de Progress Service)\n"
                        + "        // ...\n"
                        + "\n"
                        + "        return \"dashboard\";\n"
                        + "    }\n"
                        + "}</code></pre>"
                        + "<p><b>¿Qué hace?</b></p>"
                        + "<ol>"
                        + "<li>Verifica que hay sesión (token). Si no → redirige a login</li>"
                        + "<li>Define los 6 cinturones con su código, nombre y clase CSS</li>"
                        + "<li>Para cada cinturón, pide las flashcards al Gateway (con JWT en el header)</li>"
                        + "<li>Pasa todo al template con <code>model.addAttribute()</code></li>"
                        + "</ol>"
                        + "<p>📌 <code>ParameterizedTypeReference</code> — necesario cuando el tipo de respuesta es genérico "
                        + "(<code>List&lt;Map&gt;</code>). Java pierde la info genérica en runtime (type erasure), "
                        + "y esta clase la preserva.</p>"),

                    section("2. dashboard.html — Estadísticas",
                        "<p>El dashboard tiene dos zonas: <b>estadísticas arriba</b> y <b>tarjetas de cinturones abajo</b>.</p>"
                        + "<p><b>Fila de estadísticas:</b></p>"
                        + "<pre><code>&lt;!-- 4 tarjetas de stats --&gt;\n"
                        + "&lt;div class=\"row g-3 mb-4\"&gt;\n"
                        + "  &lt;div class=\"col-md-3\"&gt;\n"
                        + "    &lt;div class=\"card shadow-sm\"&gt;\n"
                        + "      &lt;div class=\"card-body text-center\"&gt;\n"
                        + "        &lt;i class=\"bi bi-fire fs-2 text-danger\"&gt;&lt;/i&gt;\n"
                        + "        &lt;h4 th:text=\"${currentStreak}\"&gt;0&lt;/h4&gt;\n"
                        + "        &lt;small class=\"text-muted\"&gt;Current Streak&lt;/small&gt;\n"
                        + "      &lt;/div&gt;\n"
                        + "    &lt;/div&gt;\n"
                        + "  &lt;/div&gt;\n"
                        + "  &lt;!-- Repetir para: Best Streak, Total Correct, Accuracy --&gt;\n"
                        + "&lt;/div&gt;</code></pre>"
                        + "<p>Cuatro tarjetas: 🔥 Racha actual, 🏆 Mejor racha, ✅ Total aciertos, 🎯 % Precisión.</p>"),

                    section("3. dashboard.html — Tarjetas de cinturones",
                        "<p>La parte más compleja del template. Usa <code>th:each</code> para iterar los 6 cinturones:</p>"
                        + "<pre><code>&lt;div th:each=\"belt : ${belts}\" class=\"col-md-4\"&gt;\n"
                        + "  &lt;div class=\"card belt-card shadow-sm\"\n"
                        + "       th:classappend=\"${!beltUnlocked} ? ' opacity-50' : ''\"&gt;\n"
                        + "\n"
                        + "    &lt;!-- Header con color del cinturón --&gt;\n"
                        + "    &lt;div class=\"card-header text-center\"\n"
                        + "         th:classappend=\"${belt[2]}\"&gt;\n"
                        + "      &lt;h5 th:text=\"${belt[1]}\"&gt;Belt Name&lt;/h5&gt;\n"
                        + "    &lt;/div&gt;\n"
                        + "\n"
                        + "    &lt;div class=\"card-body text-center\"&gt;\n"
                        + "      &lt;!-- Barra de progreso --&gt;\n"
                        + "      &lt;div class=\"progress\" style=\"height: 8px;\"&gt;\n"
                        + "        &lt;div class=\"progress-bar\"\n"
                        + "             th:style=\"'width: ' + ${beltPct} + '%'\"&gt;&lt;/div&gt;\n"
                        + "      &lt;/div&gt;\n"
                        + "\n"
                        + "      &lt;!-- Botones Study + Quiz --&gt;\n"
                        + "      &lt;div th:if=\"${beltUnlocked}\"&gt;\n"
                        + "        &lt;a th:href=\"@{/study(difficulty=${belt[0]})}\"\n"
                        + "           class=\"btn btn-outline-dark btn-sm\"&gt;\n"
                        + "          &lt;i class=\"bi bi-book\"&gt;&lt;/i&gt; Study\n"
                        + "        &lt;/a&gt;\n"
                        + "        &lt;a th:href=\"@{/quiz(difficulty=${belt[0]})}\"\n"
                        + "           class=\"btn btn-primary btn-sm\"&gt;\n"
                        + "          &lt;i class=\"bi bi-patch-question\"&gt;&lt;/i&gt; Quiz\n"
                        + "        &lt;/a&gt;\n"
                        + "      &lt;/div&gt;\n"
                        + "\n"
                        + "      &lt;!-- Bloqueado --&gt;\n"
                        + "      &lt;div th:unless=\"${beltUnlocked}\"&gt;\n"
                        + "        &lt;button class=\"btn btn-secondary btn-sm\" disabled&gt;\n"
                        + "          🔒 Master previous belt to unlock\n"
                        + "        &lt;/button&gt;\n"
                        + "      &lt;/div&gt;\n"
                        + "    &lt;/div&gt;\n"
                        + "  &lt;/div&gt;\n"
                        + "&lt;/div&gt;</code></pre>"
                        + "<p>Cada tarjeta muestra: color del cinturón, nombre, barra de progreso, "
                        + "número de flashcards, y botones de Study/Quiz. Si el cinturón está bloqueado, "
                        + "se muestra semitransparente (<code>opacity-50</code>) con un candado.</p>"),

                    section("4. StudyController.java",
                        "<p><b>Ruta</b>: <code>.../controller/StudyController.java</code></p>"
                        + "<pre><code>package com.dojo.frontend.controller;\n"
                        + "\n"
                        + "import jakarta.servlet.http.HttpSession;\n"
                        + "import org.springframework.beans.factory.annotation.Value;\n"
                        + "import org.springframework.core.ParameterizedTypeReference;\n"
                        + "import org.springframework.http.*;\n"
                        + "import org.springframework.stereotype.Controller;\n"
                        + "import org.springframework.ui.Model;\n"
                        + "import org.springframework.web.bind.annotation.*;\n"
                        + "import org.springframework.web.client.RestTemplate;\n"
                        + "import java.util.*;\n"
                        + "\n"
                        + "@Controller\n"
                        + "public class StudyController {\n"
                        + "\n"
                        + "    private final RestTemplate restTemplate;\n"
                        + "    private final String gatewayUrl;\n"
                        + "\n"
                        + "    public StudyController(RestTemplate restTemplate,\n"
                        + "            @Value(\"${gateway.url}\") String gatewayUrl) {\n"
                        + "        this.restTemplate = restTemplate;\n"
                        + "        this.gatewayUrl = gatewayUrl;\n"
                        + "    }\n"
                        + "\n"
                        + "    @GetMapping(\"/study\")\n"
                        + "    public String study(@RequestParam String difficulty,\n"
                        + "                       HttpSession session, Model model) {\n"
                        + "        String token = (String) session.getAttribute(\"token\");\n"
                        + "        if (token == null) return \"redirect:/login\";\n"
                        + "\n"
                        + "        String username = (String) session.getAttribute(\"username\");\n"
                        + "        model.addAttribute(\"username\", username);\n"
                        + "        model.addAttribute(\"difficulty\", difficulty);\n"
                        + "\n"
                        + "        HttpHeaders headers = new HttpHeaders();\n"
                        + "        headers.set(\"Authorization\", \"Bearer \" + token);\n"
                        + "        HttpEntity&lt;Void&gt; entity = new HttpEntity&lt;&gt;(headers);\n"
                        + "\n"
                        + "        try {\n"
                        + "            // Pedir flashcards con repetición espaciada\n"
                        + "            var response = restTemplate.exchange(\n"
                        + "                gatewayUrl + \"/api/content/flashcards/next\"\n"
                        + "                + \"?difficulty=\" + difficulty\n"
                        + "                + \"&userId=\" + username,\n"
                        + "                HttpMethod.GET, entity,\n"
                        + "                new ParameterizedTypeReference\n"
                        + "                    &lt;List&lt;Map&lt;String, Object&gt;&gt;&gt;() {});\n"
                        + "            model.addAttribute(\"flashcards\",\n"
                        + "                response.getBody());\n"
                        + "        } catch (Exception e) {\n"
                        + "            model.addAttribute(\"flashcards\",\n"
                        + "                Collections.emptyList());\n"
                        + "        }\n"
                        + "\n"
                        + "        return \"study\";\n"
                        + "    }\n"
                        + "\n"
                        + "    @PostMapping(\"/study/answer\")\n"
                        + "    public String recordAnswer(\n"
                        + "            @RequestParam Long flashcardId,\n"
                        + "            @RequestParam String difficulty,\n"
                        + "            @RequestParam boolean correct,\n"
                        + "            HttpSession session) {\n"
                        + "        String token = (String) session.getAttribute(\"token\");\n"
                        + "        String username = (String) session.getAttribute(\"username\");\n"
                        + "        if (token == null) return \"redirect:/login\";\n"
                        + "\n"
                        + "        try {\n"
                        + "            HttpHeaders headers = new HttpHeaders();\n"
                        + "            headers.set(\"Authorization\", \"Bearer \" + token);\n"
                        + "            HttpEntity&lt;Void&gt; entity = new HttpEntity&lt;&gt;(headers);\n"
                        + "\n"
                        + "            // Registrar respuesta para repetición espaciada\n"
                        + "            restTemplate.exchange(\n"
                        + "                gatewayUrl + \"/api/content/flashcards/\"\n"
                        + "                + flashcardId + \"/answer?userId=\" + username\n"
                        + "                + \"&correct=\" + correct,\n"
                        + "                HttpMethod.POST, entity,\n"
                        + "                new ParameterizedTypeReference\n"
                        + "                    &lt;Map&lt;String, Object&gt;&gt;() {});\n"
                        + "\n"
                        + "            // Registrar en progress service\n"
                        + "            HttpHeaders postHeaders = new HttpHeaders();\n"
                        + "            postHeaders.set(\"Authorization\", \"Bearer \" + token);\n"
                        + "            postHeaders.setContentType(MediaType.APPLICATION_JSON);\n"
                        + "            HttpEntity&lt;Map&lt;String, Object&gt;&gt; progressEntity =\n"
                        + "                new HttpEntity&lt;&gt;(Map.of(\n"
                        + "                    \"username\", username,\n"
                        + "                    \"beltLevel\", difficulty,\n"
                        + "                    \"correct\", correct), postHeaders);\n"
                        + "            restTemplate.postForEntity(\n"
                        + "                gatewayUrl + \"/api/progress/record\",\n"
                        + "                progressEntity, Object.class);\n"
                        + "        } catch (Exception ignored) {\n"
                        + "            // Best effort\n"
                        + "        }\n"
                        + "\n"
                        + "        return \"redirect:/study?difficulty=\" + difficulty;\n"
                        + "    }\n"
                        + "}</code></pre>"
                        + "<p>El StudyController hace dos cosas:</p>"
                        + "<ul>"
                        + "<li><b>GET /study</b> — Pide flashcards priorizadas (las que más fallas primero)</li>"
                        + "<li><b>POST /study/answer</b> — Cuando pulsas \"Lo sabía\" o \"No lo sabía\", registra la respuesta "
                        + "en dos sitios: content-service (para repetición espaciada) y progress-service (para racha/cinturones)</li>"
                        + "</ul>"),

                    section("5. study.html — Modo estudio",
                        "<p>Muestra las flashcards como tarjetas con la respuesta oculta. Click para revelar:</p>"
                        + "<pre><code>&lt;div th:each=\"card, iter : ${flashcards}\" class=\"col-12\"&gt;\n"
                        + "  &lt;div class=\"card flashcard shadow-sm\"&gt;\n"
                        + "    &lt;div class=\"card-body\"&gt;\n"
                        + "      &lt;!-- Pregunta visible --&gt;\n"
                        + "      &lt;h5 th:text=\"${card['question']}\"&gt;Question&lt;/h5&gt;\n"
                        + "\n"
                        + "      &lt;!-- Respuesta oculta --&gt;\n"
                        + "      &lt;div th:id=\"'answer-' + ${iter.index}\"\n"
                        + "           style=\"display: none;\"&gt;\n"
                        + "        &lt;p class=\"text-success\"\n"
                        + "           th:text=\"${card['answer']}\"&gt;Answer&lt;/p&gt;\n"
                        + "\n"
                        + "        &lt;!-- Botones de feedback --&gt;\n"
                        + "        &lt;form method=\"post\" action=\"/study/answer\"&gt;\n"
                        + "          &lt;input type=\"hidden\" name=\"flashcardId\"\n"
                        + "                 th:value=\"${card['id']}\"/&gt;\n"
                        + "          &lt;input type=\"hidden\" name=\"difficulty\"\n"
                        + "                 th:value=\"${difficulty}\"/&gt;\n"
                        + "          &lt;input type=\"hidden\" name=\"correct\" value=\"true\"/&gt;\n"
                        + "          &lt;button class=\"btn btn-success btn-sm\"&gt;\n"
                        + "            ✅ Lo sabía&lt;/button&gt;\n"
                        + "        &lt;/form&gt;\n"
                        + "        &lt;form method=\"post\" action=\"/study/answer\"&gt;\n"
                        + "          &lt;!-- mismo pero correct=false --&gt;\n"
                        + "          &lt;button class=\"btn btn-danger btn-sm\"&gt;\n"
                        + "            ❌ No lo sabía&lt;/button&gt;\n"
                        + "        &lt;/form&gt;\n"
                        + "      &lt;/div&gt;\n"
                        + "\n"
                        + "      &lt;!-- Botón para mostrar/ocultar --&gt;\n"
                        + "      &lt;button onclick=\"toggleAnswer(index)\"&gt;\n"
                        + "        Show Answer\n"
                        + "      &lt;/button&gt;\n"
                        + "    &lt;/div&gt;\n"
                        + "  &lt;/div&gt;\n"
                        + "&lt;/div&gt;\n"
                        + "\n"
                        + "&lt;script&gt;\n"
                        + "function toggleAnswer(index) {\n"
                        + "    var el = document.getElementById('answer-' + index);\n"
                        + "    el.style.display =\n"
                        + "        el.style.display === 'none' ? 'block' : 'none';\n"
                        + "}\n"
                        + "&lt;/script&gt;</code></pre>"
                        + "<p><b>Flujo del usuario:</b></p>"
                        + "<ol>"
                        + "<li>Ve la pregunta → piensa la respuesta</li>"
                        + "<li>Click \"Show Answer\" → ve la respuesta</li>"
                        + "<li>Click \"Lo sabía\" o \"No lo sabía\" → se registra y recarga con la siguiente flashcard prioritaria</li>"
                        + "</ol>"
                        + "<p>📌 <code>th:each=\"card, iter\"</code> — <code>iter</code> es el iterador de Thymeleaf. "
                        + "Tiene <code>iter.index</code> (0-based), <code>iter.count</code> (1-based), etc.</p>"),

                    section("6. JavaScript mínimo",
                        "<p>El estudio usa una función JavaScript muy sencilla para mostrar/ocultar respuestas:</p>"
                        + "<pre><code>function toggleAnswer(index) {\n"
                        + "    var answerEl = document.getElementById('answer-' + index);\n"
                        + "    var btn = answerEl.parentElement.querySelector('button');\n"
                        + "    if (answerEl.style.display === 'none') {\n"
                        + "        answerEl.style.display = 'block';\n"
                        + "        btn.innerHTML = '&lt;i class=\"bi bi-eye-slash\"&gt;&lt;/i&gt; Hide Answer';\n"
                        + "    } else {\n"
                        + "        answerEl.style.display = 'none';\n"
                        + "        btn.innerHTML = '&lt;i class=\"bi bi-eye\"&gt;&lt;/i&gt; Show Answer';\n"
                        + "    }\n"
                        + "}</code></pre>"
                        + "<p>No necesitas React, Vue ni Angular. JavaScript vanilla para interacciones simples + "
                        + "formularios HTML para las acciones del servidor. Simple y efectivo.</p>"),

                    section("⚠️ Errores comunes",
                        "<table class='table table-sm table-dark'>"
                        + "<thead><tr><th>Error</th><th>Causa</th><th>Solución</th></tr></thead>"
                        + "<tbody>"
                        + "<tr><td>Dashboard vacío (sin cinturones)</td>"
                        + "<td>Content Service no está corriendo o no hay datos</td>"
                        + "<td>Arranca content-service y verifica que el DataSeeder carga datos</td></tr>"
                        + "<tr><td>Stats siempre en 0</td>"
                        + "<td>Progress Service no está arrancado (lo crearemos en un capítulo posterior)</td>"
                        + "<td>Normal por ahora. Los stats funcionarán cuando añadamos progress-service</td></tr>"
                        + "<tr><td><code>401 Unauthorized</code> al cargar flashcards</td>"
                        + "<td>Token expirado o sesión perdida</td>"
                        + "<td>Haz logout y login de nuevo. El token expira a las 24h</td></tr>"
                        + "<tr><td>\"Lo sabía\" / \"No lo sabía\" no hace nada</td>"
                        + "<td>Progress Service o endpoint de answer no disponible</td>"
                        + "<td>El registro es best-effort (ignora errores). Funcionará cuando todo esté arrancado</td></tr>"
                        + "</tbody></table>"),

                    section("✅ Checklist antes de continuar",
                        "<ul>"
                        + "<li>☐ DashboardController creado</li>"
                        + "<li>☐ dashboard.html con stats + tarjetas de cinturones</li>"
                        + "<li>☐ StudyController creado (GET /study + POST /study/answer)</li>"
                        + "<li>☐ study.html con flashcards y botones Lo sabía / No lo sabía</li>"
                        + "<li>☐ Puedes navegar: Login → Dashboard → Study → ver flashcards</li>"
                        + "<li>☐ Commit: <code>git commit -m \"Add dashboard and study mode\"</code></li>"
                        + "</ul>"
                        + "<p>¡La app ya es usable! 🎉 Ahora vamos a añadir los <b>Quizzes</b> — preguntas tipo test con feedback. 📝</p>")
                ));

    }
}
