package com.dojo.frontend.controller.guia;

import java.util.*;
import static com.dojo.frontend.controller.guia.GuiaHelper.*;

public class GuiaCapitulo07 {

    public static Map<String, Object> getPaso() {
        return crearPaso(
            7, "Frontend Base (Thymeleaf + Bootstrap)", "bi-window-desktop",
                "Ahora le damos cara a la aplicación. El frontend usa Thymeleaf (motor de plantillas de Spring) + Bootstrap 5. "
                + "No necesitas React ni Angular — Thymeleaf renderiza HTML en el servidor y lo envía al navegador. "
                + "En este capítulo montamos la estructura base: layout compartido, login, registro y la conexión con el Gateway.",
                List.of(

                    section("1. ¿Cómo funciona el Frontend?",
                        "<p>A diferencia del resto de servicios (que son APIs REST que devuelven JSON), "
                        + "el frontend <b>devuelve HTML</b>. El flujo es:</p>"
                        + "<ol>"
                        + "<li>Usuario abre <code>http://localhost:8090</code> → ve la página de login</li>"
                        + "<li>Rellena usuario + contraseña → el frontend <b>llama al Gateway</b> (<code>:8080/api/auth/login</code>)</li>"
                        + "<li>Gateway → Auth Service → valida → devuelve JWT</li>"
                        + "<li>El frontend guarda el JWT en la <b>sesión HTTP</b> del servidor</li>"
                        + "<li>Para ver flashcards → frontend llama al Gateway <b>con el JWT en el header</b></li>"
                        + "<li>Recibe el JSON → lo renderiza en HTML con Thymeleaf → envía al navegador</li>"
                        + "</ol>"
                        + "<pre><code>Browser ←HTML→ Frontend (:8090) ←JSON→ Gateway (:8080) ←→ Services\n"
                        + "                  │\n"
                        + "         Sesión HTTP (guarda JWT)\n"
                        + "         Thymeleaf (renderiza HTML)</code></pre>"
                        + "<p>📌 El frontend es un <b>@Controller</b> (no @RestController). "
                        + "Devuelve nombres de templates HTML en vez de JSON.</p>"),

                    section("2. Crear el proyecto dojo-frontend",
                        "<p><b>Spring Initializr</b> con:</p>"
                        + "<table class='table table-sm table-dark'>"
                        + "<thead><tr><th>Dependencia</th><th>Para qué</th></tr></thead>"
                        + "<tbody>"
                        + "<tr><td><b>Spring Web</b></td><td>Controllers, MVC, servir páginas</td></tr>"
                        + "<tr><td><b>Thymeleaf</b></td><td>Motor de plantillas HTML</td></tr>"
                        + "<tr><td><b>Eureka Discovery Client</b></td><td>Registrarse en Eureka</td></tr>"
                        + "</tbody></table>"
                        + "<p>No necesita JPA, H2, ni Security — es solo un cliente web que consume APIs.</p>"),

                    section("3. pom.xml completo",
                        "<p><b>Ruta</b>: <code>dojo-frontend/pom.xml</code></p>"
                        + "<pre><code>&lt;?xml version=\"1.0\" encoding=\"UTF-8\"?&gt;\n"
                        + "&lt;project ...&gt;\n"
                        + "    &lt;parent&gt;\n"
                        + "        &lt;groupId&gt;org.springframework.boot&lt;/groupId&gt;\n"
                        + "        &lt;artifactId&gt;spring-boot-starter-parent&lt;/artifactId&gt;\n"
                        + "        &lt;version&gt;3.2.0&lt;/version&gt;\n"
                        + "        &lt;relativePath/&gt;\n"
                        + "    &lt;/parent&gt;\n"
                        + "\n"
                        + "    &lt;groupId&gt;com.dojo&lt;/groupId&gt;\n"
                        + "    &lt;artifactId&gt;dojo-frontend&lt;/artifactId&gt;\n"
                        + "    &lt;version&gt;0.0.1-SNAPSHOT&lt;/version&gt;\n"
                        + "\n"
                        + "    &lt;properties&gt;\n"
                        + "        &lt;java.version&gt;17&lt;/java.version&gt;\n"
                        + "        &lt;spring-cloud.version&gt;2023.0.0&lt;/spring-cloud.version&gt;\n"
                        + "    &lt;/properties&gt;\n"
                        + "\n"
                        + "    &lt;dependencies&gt;\n"
                        + "        &lt;dependency&gt;\n"
                        + "            &lt;groupId&gt;org.springframework.boot&lt;/groupId&gt;\n"
                        + "            &lt;artifactId&gt;spring-boot-starter-web&lt;/artifactId&gt;\n"
                        + "        &lt;/dependency&gt;\n"
                        + "        &lt;dependency&gt;\n"
                        + "            &lt;groupId&gt;org.springframework.boot&lt;/groupId&gt;\n"
                        + "            &lt;artifactId&gt;spring-boot-starter-thymeleaf&lt;/artifactId&gt;\n"
                        + "        &lt;/dependency&gt;\n"
                        + "        &lt;dependency&gt;\n"
                        + "            &lt;groupId&gt;org.springframework.cloud&lt;/groupId&gt;\n"
                        + "            &lt;artifactId&gt;spring-cloud-starter-netflix-eureka-client&lt;/artifactId&gt;\n"
                        + "        &lt;/dependency&gt;\n"
                        + "    &lt;/dependencies&gt;\n"
                        + "\n"
                        + "    &lt;!-- dependencyManagement con spring-cloud-dependencies --&gt;\n"
                        + "    &lt;!-- build con spring-boot-maven-plugin --&gt;\n"
                        + "&lt;/project&gt;</code></pre>"
                        + "<p>El más ligero de todos: web + thymeleaf + eureka. Sin base de datos, sin security.</p>"),

                    section("4. Estructura de carpetas",
                        "<pre><code>dojo-frontend/\n"
                        + "├── src/main/java/com/dojo/frontend/\n"
                        + "│   ├── DojoFrontendApplication.java\n"
                        + "│   ├── config/\n"
                        + "│   │   └── AppConfig.java          ← Bean RestTemplate\n"
                        + "│   ├── controller/\n"
                        + "│   │   └── AuthController.java      ← Login, Register, Logout\n"
                        + "│   └── dto/\n"
                        + "│       ├── LoginRequest.java\n"
                        + "│       ├── RegisterRequest.java\n"
                        + "│       └── AuthResponse.java\n"
                        + "│\n"
                        + "├── src/main/resources/\n"
                        + "│   ├── application.yml\n"
                        + "│   ├── templates/                    ← HTMLs de Thymeleaf\n"
                        + "│   │   ├── fragments/\n"
                        + "│   │   │   └── layout.html           ← Head + Navbar + Footer compartidos\n"
                        + "│   │   ├── login.html\n"
                        + "│   │   └── register.html\n"
                        + "│   └── static/css/\n"
                        + "│       └── style.css                  ← Estilos personalizados\n"
                        + "└── pom.xml</code></pre>"
                        + "<p>📌 Thymeleaf busca los templates en <code>src/main/resources/templates/</code> automáticamente. "
                        + "Los archivos estáticos (CSS, JS, imágenes) van en <code>src/main/resources/static/</code>.</p>"),

                    section("5. application.yml",
                        "<p><b>Ruta</b>: <code>dojo-frontend/src/main/resources/application.yml</code></p>"
                        + "<pre><code>server:\n"
                        + "  port: 8090\n"
                        + "\n"
                        + "spring:\n"
                        + "  application:\n"
                        + "    name: dojo-frontend\n"
                        + "  thymeleaf:\n"
                        + "    cache: false   # Desactivar caché en desarrollo\n"
                        + "                   # (cambias el HTML y se ve al refrescar)\n"
                        + "\n"
                        + "eureka:\n"
                        + "  client:\n"
                        + "    service-url:\n"
                        + "      defaultZone: http://localhost:8761/eureka/\n"
                        + "\n"
                        + "gateway:\n"
                        + "  url: http://localhost:8080   # URL del Gateway</code></pre>"
                        + "<p><code>gateway.url</code> es una propiedad personalizada nuestra. "
                        + "No es de Spring — la leemos con <code>@Value(\"${gateway.url}\")</code> en los controllers "
                        + "para saber dónde llamar al Gateway.</p>"),

                    section("6. AppConfig.java (RestTemplate)",
                        "<p><b>Ruta</b>: <code>.../config/AppConfig.java</code></p>"
                        + "<pre><code>package com.dojo.frontend.config;\n"
                        + "\n"
                        + "import org.springframework.context.annotation.Bean;\n"
                        + "import org.springframework.context.annotation.Configuration;\n"
                        + "import org.springframework.web.client.RestTemplate;\n"
                        + "\n"
                        + "@Configuration\n"
                        + "public class AppConfig {\n"
                        + "\n"
                        + "    @Bean\n"
                        + "    public RestTemplate restTemplate() {\n"
                        + "        return new RestTemplate();\n"
                        + "    }\n"
                        + "}</code></pre>"
                        + "<p><b>RestTemplate</b> es el cliente HTTP de Spring para hacer llamadas a otros servicios. "
                        + "Es como un <code>curl</code> desde Java:</p>"
                        + "<ul>"
                        + "<li><code>restTemplate.postForEntity(url, body, ResponseType.class)</code> → POST</li>"
                        + "<li><code>restTemplate.exchange(url, GET, headers, ResponseType.class)</code> → GET con headers</li>"
                        + "</ul>"
                        + "<p>Lo declaramos como <code>@Bean</code> para inyectarlo en cualquier controller.</p>"
                        + "<p>📌 En Spring Boot 3, <code>RestTemplate</code> sigue funcionando pero hay una alternativa más moderna: "
                        + "<code>WebClient</code> (reactivo). Para este proyecto, RestTemplate es más que suficiente y más fácil de entender.</p>"),

                    section("7. DTOs del frontend",
                        "<p>El frontend necesita sus propios DTOs para comunicarse con el Gateway:</p>"
                        + "<p><b>LoginRequest.java</b>:</p>"
                        + "<pre><code>package com.dojo.frontend.dto;\n"
                        + "\n"
                        + "public class LoginRequest {\n"
                        + "    private String username;\n"
                        + "    private String password;\n"
                        + "\n"
                        + "    public String getUsername() { return username; }\n"
                        + "    public void setUsername(String username) { this.username = username; }\n"
                        + "    public String getPassword() { return password; }\n"
                        + "    public void setPassword(String password) { this.password = password; }\n"
                        + "}</code></pre>"
                        + "<p><b>RegisterRequest.java</b>: Igual pero con campo <code>email</code> adicional.</p>"
                        + "<p><b>AuthResponse.java</b>:</p>"
                        + "<pre><code>package com.dojo.frontend.dto;\n"
                        + "\n"
                        + "public class AuthResponse {\n"
                        + "    private String token;\n"
                        + "    private String username;\n"
                        + "    private String role;\n"
                        + "\n"
                        + "    // Getters y setters\n"
                        + "}</code></pre>"
                        + "<p>📌 Estos DTOs NO llevan <code>@NotBlank</code> ni validaciones — la validación la hace Auth Service. "
                        + "El frontend solo envía datos y recibe respuestas.</p>"),

                    section("8. AuthController del frontend",
                        "<p><b>Ruta</b>: <code>.../controller/AuthController.java</code></p>"
                        + "<p>⚠️ Este es un <code>@Controller</code> (no @RestController) — devuelve nombres de templates HTML.</p>"
                        + "<pre><code>package com.dojo.frontend.controller;\n"
                        + "\n"
                        + "import com.dojo.frontend.dto.*;\n"
                        + "import jakarta.servlet.http.HttpSession;\n"
                        + "import org.springframework.beans.factory.annotation.Value;\n"
                        + "import org.springframework.http.*;\n"
                        + "import org.springframework.stereotype.Controller;\n"
                        + "import org.springframework.ui.Model;\n"
                        + "import org.springframework.web.bind.annotation.*;\n"
                        + "import org.springframework.web.client.HttpClientErrorException;\n"
                        + "import org.springframework.web.client.RestTemplate;\n"
                        + "\n"
                        + "@Controller\n"
                        + "public class AuthController {\n"
                        + "\n"
                        + "    private final RestTemplate restTemplate;\n"
                        + "    private final String gatewayUrl;\n"
                        + "\n"
                        + "    public AuthController(RestTemplate restTemplate,\n"
                        + "            @Value(\"${gateway.url}\") String gatewayUrl) {\n"
                        + "        this.restTemplate = restTemplate;\n"
                        + "        this.gatewayUrl = gatewayUrl;\n"
                        + "    }\n"
                        + "\n"
                        + "    @GetMapping(\"/login\")\n"
                        + "    public String loginPage(Model model) {\n"
                        + "        model.addAttribute(\"loginRequest\", new LoginRequest());\n"
                        + "        return \"login\";  // → templates/login.html\n"
                        + "    }\n"
                        + "\n"
                        + "    @PostMapping(\"/login\")\n"
                        + "    public String login(@ModelAttribute LoginRequest loginRequest,\n"
                        + "                       HttpSession session, Model model) {\n"
                        + "        try {\n"
                        + "            HttpHeaders headers = new HttpHeaders();\n"
                        + "            headers.setContentType(MediaType.APPLICATION_JSON);\n"
                        + "            HttpEntity&lt;LoginRequest&gt; entity =\n"
                        + "                new HttpEntity&lt;&gt;(loginRequest, headers);\n"
                        + "\n"
                        + "            // Llamar al Gateway → Auth Service\n"
                        + "            ResponseEntity&lt;AuthResponse&gt; response =\n"
                        + "                restTemplate.postForEntity(\n"
                        + "                    gatewayUrl + \"/api/auth/login\",\n"
                        + "                    entity, AuthResponse.class);\n"
                        + "\n"
                        + "            // Guardar token en sesión HTTP\n"
                        + "            AuthResponse auth = response.getBody();\n"
                        + "            if (auth != null) {\n"
                        + "                session.setAttribute(\"token\", auth.getToken());\n"
                        + "                session.setAttribute(\"username\", auth.getUsername());\n"
                        + "                session.setAttribute(\"role\", auth.getRole());\n"
                        + "            }\n"
                        + "            return \"redirect:/dashboard\";\n"
                        + "\n"
                        + "        } catch (HttpClientErrorException e) {\n"
                        + "            model.addAttribute(\"error\",\n"
                        + "                \"Invalid username or password\");\n"
                        + "            model.addAttribute(\"loginRequest\", loginRequest);\n"
                        + "            return \"login\";\n"
                        + "        } catch (Exception e) {\n"
                        + "            model.addAttribute(\"error\",\n"
                        + "                \"Service unavailable. Please try again later.\");\n"
                        + "            model.addAttribute(\"loginRequest\", loginRequest);\n"
                        + "            return \"login\";\n"
                        + "        }\n"
                        + "    }\n"
                        + "\n"
                        + "    // Register: mismo patrón que login\n"
                        + "    // Logout: session.invalidate() + redirect a /login\n"
                        + "    // GET /: redirect a /login\n"
                        + "}</code></pre>"
                        + "<p><b>Conceptos clave:</b></p>"
                        + "<ul>"
                        + "<li><code>@Controller</code> vs <code>@RestController</code> — Controller devuelve el <b>nombre del template</b> "
                        + "(<code>\"login\"</code> → <code>templates/login.html</code>). RestController devuelve datos JSON</li>"
                        + "<li><code>Model model</code> — Objeto que pasa datos del controller al template. "
                        + "<code>model.addAttribute(\"error\", \"msg\")</code> → en HTML: <code>th:text=\"${error}\"</code></li>"
                        + "<li><code>HttpSession</code> — Sesión del servidor. Guarda el JWT para usarlo en peticiones futuras</li>"
                        + "<li><code>@ModelAttribute</code> — Mapea los campos del formulario HTML al DTO de Java</li>"
                        + "<li><code>\"redirect:/dashboard\"</code> — Redirige al navegador (cambia la URL)</li>"
                        + "</ul>"),

                    section("9. Layout compartido (fragments/layout.html)",
                        "<p>Thymeleaf permite definir <b>fragmentos</b> reutilizables. Así no repites el head, navbar y footer en cada página:</p>"
                        + "<p><b>Ruta</b>: <code>templates/fragments/layout.html</code></p>"
                        + "<pre><code>&lt;!DOCTYPE html&gt;\n"
                        + "&lt;html xmlns:th=\"http://www.thymeleaf.org\"&gt;\n"
                        + "\n"
                        + "&lt;!-- HEAD compartido --&gt;\n"
                        + "&lt;head th:fragment=\"head(title)\"&gt;\n"
                        + "    &lt;meta charset=\"UTF-8\"&gt;\n"
                        + "    &lt;meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"&gt;\n"
                        + "    &lt;title th:text=\"${title}\"&gt;Spring Boot Dojo&lt;/title&gt;\n"
                        + "    &lt;link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\"\n"
                        + "          rel=\"stylesheet\"&gt;\n"
                        + "    &lt;link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css\"\n"
                        + "          rel=\"stylesheet\"&gt;\n"
                        + "    &lt;link th:href=\"@{/css/style.css}\" rel=\"stylesheet\"&gt;\n"
                        + "&lt;/head&gt;\n"
                        + "\n"
                        + "&lt;!-- NAVBAR --&gt;\n"
                        + "&lt;nav th:fragment=\"navbar\"\n"
                        + "     class=\"navbar navbar-expand-lg navbar-dark bg-dark\"&gt;\n"
                        + "    &lt;div class=\"container\"&gt;\n"
                        + "        &lt;a class=\"navbar-brand\" href=\"/dashboard\"&gt;\n"
                        + "            &lt;i class=\"bi bi-fire\"&gt;&lt;/i&gt; Spring Boot Dojo\n"
                        + "        &lt;/a&gt;\n"
                        + "        &lt;div class=\"navbar-nav ms-auto\"\n"
                        + "             th:if=\"${session.username != null}\"&gt;\n"
                        + "            &lt;a class=\"nav-link\" href=\"/dashboard\"&gt;Dashboard&lt;/a&gt;\n"
                        + "            &lt;a class=\"nav-link\" href=\"/exercises\"&gt;Ejercicios&lt;/a&gt;\n"
                        + "            &lt;a class=\"nav-link\" href=\"/guia\"&gt;Guía&lt;/a&gt;\n"
                        + "            &lt;span class=\"navbar-text mx-3\"\n"
                        + "                  th:text=\"${session.username}\"&gt;User&lt;/span&gt;\n"
                        + "            &lt;a class=\"nav-link\" href=\"/logout\"&gt;Logout&lt;/a&gt;\n"
                        + "        &lt;/div&gt;\n"
                        + "    &lt;/div&gt;\n"
                        + "&lt;/nav&gt;\n"
                        + "\n"
                        + "&lt;!-- FOOTER (scripts) --&gt;\n"
                        + "&lt;footer th:fragment=\"footer\"&gt;\n"
                        + "    &lt;script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"&gt;&lt;/script&gt;\n"
                        + "&lt;/footer&gt;\n"
                        + "&lt;/html&gt;</code></pre>"
                        + "<p><b>Cómo se usa en otras páginas:</b></p>"
                        + "<pre><code>&lt;!-- Incluir el head --&gt;\n"
                        + "&lt;head th:replace=\"~{fragments/layout :: head('Mi Título')}\"&gt;&lt;/head&gt;\n"
                        + "\n"
                        + "&lt;!-- Incluir la navbar --&gt;\n"
                        + "&lt;nav th:replace=\"~{fragments/layout :: navbar}\"&gt;&lt;/nav&gt;\n"
                        + "\n"
                        + "&lt;!-- Incluir el footer --&gt;\n"
                        + "&lt;div th:replace=\"~{fragments/layout :: footer}\"&gt;&lt;/div&gt;</code></pre>"
                        + "<p>Así todas las páginas tienen el mismo head (Bootstrap CSS + icons), navbar y scripts de Bootstrap.</p>"),

                    section("10. Página de Login (templates/login.html)",
                        "<p><b>Ruta</b>: <code>templates/login.html</code></p>"
                        + "<pre><code>&lt;!DOCTYPE html&gt;\n"
                        + "&lt;html xmlns:th=\"http://www.thymeleaf.org\"&gt;\n"
                        + "&lt;head th:replace=\"~{fragments/layout :: head('Login - Spring Boot Dojo')}\"&gt;&lt;/head&gt;\n"
                        + "&lt;body class=\"bg-light\"&gt;\n"
                        + "\n"
                        + "&lt;div class=\"container\"&gt;\n"
                        + "  &lt;div class=\"row justify-content-center mt-5\"&gt;\n"
                        + "    &lt;div class=\"col-md-5\"&gt;\n"
                        + "      &lt;div class=\"card shadow\"&gt;\n"
                        + "        &lt;div class=\"card-body p-4\"&gt;\n"
                        + "          &lt;div class=\"text-center mb-4\"&gt;\n"
                        + "            &lt;h2&gt;&lt;i class=\"bi bi-fire text-danger\"&gt;&lt;/i&gt;\n"
                        + "              Spring Boot Dojo&lt;/h2&gt;\n"
                        + "            &lt;p class=\"text-muted\"&gt;Sign in to start training&lt;/p&gt;\n"
                        + "          &lt;/div&gt;\n"
                        + "\n"
                        + "          &lt;!-- Mensaje de error --&gt;\n"
                        + "          &lt;div th:if=\"${error}\" class=\"alert alert-danger\"\n"
                        + "               th:text=\"${error}\"&gt;&lt;/div&gt;\n"
                        + "\n"
                        + "          &lt;!-- Formulario --&gt;\n"
                        + "          &lt;form th:action=\"@{/login}\" method=\"post\"\n"
                        + "                th:object=\"${loginRequest}\"&gt;\n"
                        + "            &lt;div class=\"mb-3\"&gt;\n"
                        + "              &lt;label class=\"form-label\"&gt;Username&lt;/label&gt;\n"
                        + "              &lt;input type=\"text\" class=\"form-control\"\n"
                        + "                     th:field=\"*{username}\" required&gt;\n"
                        + "            &lt;/div&gt;\n"
                        + "            &lt;div class=\"mb-3\"&gt;\n"
                        + "              &lt;label class=\"form-label\"&gt;Password&lt;/label&gt;\n"
                        + "              &lt;input type=\"password\" class=\"form-control\"\n"
                        + "                     th:field=\"*{password}\" required&gt;\n"
                        + "            &lt;/div&gt;\n"
                        + "            &lt;button type=\"submit\" class=\"btn btn-dark w-100\"&gt;\n"
                        + "              Login\n"
                        + "            &lt;/button&gt;\n"
                        + "          &lt;/form&gt;\n"
                        + "\n"
                        + "          &lt;div class=\"text-center mt-3\"&gt;\n"
                        + "            &lt;a th:href=\"@{/register}\"&gt;Register here&lt;/a&gt;\n"
                        + "          &lt;/div&gt;\n"
                        + "        &lt;/div&gt;\n"
                        + "      &lt;/div&gt;\n"
                        + "    &lt;/div&gt;\n"
                        + "  &lt;/div&gt;\n"
                        + "&lt;/div&gt;\n"
                        + "\n"
                        + "&lt;div th:replace=\"~{fragments/layout :: footer}\"&gt;&lt;/div&gt;\n"
                        + "&lt;/body&gt;&lt;/html&gt;</code></pre>"
                        + "<p><b>Thymeleaf cheatsheet:</b></p>"
                        + "<table class='table table-sm table-dark'>"
                        + "<thead><tr><th>Sintaxis</th><th>Qué hace</th></tr></thead>"
                        + "<tbody>"
                        + "<tr><td><code>th:text=\"${variable}\"</code></td><td>Muestra el valor de una variable (seguro, escapa HTML)</td></tr>"
                        + "<tr><td><code>th:if=\"${error}\"</code></td><td>Solo muestra el elemento si la variable existe y no es null</td></tr>"
                        + "<tr><td><code>th:action=\"@{/login}\"</code></td><td>URL del action del formulario (con context-path)</td></tr>"
                        + "<tr><td><code>th:object=\"${loginRequest}\"</code></td><td>Vincula el formulario al DTO</td></tr>"
                        + "<tr><td><code>th:field=\"*{username}\"</code></td><td>Vincula el input al campo del DTO (name + value)</td></tr>"
                        + "<tr><td><code>th:replace=\"~{...}\"</code></td><td>Reemplaza el elemento con un fragmento de otro archivo</td></tr>"
                        + "<tr><td><code>th:each=\"item : ${list}\"</code></td><td>Bucle — repite el elemento por cada item (lo usaremos en dashboard)</td></tr>"
                        + "</tbody></table>"),

                    section("11. CSS personalizado (static/css/style.css)",
                        "<p><b>Ruta</b>: <code>src/main/resources/static/css/style.css</code></p>"
                        + "<pre><code>/* Colores para cinturones que Bootstrap no tiene */\n"
                        + ".bg-orange {\n"
                        + "    background-color: #fd7e14 !important;\n"
                        + "    color: white;\n"
                        + "}\n"
                        + ".bg-brown {\n"
                        + "    background-color: #795548 !important;\n"
                        + "    color: white;\n"
                        + "}\n"
                        + "\n"
                        + "/* Animación para las cards de cinturón */\n"
                        + ".belt-card {\n"
                        + "    transition: transform 0.2s;\n"
                        + "}\n"
                        + ".belt-card:hover {\n"
                        + "    transform: translateY(-5px);\n"
                        + "}\n"
                        + "\n"
                        + "/* Hover para flashcards */\n"
                        + ".flashcard:hover {\n"
                        + "    box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.15) !important;\n"
                        + "}</code></pre>"
                        + "<p>Poco CSS propio — Bootstrap 5 hace casi todo. Solo añadimos colores de cinturones "
                        + "(naranja y marrón no existen en Bootstrap) y pequeñas animaciones.</p>"),

                    section("12. Arrancar y probar",
                        "<p>Necesitas <b>todos los servicios corriendo</b>: Eureka → Auth → Content → Gateway → Frontend</p>"
                        + "<pre><code>cd dojo-frontend && mvn spring-boot:run</code></pre>"
                        + "<p>Abre el navegador: 👉 <a href='http://localhost:8090' target='_blank'><b>http://localhost:8090</b></a></p>"
                        + "<ol>"
                        + "<li>Deberías ver la página de <b>login</b></li>"
                        + "<li>Pulsa \"Register here\" → rellena datos → registra</li>"
                        + "<li>Debería redirigir al <b>dashboard</b> (lo crearemos en el siguiente capítulo)</li>"
                        + "</ol>"
                        + "<p>Si ves un error \"Service unavailable\" → alguno de los servicios no está corriendo. "
                        + "Revisa la consola de cada servicio.</p>"),

                    section("⚠️ Errores comunes",
                        "<table class='table table-sm table-dark'>"
                        + "<thead><tr><th>Error</th><th>Causa</th><th>Solución</th></tr></thead>"
                        + "<tbody>"
                        + "<tr><td>Página en blanco</td>"
                        + "<td>Thymeleaf no encuentra el template</td>"
                        + "<td>Verifica que el archivo está en <code>src/main/resources/templates/</code> (no <code>template</code> sin s)</td></tr>"
                        + "<tr><td><code>Error resolving template \"login\"</code></td>"
                        + "<td>El controller devuelve <code>\"login\"</code> pero no existe <code>templates/login.html</code></td>"
                        + "<td>Crea el archivo. El nombre debe coincidir exactamente</td></tr>"
                        + "<tr><td>Los estilos no cargan</td>"
                        + "<td>El CSS no está en <code>static/</code></td>"
                        + "<td>Archivos estáticos van en <code>src/main/resources/static/</code>. Accesibles como <code>/css/style.css</code></td></tr>"
                        + "<tr><td><code>Connection refused</code> al login</td>"
                        + "<td>El Gateway no está corriendo o la URL es incorrecta</td>"
                        + "<td>Verifica <code>gateway.url</code> en application.yml → <code>http://localhost:8080</code></td></tr>"
                        + "<tr><td>Cambios en HTML no se reflejan</td>"
                        + "<td>Caché de Thymeleaf activado</td>"
                        + "<td><code>thymeleaf.cache: false</code> en application.yml. Si usas IntelliJ, haz Build → Recompile (Ctrl+Shift+F9)</td></tr>"
                        + "</tbody></table>"),

                    section("✅ Checklist antes de continuar",
                        "<ul>"
                        + "<li>☐ Proyecto <code>dojo-frontend</code> creado</li>"
                        + "<li>☐ AppConfig con bean RestTemplate</li>"
                        + "<li>☐ DTOs: LoginRequest, RegisterRequest, AuthResponse</li>"
                        + "<li>☐ AuthController con login, register, logout</li>"
                        + "<li>☐ layout.html con head + navbar + footer fragments</li>"
                        + "<li>☐ login.html y register.html</li>"
                        + "<li>☐ style.css con colores de cinturones</li>"
                        + "<li>☐ Puedes abrir <a href='http://localhost:8090'>localhost:8090</a> y ver la página de login</li>"
                        + "<li>☐ Login funciona y redirige al dashboard</li>"
                        + "<li>☐ Commit: <code>git commit -m \"Add frontend with login and register\"</code></li>"
                        + "</ul>"
                        + "<p>¡Ya tiene cara! 🎨 En el siguiente capítulo montamos el <b>Dashboard</b> con las tarjetas de cinturones "
                        + "y el <b>modo de estudio</b> de flashcards. 🥋</p>")
                ));

    }
}
