package com.dojo.frontend.controller.guia;

import java.util.*;
import static com.dojo.frontend.controller.guia.GuiaHelper.*;

public class GuiaCapitulo03 {

    public static Map<String, Object> getPaso() {
        return crearPaso(
            3, "Eureka Server (Service Discovery)", "bi-broadcast",
                "El primer microservicio que vamos a crear es Eureka Server. Es el servicio de descubrimiento: "
                + "el resto de microservicios se registran en él al arrancar, y cuando un servicio necesita hablar con otro, "
                + "le pregunta a Eureka dónde está. Piensa en él como una guía telefónica: buscas por nombre "
                + "(\"auth-service\") y Eureka te dice la dirección (IP + puerto).",
                List.of(

                    section("1. ¿Qué problema resuelve Eureka?",
                        "<p>Sin Eureka, cada servicio tendría que saber la URL exacta de los demás. "
                        + "Por ejemplo, el Gateway tendría hardcodeado <code>http://localhost:8081</code> para hablar con Auth. "
                        + "Esto funciona en desarrollo, pero en producción los servicios pueden cambiar de IP, "
                        + "tener varias instancias, o estar en diferentes máquinas.</p>"
                        + "<p><b>Con Eureka:</b></p>"
                        + "<ol>"
                        + "<li>Cada servicio arranca y le dice a Eureka: \"Hola, soy <code>auth-service</code> y estoy en <code>192.168.1.5:8081</code>\"</li>"
                        + "<li>Cuando el Gateway necesita llamar a Auth, pregunta a Eureka: \"¿Dónde está <code>auth-service</code>?\"</li>"
                        + "<li>Eureka responde con la dirección actual</li>"
                        + "<li>Si hay 3 instancias de auth-service, Eureka las devuelve todas y el Gateway puede hacer <b>balanceo de carga</b></li>"
                        + "</ol>"
                        + "<p>En Spring Cloud, esto se traduce en usar <code>lb://auth-service</code> en vez de <code>http://localhost:8081</code>. "
                        + "El prefijo <code>lb://</code> significa \"load balanced\" — busca en Eureka y elige una instancia.</p>"),

                    section("2. Crear el proyecto eureka-server",
                        "<p><b>Opción A — Desde IntelliJ (Spring Initializr):</b></p>"
                        + "<ol>"
                        + "<li><b>File → New → Module</b> (dentro de spring-boot-dojo)</li>"
                        + "<li>Selecciona <b>Spring Initializr</b></li>"
                        + "<li>Group: <code>com.dojo</code> / Artifact: <code>eureka-server</code></li>"
                        + "<li>Type: Maven / Java 17 / Spring Boot 3.2.0</li>"
                        + "<li>Next → En dependencias busca y selecciona: <b>Eureka Server</b> (dentro de Spring Cloud Discovery)</li>"
                        + "<li>Create</li>"
                        + "</ol>"
                        + "<p><b>Opción B — Desde la web:</b></p>"
                        + "<ol>"
                        + "<li>Ve a <a href='https://start.spring.io/' target='_blank'>start.spring.io</a></li>"
                        + "<li>Configura: Maven, Java 17, Spring Boot 3.2.0, Group: com.dojo, Artifact: eureka-server</li>"
                        + "<li>ADD DEPENDENCIES → busca \"Eureka Server\" → añádelo</li>"
                        + "<li>GENERATE → descarga el .zip → descomprime en <code>spring-boot-dojo/eureka-server/</code></li>"
                        + "</ol>"
                        + "<p>La estructura creada será:</p>"
                        + "<pre><code>eureka-server/\n"
                        + "├── src/\n"
                        + "│   └── main/\n"
                        + "│       ├── java/com/dojo/eureka/\n"
                        + "│       │   └── EurekaServerApplication.java\n"
                        + "│       └── resources/\n"
                        + "│           └── application.properties  ← Lo cambiaremos a .yml\n"
                        + "└── pom.xml</code></pre>"),

                    section("3. El pom.xml completo",
                        "<p>Spring Initializr genera el pom.xml con las dependencias que seleccionaste. "
                        + "Debe quedar así:</p>"
                        + "<pre><code>&lt;?xml version=\"1.0\" encoding=\"UTF-8\"?&gt;\n"
                        + "&lt;project xmlns=\"http://maven.apache.org/POM/4.0.0\"\n"
                        + "         xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n"
                        + "         xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0\n"
                        + "         https://maven.apache.org/xsd/maven-4.0.0.xsd\"&gt;\n"
                        + "    &lt;modelVersion&gt;4.0.0&lt;/modelVersion&gt;\n"
                        + "\n"
                        + "    &lt;parent&gt;\n"
                        + "        &lt;groupId&gt;org.springframework.boot&lt;/groupId&gt;\n"
                        + "        &lt;artifactId&gt;spring-boot-starter-parent&lt;/artifactId&gt;\n"
                        + "        &lt;version&gt;3.2.0&lt;/version&gt;\n"
                        + "        &lt;relativePath/&gt;\n"
                        + "    &lt;/parent&gt;\n"
                        + "\n"
                        + "    &lt;groupId&gt;com.dojo&lt;/groupId&gt;\n"
                        + "    &lt;artifactId&gt;eureka-server&lt;/artifactId&gt;\n"
                        + "    &lt;version&gt;0.0.1-SNAPSHOT&lt;/version&gt;\n"
                        + "    &lt;name&gt;eureka-server&lt;/name&gt;\n"
                        + "    &lt;description&gt;Service Discovery - Spring Boot Dojo&lt;/description&gt;\n"
                        + "\n"
                        + "    &lt;properties&gt;\n"
                        + "        &lt;java.version&gt;17&lt;/java.version&gt;\n"
                        + "        &lt;spring-cloud.version&gt;2023.0.0&lt;/spring-cloud.version&gt;\n"
                        + "    &lt;/properties&gt;\n"
                        + "\n"
                        + "    &lt;dependencies&gt;\n"
                        + "        &lt;!-- La única dependencia: Eureka Server --&gt;\n"
                        + "        &lt;dependency&gt;\n"
                        + "            &lt;groupId&gt;org.springframework.cloud&lt;/groupId&gt;\n"
                        + "            &lt;artifactId&gt;spring-cloud-starter-netflix-eureka-server&lt;/artifactId&gt;\n"
                        + "        &lt;/dependency&gt;\n"
                        + "    &lt;/dependencies&gt;\n"
                        + "\n"
                        + "    &lt;!-- Gestión de versiones de Spring Cloud --&gt;\n"
                        + "    &lt;dependencyManagement&gt;\n"
                        + "        &lt;dependencies&gt;\n"
                        + "            &lt;dependency&gt;\n"
                        + "                &lt;groupId&gt;org.springframework.cloud&lt;/groupId&gt;\n"
                        + "                &lt;artifactId&gt;spring-cloud-dependencies&lt;/artifactId&gt;\n"
                        + "                &lt;version&gt;${spring-cloud.version}&lt;/version&gt;\n"
                        + "                &lt;type&gt;pom&lt;/type&gt;\n"
                        + "                &lt;scope&gt;import&lt;/scope&gt;\n"
                        + "            &lt;/dependency&gt;\n"
                        + "        &lt;/dependencies&gt;\n"
                        + "    &lt;/dependencyManagement&gt;\n"
                        + "\n"
                        + "    &lt;build&gt;\n"
                        + "        &lt;plugins&gt;\n"
                        + "            &lt;plugin&gt;\n"
                        + "                &lt;groupId&gt;org.springframework.boot&lt;/groupId&gt;\n"
                        + "                &lt;artifactId&gt;spring-boot-maven-plugin&lt;/artifactId&gt;\n"
                        + "            &lt;/plugin&gt;\n"
                        + "        &lt;/plugins&gt;\n"
                        + "    &lt;/build&gt;\n"
                        + "&lt;/project&gt;</code></pre>"
                        + "<p>📌 <b>Nota</b>: Fíjate en el bloque <code>&lt;dependencyManagement&gt;</code>. "
                        + "Esto NO añade dependencias — solo <b>gestiona las versiones</b> de Spring Cloud. "
                        + "Así cuando declaras <code>spring-cloud-starter-netflix-eureka-server</code> arriba, "
                        + "no necesitas especificar la versión porque ya la sabe por <code>spring-cloud-dependencies</code>.</p>"),

                    section("4. La clase principal: EurekaServerApplication.java",
                        "<p><b>Ruta</b>: <code>eureka-server/src/main/java/com/dojo/eureka/EurekaServerApplication.java</code></p>"
                        + "<pre><code>package com.dojo.eureka;\n"
                        + "\n"
                        + "import org.springframework.boot.SpringApplication;\n"
                        + "import org.springframework.boot.autoconfigure.SpringBootApplication;\n"
                        + "import org.springframework.cloud.netflix.eureka.server.EnableEurekaServer;\n"
                        + "\n"
                        + "@SpringBootApplication\n"
                        + "@EnableEurekaServer  // ← Esta anotación activa Eureka\n"
                        + "public class EurekaServerApplication {\n"
                        + "\n"
                        + "    public static void main(String[] args) {\n"
                        + "        SpringApplication.run(EurekaServerApplication.class, args);\n"
                        + "    }\n"
                        + "}</code></pre>"
                        + "<p><b>¿Qué hace cada cosa?</b></p>"
                        + "<ul>"
                        + "<li><code>@SpringBootApplication</code> — Ya la conoces del capítulo anterior: configuración + auto-config + component scan</li>"
                        + "<li><code>@EnableEurekaServer</code> — Le dice a Spring Boot que este servicio <b>ES</b> un servidor Eureka. "
                        + "Sin esta anotación, sería una app Spring Boot normal que no hace nada especial</li>"
                        + "<li><code>SpringApplication.run(...)</code> — Arranca la aplicación. Standard en todos los servicios</li>"
                        + "</ul>"
                        + "<p>Sí, es todo. Solo 2 anotaciones y un main. Spring Boot se encarga del resto. "
                        + "Toda la magia está en las dependencias del pom.xml y la configuración del application.yml.</p>"),

                    section("5. Configuración: application.yml",
                        "<p><b>Ruta</b>: <code>eureka-server/src/main/resources/application.yml</code></p>"
                        + "<p>⚠️ Spring Initializr genera <code>application.properties</code>. "
                        + "Renómbralo a <code>application.yml</code> — es más legible para configuraciones jerárquicas.</p>"
                        + "<p>En IntelliJ: click derecho sobre el archivo → <b>Refactor → Rename</b> → cambia la extensión a <code>.yml</code></p>"
                        + "<pre><code>server:\n"
                        + "  port: 8761  # Puerto estándar de Eureka\n"
                        + "\n"
                        + "spring:\n"
                        + "  application:\n"
                        + "    name: eureka-server  # Nombre del servicio\n"
                        + "\n"
                        + "eureka:\n"
                        + "  client:\n"
                        + "    register-with-eureka: false  # No se registra a sí mismo\n"
                        + "    fetch-registry: false        # No busca otros servidores Eureka\n"
                        + "  server:\n"
                        + "    enable-self-preservation: false  # Desactivar en desarrollo</code></pre>"
                        + "<p><b>¿Por qué estas configuraciones?</b></p>"
                        + "<table class='table table-sm table-dark'>"
                        + "<thead><tr><th>Propiedad</th><th>Valor</th><th>¿Por qué?</th></tr></thead>"
                        + "<tbody>"
                        + "<tr><td><code>server.port</code></td><td>8761</td>"
                        + "<td>Puerto estándar de Eureka. Todos los servicios buscan Eureka en este puerto por defecto</td></tr>"
                        + "<tr><td><code>spring.application.name</code></td><td>eureka-server</td>"
                        + "<td>Identifica al servicio. No es crítico aquí porque Eureka no se registra a sí mismo, pero es buena práctica</td></tr>"
                        + "<tr><td><code>register-with-eureka</code></td><td>false</td>"
                        + "<td>Eureka ES el servidor, no necesita registrarse en sí mismo. Si lo dejas en true, intenta registrarse y lanza errores en el log</td></tr>"
                        + "<tr><td><code>fetch-registry</code></td><td>false</td>"
                        + "<td>No necesita descargar el registro de otro Eureka (solo hay uno). En producción con múltiples Eureka, sería true</td></tr>"
                        + "<tr><td><code>enable-self-preservation</code></td><td>false</td>"
                        + "<td>En producción, Eureka no elimina servicios caídos por si es un problema de red temporal. En desarrollo esto es un incordio — desactívalo para que los servicios se limpien rápido</td></tr>"
                        + "</tbody></table>"),

                    section("6. Arrancar y probar",
                        "<p><b>Desde IntelliJ:</b></p>"
                        + "<ol>"
                        + "<li>Abre <code>EurekaServerApplication.java</code></li>"
                        + "<li>Click en el botón verde ▶ que aparece al lado del método <code>main</code></li>"
                        + "<li>O usa la Run Configuration que creamos en el capítulo 1: <code>Eureka Server</code></li>"
                        + "</ol>"
                        + "<p><b>Desde terminal:</b></p>"
                        + "<pre><code>cd eureka-server\nmvn spring-boot:run</code></pre>"
                        + "<p><b>¿Qué deberías ver en la consola?</b></p>"
                        + "<pre><code>  .   ____          _            __ _ _\n"
                        + " /\\\\ / ___'_ __ _ _(_)_ __  __ _ \\ \\ \\ \\\n"
                        + "( ( )\\___ | '_ | '_| | '_ \\/ _` | \\ \\ \\ \\\n"
                        + " \\\\/  ___)| |_)| | | | | || (_| |  ) ) ) )\n"
                        + "  '  |____| .__|_| |_|_| |_\\__, | / / / /\n"
                        + " =========|_|==============|___/=/_/_/_/\n"
                        + " :: Spring Boot ::                (v3.2.0)\n"
                        + "\n"
                        + "... Started EurekaServerApplication in X.XXX seconds</code></pre>"
                        + "<p>Cuando veas <code>Started EurekaServerApplication</code>, abre el navegador:</p>"
                        + "<p>👉 <a href='http://localhost:8761' target='_blank'><b>http://localhost:8761</b></a></p>"
                        + "<p>Verás el <b>dashboard de Eureka</b>: una página web con información del servidor. "
                        + "La sección <b>\"Instances currently registered with Eureka\"</b> estará vacía — es normal, "
                        + "todavía no hemos arrancado ningún otro servicio.</p>"
                        + "<p>Cuando arranquemos los siguientes servicios, aparecerán listados ahí automáticamente. "
                        + "Deja Eureka corriendo mientras desarrollas los demás servicios.</p>"),

                    section("⚠️ Errores comunes",
                        "<table class='table table-sm table-dark'>"
                        + "<thead><tr><th>Error</th><th>Causa</th><th>Solución</th></tr></thead>"
                        + "<tbody>"
                        + "<tr>"
                        + "<td><code>Port 8761 already in use</code></td>"
                        + "<td>Ya tienes algo corriendo en ese puerto (otra instancia de Eureka o cualquier otra app)</td>"
                        + "<td>Cierra el proceso: <code>lsof -i :8761</code> (Linux/Mac) o <code>netstat -ano | findstr 8761</code> (Windows), "
                        + "luego mata el proceso. O cambia el puerto en application.yml</td>"
                        + "</tr>"
                        + "<tr>"
                        + "<td><code>Cannot resolve spring-cloud-starter-netflix-eureka-server</code></td>"
                        + "<td>Falta el bloque <code>dependencyManagement</code> con <code>spring-cloud-dependencies</code> en tu pom.xml</td>"
                        + "<td>Copia el bloque <code>&lt;dependencyManagement&gt;</code> completo del paso anterior. "
                        + "Luego haz Maven Reload (🔄)</td>"
                        + "</tr>"
                        + "<tr>"
                        + "<td><code>Connection refused</code> en el log (repetido)</td>"
                        + "<td>Eureka intenta registrarse en sí mismo porque <code>register-with-eureka</code> no está en false</td>"
                        + "<td>Asegúrate de tener <code>register-with-eureka: false</code> y <code>fetch-registry: false</code></td>"
                        + "</tr>"
                        + "<tr>"
                        + "<td>Dashboard vacío</td>"
                        + "<td>No hay otros servicios registrados</td>"
                        + "<td>¡Es normal! Los verás cuando arranques auth-service, content-service, etc.</td>"
                        + "</tr>"
                        + "<tr>"
                        + "<td><code>java.lang.NoSuchMethodError</code> o errores raros de classpath</td>"
                        + "<td>Versiones incompatibles de Spring Boot y Spring Cloud</td>"
                        + "<td>Spring Boot 3.2.x necesita Spring Cloud 2023.0.x. Verifica que ambas versiones coinciden en tu pom.xml. "
                        + "Consulta la <a href='https://spring.io/projects/spring-cloud#overview' target='_blank'>tabla de compatibilidad</a></td>"
                        + "</tr>"
                        + "</tbody></table>"),

                    section("💡 Conceptos para la entrevista",
                        "<p>Si te preguntan sobre Eureka en una entrevista de Spring Boot, estos son los puntos clave:</p>"
                        + "<ul>"
                        + "<li><b>Service Discovery</b> — Patrón que permite a los servicios encontrarse entre sí sin URLs hardcodeadas</li>"
                        + "<li><b>Eureka Server</b> — El registro central donde los servicios se apuntan</li>"
                        + "<li><b>Eureka Client</b> — Cada microservicio que se registra en Eureka (lo veremos en los siguientes capítulos)</li>"
                        + "<li><b>Heartbeat</b> — Los clientes envían un \"ping\" cada 30 segundos para decir que siguen vivos</li>"
                        + "<li><b>Self-preservation</b> — Si Eureka deja de recibir heartbeats de muchos servicios a la vez, "
                        + "asume que es un problema de red (no que todos cayeron) y NO los elimina del registro</li>"
                        + "<li><b>Alternativas</b> — Consul, Zookeeper, Kubernetes DNS. Eureka es el estándar de Netflix/Spring Cloud</li>"
                        + "</ul>"),

                    section("✅ Checklist antes de continuar",
                        "<ul>"
                        + "<li>☐ Proyecto <code>eureka-server</code> creado dentro de <code>spring-boot-dojo/</code></li>"
                        + "<li>☐ pom.xml con la dependencia <code>spring-cloud-starter-netflix-eureka-server</code></li>"
                        + "<li>☐ <code>@EnableEurekaServer</code> en la clase principal</li>"
                        + "<li>☐ <code>application.yml</code> configurado (puerto 8761, register false, fetch false)</li>"
                        + "<li>☐ Arranca sin errores y ves el dashboard en <a href='http://localhost:8761'>localhost:8761</a></li>"
                        + "<li>☐ Commit: <code>git commit -m \"Add eureka-server\"</code></li>"
                        + "</ul>"
                        + "<p>¡Primer microservicio funcionando! 🎉 Ahora vamos con el que más chicha tiene: <b>Auth Service</b>. 🔐</p>")
                ));

    }
}
