package com.dojo.frontend.controller.guia;

import java.util.*;
import static com.dojo.frontend.controller.guia.GuiaHelper.*;

public class GuiaCapitulo06 {

    public static Map<String, Object> getPaso() {
        return crearPaso(
            6, "API Gateway", "bi-diagram-3",
                "El API Gateway es el punto de entrada único a toda la arquitectura. Los clientes (frontend, apps) solo hablan con el Gateway en el puerto 8080, "
                + "y este redirige las peticiones al servicio correcto consultando Eureka. Además, valida los tokens JWT antes de dejar pasar las peticiones. "
                + "Es como la recepción de un hotel con control de acceso: verificas tu identidad y te conectan con quien necesites.",
                List.of(

                    section("1. ¿Qué hace el API Gateway?",
                        "<p>El Gateway tiene <b>tres funciones principales</b>:</p>"
                        + "<ol>"
                        + "<li><b>Routing</b> — Redirige peticiones al servicio correcto según la URL:<br>"
                        + "<code>/api/auth/**</code> → auth-service<br>"
                        + "<code>/api/content/**</code> → content-service<br>"
                        + "<code>/api/progress/**</code> → progress-service</li>"
                        + "<li><b>Seguridad</b> — Valida el token JWT en las peticiones. Si no hay token o es inválido, devuelve 401</li>"
                        + "<li><b>Descubrimiento</b> — No necesita saber IPs. Pregunta a Eureka: \"¿Dónde está content-service?\" y Eureka le dice</li>"
                        + "</ol>"
                        + "<pre><code>Cliente → Gateway (:8080) → Eureka: ¿dónde está auth-service?\n"
                        + "                                   → Eureka: está en localhost:8081\n"
                        + "                          → auth-service (:8081)\n"
                        + "                          ← respuesta\n"
                        + "       ← respuesta al cliente</code></pre>"),

                    section("2. Crear el proyecto api-gateway",
                        "<p><b>Spring Initializr</b> con estas dependencias:</p>"
                        + "<table class='table table-sm table-dark'>"
                        + "<thead><tr><th>Dependencia</th><th>Para qué</th></tr></thead>"
                        + "<tbody>"
                        + "<tr><td><b>Gateway</b> (Spring Cloud Routing)</td><td>El core del Gateway — routing, filtros, predicates</td></tr>"
                        + "<tr><td><b>Eureka Discovery Client</b></td><td>Buscar servicios en Eureka (<code>lb://</code>)</td></tr>"
                        + "</tbody></table>"
                        + "<p>⚠️ <b>Importante</b>: JJWT se añade manualmente al pom.xml (igual que en auth-service).</p>"
                        + "<p>⚠️⚠️ <b>MUY IMPORTANTE</b>: NO añadas <code>spring-boot-starter-web</code>. "
                        + "El Gateway usa <b>WebFlux</b> (reactivo, no bloqueante). "
                        + "Si añades starter-web, da un conflicto de classpath y no arranca. "
                        + "Spring Cloud Gateway es incompatible con Spring MVC.</p>"),

                    section("3. pom.xml completo",
                        "<p><b>Ruta</b>: <code>api-gateway/pom.xml</code></p>"
                        + "<pre><code>&lt;?xml version=\"1.0\" encoding=\"UTF-8\"?&gt;\n"
                        + "&lt;project ...&gt;\n"
                        + "    &lt;modelVersion&gt;4.0.0&lt;/modelVersion&gt;\n"
                        + "\n"
                        + "    &lt;parent&gt;\n"
                        + "        &lt;groupId&gt;org.springframework.boot&lt;/groupId&gt;\n"
                        + "        &lt;artifactId&gt;spring-boot-starter-parent&lt;/artifactId&gt;\n"
                        + "        &lt;version&gt;3.2.0&lt;/version&gt;\n"
                        + "        &lt;relativePath/&gt;\n"
                        + "    &lt;/parent&gt;\n"
                        + "\n"
                        + "    &lt;groupId&gt;com.dojo&lt;/groupId&gt;\n"
                        + "    &lt;artifactId&gt;api-gateway&lt;/artifactId&gt;\n"
                        + "    &lt;version&gt;0.0.1-SNAPSHOT&lt;/version&gt;\n"
                        + "\n"
                        + "    &lt;properties&gt;\n"
                        + "        &lt;java.version&gt;17&lt;/java.version&gt;\n"
                        + "        &lt;spring-cloud.version&gt;2023.0.0&lt;/spring-cloud.version&gt;\n"
                        + "        &lt;jjwt.version&gt;0.12.3&lt;/jjwt.version&gt;\n"
                        + "    &lt;/properties&gt;\n"
                        + "\n"
                        + "    &lt;dependencies&gt;\n"
                        + "        &lt;!-- Spring Cloud Gateway (NO spring-boot-starter-web!) --&gt;\n"
                        + "        &lt;dependency&gt;\n"
                        + "            &lt;groupId&gt;org.springframework.cloud&lt;/groupId&gt;\n"
                        + "            &lt;artifactId&gt;spring-cloud-starter-gateway&lt;/artifactId&gt;\n"
                        + "        &lt;/dependency&gt;\n"
                        + "\n"
                        + "        &lt;!-- Eureka Client --&gt;\n"
                        + "        &lt;dependency&gt;\n"
                        + "            &lt;groupId&gt;org.springframework.cloud&lt;/groupId&gt;\n"
                        + "            &lt;artifactId&gt;spring-cloud-starter-netflix-eureka-client&lt;/artifactId&gt;\n"
                        + "        &lt;/dependency&gt;\n"
                        + "\n"
                        + "        &lt;!-- JWT (para validar tokens en el filtro) --&gt;\n"
                        + "        &lt;dependency&gt;\n"
                        + "            &lt;groupId&gt;io.jsonwebtoken&lt;/groupId&gt;\n"
                        + "            &lt;artifactId&gt;jjwt-api&lt;/artifactId&gt;\n"
                        + "            &lt;version&gt;${jjwt.version}&lt;/version&gt;\n"
                        + "        &lt;/dependency&gt;\n"
                        + "        &lt;dependency&gt;\n"
                        + "            &lt;groupId&gt;io.jsonwebtoken&lt;/groupId&gt;\n"
                        + "            &lt;artifactId&gt;jjwt-impl&lt;/artifactId&gt;\n"
                        + "            &lt;version&gt;${jjwt.version}&lt;/version&gt;\n"
                        + "            &lt;scope&gt;runtime&lt;/scope&gt;\n"
                        + "        &lt;/dependency&gt;\n"
                        + "        &lt;dependency&gt;\n"
                        + "            &lt;groupId&gt;io.jsonwebtoken&lt;/groupId&gt;\n"
                        + "            &lt;artifactId&gt;jjwt-jackson&lt;/artifactId&gt;\n"
                        + "            &lt;version&gt;${jjwt.version}&lt;/version&gt;\n"
                        + "            &lt;scope&gt;runtime&lt;/scope&gt;\n"
                        + "        &lt;/dependency&gt;\n"
                        + "    &lt;/dependencies&gt;\n"
                        + "\n"
                        + "    &lt;dependencyManagement&gt;\n"
                        + "        &lt;dependencies&gt;\n"
                        + "            &lt;dependency&gt;\n"
                        + "                &lt;groupId&gt;org.springframework.cloud&lt;/groupId&gt;\n"
                        + "                &lt;artifactId&gt;spring-cloud-dependencies&lt;/artifactId&gt;\n"
                        + "                &lt;version&gt;${spring-cloud.version}&lt;/version&gt;\n"
                        + "                &lt;type&gt;pom&lt;/type&gt;\n"
                        + "                &lt;scope&gt;import&lt;/scope&gt;\n"
                        + "            &lt;/dependency&gt;\n"
                        + "        &lt;/dependencies&gt;\n"
                        + "    &lt;/dependencyManagement&gt;\n"
                        + "\n"
                        + "    &lt;build&gt;\n"
                        + "        &lt;plugins&gt;\n"
                        + "            &lt;plugin&gt;\n"
                        + "                &lt;groupId&gt;org.springframework.boot&lt;/groupId&gt;\n"
                        + "                &lt;artifactId&gt;spring-boot-maven-plugin&lt;/artifactId&gt;\n"
                        + "            &lt;/plugin&gt;\n"
                        + "        &lt;/plugins&gt;\n"
                        + "    &lt;/build&gt;\n"
                        + "&lt;/project&gt;</code></pre>"
                        + "<p>Fíjate: solo 3 dependencias + JJWT. Es el servicio más ligero en código pero el más crítico en configuración.</p>"),

                    section("4. Estructura de carpetas",
                        "<pre><code>com.dojo.gateway/\n"
                        + "├── ApiGatewayApplication.java\n"
                        + "└── filter/\n"
                        + "    └── JwtAuthFilter.java        ← El filtro de seguridad</code></pre>"
                        + "<p>¡Solo 2 archivos Java! Toda la magia está en el <code>application.yml</code> (rutas) "
                        + "y el filtro JWT.</p>"),

                    section("5. Clase principal",
                        "<p><b>Ruta</b>: <code>api-gateway/src/main/java/com/dojo/gateway/ApiGatewayApplication.java</code></p>"
                        + "<pre><code>package com.dojo.gateway;\n"
                        + "\n"
                        + "import org.springframework.boot.SpringApplication;\n"
                        + "import org.springframework.boot.autoconfigure.SpringBootApplication;\n"
                        + "import org.springframework.cloud.client.discovery.EnableDiscoveryClient;\n"
                        + "\n"
                        + "@SpringBootApplication\n"
                        + "@EnableDiscoveryClient\n"
                        + "public class ApiGatewayApplication {\n"
                        + "    public static void main(String[] args) {\n"
                        + "        SpringApplication.run(ApiGatewayApplication.class, args);\n"
                        + "    }\n"
                        + "}</code></pre>"
                        + "<p>Igual que los demás servicios — <code>@EnableDiscoveryClient</code> para registrarse en Eureka.</p>"),

                    section("6. El filtro JWT (filter/JwtAuthFilter.java)",
                        "<p>Este es el archivo más importante del Gateway. Intercepta cada petición y valida el token:</p>"
                        + "<p><b>Ruta</b>: <code>api-gateway/src/main/java/com/dojo/gateway/filter/JwtAuthFilter.java</code></p>"
                        + "<pre><code>package com.dojo.gateway.filter;\n"
                        + "\n"
                        + "import io.jsonwebtoken.Claims;\n"
                        + "import io.jsonwebtoken.Jwts;\n"
                        + "import io.jsonwebtoken.security.Keys;\n"
                        + "import org.springframework.beans.factory.annotation.Value;\n"
                        + "import org.springframework.cloud.gateway.filter.GatewayFilter;\n"
                        + "import org.springframework.cloud.gateway.filter.factory\n"
                        + "        .AbstractGatewayFilterFactory;\n"
                        + "import org.springframework.http.HttpHeaders;\n"
                        + "import org.springframework.http.HttpStatus;\n"
                        + "import org.springframework.http.server.reactive.ServerHttpRequest;\n"
                        + "import org.springframework.stereotype.Component;\n"
                        + "\n"
                        + "import javax.crypto.SecretKey;\n"
                        + "import java.nio.charset.StandardCharsets;\n"
                        + "\n"
                        + "@Component\n"
                        + "public class JwtAuthFilter extends\n"
                        + "        AbstractGatewayFilterFactory&lt;JwtAuthFilter.Config&gt; {\n"
                        + "\n"
                        + "    private final SecretKey key;\n"
                        + "\n"
                        + "    public JwtAuthFilter(@Value(\"${jwt.secret}\") String secret) {\n"
                        + "        super(Config.class);\n"
                        + "        this.key = Keys.hmacShaKeyFor(\n"
                        + "            secret.getBytes(StandardCharsets.UTF_8));\n"
                        + "    }\n"
                        + "\n"
                        + "    @Override\n"
                        + "    public GatewayFilter apply(Config config) {\n"
                        + "        return (exchange, chain) -> {\n"
                        + "\n"
                        + "            // 1. Buscar el header Authorization\n"
                        + "            String authHeader = exchange.getRequest()\n"
                        + "                .getHeaders().getFirst(HttpHeaders.AUTHORIZATION);\n"
                        + "\n"
                        + "            // 2. Si no hay token → 401 Unauthorized\n"
                        + "            if (authHeader == null\n"
                        + "                    || !authHeader.startsWith(\"Bearer \")) {\n"
                        + "                exchange.getResponse()\n"
                        + "                    .setStatusCode(HttpStatus.UNAUTHORIZED);\n"
                        + "                return exchange.getResponse().setComplete();\n"
                        + "            }\n"
                        + "\n"
                        + "            // 3. Extraer el token (quitar \"Bearer \")\n"
                        + "            String token = authHeader.substring(7);\n"
                        + "\n"
                        + "            try {\n"
                        + "                // 4. Validar y parsear el token\n"
                        + "                Claims claims = Jwts.parser()\n"
                        + "                    .verifyWith(key)\n"
                        + "                    .build()\n"
                        + "                    .parseSignedClaims(token)\n"
                        + "                    .getPayload();\n"
                        + "\n"
                        + "                // 5. Añadir datos del usuario como headers\n"
                        + "                //    para que los servicios los lean\n"
                        + "                ServerHttpRequest mutatedRequest = exchange\n"
                        + "                    .getRequest().mutate()\n"
                        + "                    .header(\"X-User-Username\",\n"
                        + "                        claims.getSubject())\n"
                        + "                    .header(\"X-User-Role\",\n"
                        + "                        claims.get(\"role\", String.class))\n"
                        + "                    .build();\n"
                        + "\n"
                        + "                // 6. Continuar con la petición modificada\n"
                        + "                return chain.filter(\n"
                        + "                    exchange.mutate()\n"
                        + "                        .request(mutatedRequest).build());\n"
                        + "\n"
                        + "            } catch (Exception e) {\n"
                        + "                // 7. Token inválido o expirado → 401\n"
                        + "                exchange.getResponse()\n"
                        + "                    .setStatusCode(HttpStatus.UNAUTHORIZED);\n"
                        + "                return exchange.getResponse().setComplete();\n"
                        + "            }\n"
                        + "        };\n"
                        + "    }\n"
                        + "\n"
                        + "    // Clase de configuración (vacía, pero necesaria)\n"
                        + "    public static class Config {}\n"
                        + "}</code></pre>"
                        + "<p><b>Flujo paso a paso:</b></p>"
                        + "<ol>"
                        + "<li>Llega una petición al Gateway (ej: <code>GET /api/content/flashcards</code>)</li>"
                        + "<li>El filtro busca el header <code>Authorization: Bearer eyJhbGci...</code></li>"
                        + "<li>Si no hay header → 401 inmediato</li>"
                        + "<li>Extrae el token y lo valida con la <b>misma clave secreta</b> que usó Auth Service para firmarlo</li>"
                        + "<li>Si es válido, extrae el username y role del token y los añade como headers <code>X-User-*</code></li>"
                        + "<li>La petición continúa hacia el servicio destino, que puede leer esos headers</li>"
                        + "<li>Si el token es inválido o expirado → 401</li>"
                        + "</ol>"
                        + "<p>📌 <b>¿Por qué <code>AbstractGatewayFilterFactory</code> y no <code>GlobalFilter</code>?</b></p>"
                        + "<p>Porque así podemos aplicar el filtro <b>solo a las rutas que lo necesiten</b>. "
                        + "Las rutas de auth (login, register) NO llevan filtro JWT — si no, no podrías loguearte sin estar logueado.</p>"),

                    section("7. application.yml — Las rutas",
                        "<p><b>Ruta</b>: <code>api-gateway/src/main/resources/application.yml</code></p>"
                        + "<pre><code>server:\n"
                        + "  port: 8080\n"
                        + "\n"
                        + "spring:\n"
                        + "  application:\n"
                        + "    name: api-gateway\n"
                        + "  cloud:\n"
                        + "    gateway:\n"
                        + "      routes:\n"
                        + "        # Auth Service — SIN filtro JWT (rutas públicas)\n"
                        + "        - id: auth-service\n"
                        + "          uri: lb://auth-service\n"
                        + "          predicates:\n"
                        + "            - Path=/api/auth/**\n"
                        + "          filters:\n"
                        + "            - StripPrefix=1\n"
                        + "\n"
                        + "        # Content Service — CON filtro JWT\n"
                        + "        - id: content-service\n"
                        + "          uri: lb://content-service\n"
                        + "          predicates:\n"
                        + "            - Path=/api/content/**\n"
                        + "          filters:\n"
                        + "            - StripPrefix=2\n"
                        + "            - JwtAuthFilter\n"
                        + "\n"
                        + "        # Exercises — CON filtro JWT\n"
                        + "        - id: exercises-service\n"
                        + "          uri: lb://content-service\n"
                        + "          predicates:\n"
                        + "            - Path=/api/exercises/**\n"
                        + "          filters:\n"
                        + "            - StripPrefix=1\n"
                        + "            - JwtAuthFilter\n"
                        + "\n"
                        + "        # Progress Service — CON filtro JWT\n"
                        + "        - id: progress-service\n"
                        + "          uri: lb://progress-service\n"
                        + "          predicates:\n"
                        + "            - Path=/api/progress/**\n"
                        + "          filters:\n"
                        + "            - StripPrefix=1\n"
                        + "            - JwtAuthFilter\n"
                        + "\n"
                        + "eureka:\n"
                        + "  client:\n"
                        + "    service-url:\n"
                        + "      defaultZone: http://localhost:8761/eureka/\n"
                        + "\n"
                        + "jwt:\n"
                        + "  secret: dojo-secret-key-that-is-at-least-256-bits-long-for-hs256-algorithm-security</code></pre>"
                        + "<p><b>Desglose de cada ruta:</b></p>"
                        + "<table class='table table-sm table-dark'>"
                        + "<thead><tr><th>Petición al Gateway</th><th>StripPrefix</th><th>Llega al servicio como</th><th>JWT</th></tr></thead>"
                        + "<tbody>"
                        + "<tr><td><code>/api/auth/login</code></td><td>1 (quita <code>/api</code>)</td><td><code>/auth/login</code></td><td>❌ No</td></tr>"
                        + "<tr><td><code>/api/content/flashcards</code></td><td>2 (quita <code>/api/content</code>)</td><td><code>/flashcards</code></td><td>✅ Sí</td></tr>"
                        + "<tr><td><code>/api/exercises/1</code></td><td>1 (quita <code>/api</code>)</td><td><code>/exercises/1</code></td><td>✅ Sí</td></tr>"
                        + "<tr><td><code>/api/progress/berto</code></td><td>1 (quita <code>/api</code>)</td><td><code>/progress/berto</code></td><td>✅ Sí</td></tr>"
                        + "</tbody></table>"
                        + "<p><b>Conceptos clave:</b></p>"
                        + "<ul>"
                        + "<li><code>lb://auth-service</code> — <b>Load Balanced</b> via Eureka. El Gateway pregunta a Eureka la IP real del servicio</li>"
                        + "<li><code>predicates</code> — Condiciones para que la ruta aplique. <code>Path=/api/auth/**</code> = cualquier URL que empiece por /api/auth/</li>"
                        + "<li><code>StripPrefix=1</code> — Quita N segmentos del path antes de enviar al servicio. "
                        + "<code>/api/auth/login</code> con StripPrefix=1 → <code>/auth/login</code></li>"
                        + "<li><code>JwtAuthFilter</code> — Nuestro filtro. Se referencia por el nombre de la clase (sin el sufijo \"GatewayFilterFactory\")</li>"
                        + "</ul>"
                        + "<p>📌 <b>La clave JWT DEBE ser la misma</b> que en auth-service. Si no, Auth genera tokens que el Gateway no puede validar.</p>"),

                    section("8. Arrancar y probar",
                        "<p>Necesitas <b>Eureka + Auth + Content</b> corriendo antes de probar el Gateway:</p>"
                        + "<pre><code># Si no están corriendo:\ncd eureka-server && mvn spring-boot:run &\ncd auth-service && mvn spring-boot:run &\ncd content-service && mvn spring-boot:run &\n\n# Ahora el Gateway:\ncd api-gateway && mvn spring-boot:run</code></pre>"
                        + "<p><b>Probar el flujo completo a través del Gateway:</b></p>"
                        + "<pre><code># 1. Registrarse (va a auth-service, SIN token)\n"
                        + "curl -s -X POST http://localhost:8080/api/auth/register \\\n"
                        + "  -H 'Content-Type: application/json' \\\n"
                        + "  -d '{\"username\":\"berto\",\"email\":\"berto@test.com\",\n"
                        + "       \"password\":\"123456\"}' | jq\n"
                        + "\n"
                        + "# 2. Login (guarda el token)\n"
                        + "TOKEN=$(curl -s -X POST http://localhost:8080/api/auth/login \\\n"
                        + "  -H 'Content-Type: application/json' \\\n"
                        + "  -d '{\"username\":\"berto\",\"password\":\"123456\"}' \\\n"
                        + "  | jq -r '.token')\n"
                        + "\n"
                        + "echo $TOKEN  # Debería mostrar eyJhbGci...\n"
                        + "\n"
                        + "# 3. Pedir flashcards CON token (va a content-service)\n"
                        + "curl -s http://localhost:8080/api/content/flashcards \\\n"
                        + "  -H \"Authorization: Bearer $TOKEN\" | jq\n"
                        + "\n"
                        + "# 4. Pedir SIN token → 401 Unauthorized\n"
                        + "curl -s http://localhost:8080/api/content/flashcards\n"
                        + "# (respuesta vacía = 401)</code></pre>"
                        + "<p>Si el paso 3 devuelve flashcards y el paso 4 devuelve vacío/401, "
                        + "<b>¡el Gateway y el filtro JWT funcionan correctamente!</b> 🎉</p>"),

                    section("⚠️ Errores comunes",
                        "<table class='table table-sm table-dark'>"
                        + "<thead><tr><th>Error</th><th>Causa</th><th>Solución</th></tr></thead>"
                        + "<tbody>"
                        + "<tr><td><code>Spring MVC found on classpath</code> + error de arranque</td>"
                        + "<td>Tienes <code>spring-boot-starter-web</code> en el pom</td>"
                        + "<td><b>Quítalo</b>. El Gateway usa WebFlux, no MVC. Son incompatibles</td></tr>"
                        + "<tr><td><code>503 Service Unavailable</code></td>"
                        + "<td>El servicio destino no está registrado en Eureka</td>"
                        + "<td>Verifica en <a href='http://localhost:8761'>Eureka dashboard</a> que el servicio aparece</td></tr>"
                        + "<tr><td><code>404 Not Found</code> en rutas que deberían funcionar</td>"
                        + "<td>El <code>StripPrefix</code> no es correcto — el servicio recibe una URL diferente a la esperada</td>"
                        + "<td>Revisa la tabla de rutas. Prueba el servicio directamente (sin Gateway) para confirmar la URL real</td></tr>"
                        + "<tr><td><code>401</code> en rutas de auth (login/register)</td>"
                        + "<td>El filtro JWT se está aplicando a las rutas de auth</td>"
                        + "<td>Las rutas de auth NO deben tener el filtro <code>JwtAuthFilter</code> en sus filters</td></tr>"
                        + "<tr><td>Token válido en auth pero 401 en Gateway</td>"
                        + "<td>Las claves JWT (<code>jwt.secret</code>) son diferentes</td>"
                        + "<td>Copia exactamente la misma clave en el application.yml de auth-service y api-gateway</td></tr>"
                        + "<tr><td><code>No qualifying bean of type JwtAuthFilter</code></td>"
                        + "<td>El filtro no se detecta como componente</td>"
                        + "<td>Verifica que tiene <code>@Component</code> y que está en un paquete que Spring escanea</td></tr>"
                        + "</tbody></table>"),

                    section("💡 Conceptos para la entrevista",
                        "<ul>"
                        + "<li><b>API Gateway pattern</b> — Punto de entrada único para microservicios. Centraliza routing, seguridad, rate limiting, logging</li>"
                        + "<li><b>Spring Cloud Gateway vs Zuul</b> — Gateway es reactivo (WebFlux, no bloqueante), Zuul es bloqueante (deprecated). "
                        + "Gateway es el estándar actual de Spring Cloud</li>"
                        + "<li><b>WebFlux vs MVC</b> — MVC es el modelo clásico (un thread por petición). WebFlux es reactivo "
                        + "(pocos threads, muchas peticiones asíncronas). El Gateway usa WebFlux porque es un proxy: recibe muchas peticiones y las redirige</li>"
                        + "<li><b>StripPrefix</b> — Los clientes usan URLs con prefijo (<code>/api/auth/login</code>) pero los servicios internos "
                        + "no saben de ese prefijo (<code>/auth/login</code>). StripPrefix hace la traducción</li>"
                        + "<li><b>GatewayFilterFactory vs GlobalFilter</b> — Factory = filtro configurable por ruta. GlobalFilter = se aplica a todas las rutas</li>"
                        + "</ul>"),

                    section("✅ Checklist antes de continuar",
                        "<ul>"
                        + "<li>☐ Proyecto <code>api-gateway</code> creado (SIN spring-boot-starter-web)</li>"
                        + "<li>☐ JwtAuthFilter.java implementado</li>"
                        + "<li>☐ application.yml con rutas a auth, content, exercises, progress</li>"
                        + "<li>☐ <b>Misma clave JWT</b> que en auth-service</li>"
                        + "<li>☐ Login vía Gateway funciona (<code>/api/auth/login</code>)</li>"
                        + "<li>☐ Flashcards vía Gateway con token funciona (<code>/api/content/flashcards</code>)</li>"
                        + "<li>☐ Sin token → 401</li>"
                        + "<li>☐ Aparece en Eureka como API-GATEWAY</li>"
                        + "<li>☐ Commit: <code>git commit -m \"Add api-gateway with JWT filter\"</code></li>"
                        + "</ul>"
                        + "<p>¡La infraestructura está completa! 🏗️ Eureka + Auth + Content + Gateway funcionando. "
                        + "Ahora toca darle cara: el <b>Frontend con Thymeleaf</b>. 🎨</p>")
                ));

    }
}
