package com.dojo.frontend.controller.guia;

import java.util.*;
import static com.dojo.frontend.controller.guia.GuiaHelper.*;

public class GuiaCapitulo11 {

    public static Map<String, Object> getPaso() {
        return crearPaso(
            11, "Repetición Espaciada", "bi-arrow-repeat",
            "La repetición espaciada es una técnica de aprendizaje que prioriza el contenido que más fallas. "
            + "En vez de mostrar las flashcards en orden aleatorio, las que marcas como \"No lo sabía\" "
            + "aparecen antes y con más frecuencia. Las que ya dominas van bajando de prioridad. "
            + "Es como el algoritmo de Anki pero simplificado.",
            List.of(

                section("1. ¿Cómo funciona?",
                    "<p>Cada flashcard tiene una <b>prioridad</b> por usuario (de 0 a 10):</p>"
                    + "<ul>"
                    + "<li>Prioridad <b>alta (10)</b> → aparece primero (la fallas mucho)</li>"
                    + "<li>Prioridad <b>baja (0)</b> → aparece al final (ya la dominas)</li>"
                    + "<li>Prioridad <b>inicial (5)</b> → punto medio para flashcards nuevas</li>"
                    + "</ul>"
                    + "<pre><code>Cuando respondes una flashcard:\n"
                    + "\n"
                    + "  ✅ \"Lo sabía\"     → prioridad - 1 (mínimo 0)\n"
                    + "  ❌ \"No lo sabía\"  → prioridad + 2 (máximo 10)\n"
                    + "\n"
                    + "Orden de aparición:\n"
                    + "  1. Flashcards NO vistas (nuevas)\n"
                    + "  2. Flashcards vistas, ordenadas por:\n"
                    + "     - Mayor prioridad primero (las que más fallas)\n"
                    + "     - Si misma prioridad → la que hace más tiempo que no ves</code></pre>"
                    + "<p>📌 <b>¿Por qué +2 al fallar y -1 al acertar?</b> Porque es más importante repasar los errores "
                    + "que premiar los aciertos. Así las flashcards problemáticas \"suben\" rápido y las dominadas \"bajan\" lentamente.</p>"),

                section("2. Entity: UserFlashcardHistory.java",
                    "<p><b>Ruta</b>: <code>content-service/src/main/java/com/dojo/content/entity/UserFlashcardHistory.java</code></p>"
                    + "<p>Esta entidad registra el historial de cada usuario con cada flashcard:</p>"
                    + "<pre><code>package com.dojo.content.entity;\n"
                    + "\n"
                    + "import jakarta.persistence.*;\n"
                    + "import java.time.LocalDateTime;\n"
                    + "\n"
                    + "@Entity\n"
                    + "@Table(name = \"user_flashcard_history\",\n"
                    + "    uniqueConstraints = {\n"
                    + "        @UniqueConstraint(\n"
                    + "            columnNames = {\"userId\", \"flashcard_id\"})\n"
                    + "    })\n"
                    + "public class UserFlashcardHistory {\n"
                    + "\n"
                    + "    @Id\n"
                    + "    @GeneratedValue(strategy = GenerationType.IDENTITY)\n"
                    + "    private Long id;\n"
                    + "\n"
                    + "    @Column(nullable = false)\n"
                    + "    private String userId;\n"
                    + "\n"
                    + "    @ManyToOne(fetch = FetchType.LAZY)\n"
                    + "    @JoinColumn(name = \"flashcard_id\", nullable = false)\n"
                    + "    private Flashcard flashcard;  // Relación con Flashcard\n"
                    + "\n"
                    + "    @Column(nullable = false)\n"
                    + "    private int timesCorrect;   // Veces que acertó\n"
                    + "\n"
                    + "    @Column(nullable = false)\n"
                    + "    private int timesWrong;      // Veces que falló\n"
                    + "\n"
                    + "    @Column(nullable = false)\n"
                    + "    private int priority;         // 0-10 (más alto = más urgente)\n"
                    + "\n"
                    + "    private LocalDateTime lastSeen;  // Última vez que la vio\n"
                    + "\n"
                    + "    public UserFlashcardHistory() {}\n"
                    + "\n"
                    + "    public UserFlashcardHistory(String userId, Flashcard flashcard) {\n"
                    + "        this.userId = userId;\n"
                    + "        this.flashcard = flashcard;\n"
                    + "        this.timesCorrect = 0;\n"
                    + "        this.timesWrong = 0;\n"
                    + "        this.priority = 5;  // Prioridad inicial media\n"
                    + "    }\n"
                    + "\n"
                    + "    // Getters y setters de todos los campos...\n"
                    + "}</code></pre>"
                    + "<p><b>Novedades JPA:</b></p>"
                    + "<ul>"
                    + "<li><code>@ManyToOne(fetch = FetchType.LAZY)</code> — Relación muchos-a-uno con Flashcard. "
                    + "<b>LAZY</b> significa que la flashcard solo se carga de BD cuando accedes a ella (no al cargar el history). "
                    + "Esto mejora el rendimiento</li>"
                    + "<li><code>@JoinColumn(name = \"flashcard_id\")</code> — La columna en la tabla que es foreign key hacia flashcards</li>"
                    + "<li><code>@UniqueConstraint({\"userId\", \"flashcard_id\"})</code> — Un usuario solo tiene UN historial "
                    + "por flashcard (el mismo patrón que en BeltProgress)</li>"
                    + "</ul>"),

                section("3. Repository con Query personalizada",
                    "<p><b>Ruta</b>: <code>.../repository/UserFlashcardHistoryRepository.java</code></p>"
                    + "<pre><code>package com.dojo.content.repository;\n"
                    + "\n"
                    + "import com.dojo.content.entity.UserFlashcardHistory;\n"
                    + "import org.springframework.data.jpa.repository.JpaRepository;\n"
                    + "import org.springframework.data.jpa.repository.Query;\n"
                    + "import org.springframework.data.repository.query.Param;\n"
                    + "import java.util.*;\n"
                    + "\n"
                    + "public interface UserFlashcardHistoryRepository\n"
                    + "        extends JpaRepository&lt;UserFlashcardHistory, Long&gt; {\n"
                    + "\n"
                    + "    // Buscar historial de un usuario con una flashcard\n"
                    + "    Optional&lt;UserFlashcardHistory&gt; findByUserIdAndFlashcardId(\n"
                    + "        String userId, Long flashcardId);\n"
                    + "\n"
                    + "    // Todo el historial de un usuario\n"
                    + "    List&lt;UserFlashcardHistory&gt; findByUserId(String userId);\n"
                    + "\n"
                    + "    // 🔑 La query clave: obtener historial ordenado por prioridad\n"
                    + "    @Query(\"SELECT h FROM UserFlashcardHistory h \"\n"
                    + "         + \"WHERE h.userId = :userId \"\n"
                    + "         + \"AND h.flashcard.difficulty = :difficulty \"\n"
                    + "         + \"ORDER BY h.priority DESC, h.lastSeen ASC\")\n"
                    + "    List&lt;UserFlashcardHistory&gt;\n"
                    + "        findByUserIdAndDifficultyOrderByPriority(\n"
                    + "            @Param(\"userId\") String userId,\n"
                    + "            @Param(\"difficulty\") String difficulty);\n"
                    + "}</code></pre>"
                    + "<p><b>¿Por qué <code>@Query</code> en vez de Derived Query?</b></p>"
                    + "<p>La última query necesita filtrar por un campo de la <b>relación</b> (<code>h.flashcard.difficulty</code>) "
                    + "y ordenar por dos campos. Esto es demasiado complejo para un Derived Query Method. "
                    + "Con <code>@Query</code> escribes JPQL directamente.</p>"
                    + "<p><b>JPQL vs SQL</b>: JPQL usa nombres de <b>entidades y campos Java</b> (no tablas y columnas SQL). "
                    + "<code>UserFlashcardHistory</code> en vez de <code>user_flashcard_history</code>. "
                    + "Spring lo traduce a SQL automáticamente.</p>"
                    + "<p><b>El ORDER BY:</b></p>"
                    + "<ul>"
                    + "<li><code>priority DESC</code> — Las de más prioridad primero (las que más fallas)</li>"
                    + "<li><code>lastSeen ASC</code> — Si misma prioridad, la que hace más tiempo que no ves</li>"
                    + "</ul>"),

                section("4. Lógica en FlashcardService",
                    "<p>Dos métodos nuevos en <code>FlashcardService.java</code>:</p>"
                    + "<p><b>findNextForUser()</b> — Decide el orden de las flashcards:</p>"
                    + "<pre><code>public List&lt;Flashcard&gt; findNextForUser(\n"
                    + "        String difficulty, String userId) {\n"
                    + "\n"
                    + "    List&lt;Flashcard&gt; allFlashcards =\n"
                    + "        flashcardRepository.findByDifficulty(difficulty);\n"
                    + "\n"
                    + "    // Si no hay userId, devolver todas sin ordenar\n"
                    + "    if (userId == null || userId.isBlank()) {\n"
                    + "        return allFlashcards;\n"
                    + "    }\n"
                    + "\n"
                    + "    // Obtener historial ordenado por prioridad\n"
                    + "    List&lt;UserFlashcardHistory&gt; history = historyRepository\n"
                    + "        .findByUserIdAndDifficultyOrderByPriority(\n"
                    + "            userId, difficulty);\n"
                    + "\n"
                    + "    // Flashcards que el usuario YA ha visto\n"
                    + "    Set&lt;Long&gt; seenIds = history.stream()\n"
                    + "        .map(h -> h.getFlashcard().getId())\n"
                    + "        .collect(Collectors.toSet());\n"
                    + "\n"
                    + "    // 1. Primero las NO vistas (nuevas)\n"
                    + "    List&lt;Flashcard&gt; unseen = allFlashcards.stream()\n"
                    + "        .filter(f -> !seenIds.contains(f.getId()))\n"
                    + "        .collect(Collectors.toList());\n"
                    + "\n"
                    + "    // 2. Luego las vistas, ordenadas por prioridad\n"
                    + "    List&lt;Flashcard&gt; seenSorted = history.stream()\n"
                    + "        .map(UserFlashcardHistory::getFlashcard)\n"
                    + "        .collect(Collectors.toList());\n"
                    + "\n"
                    + "    // Combinar: nuevas primero, luego por prioridad\n"
                    + "    List&lt;Flashcard&gt; result = new ArrayList&lt;&gt;(unseen);\n"
                    + "    result.addAll(seenSorted);\n"
                    + "    return result;\n"
                    + "}</code></pre>"
                    + "<p><b>recordFlashcardAnswer()</b> — Registra la respuesta y ajusta la prioridad:</p>"
                    + "<pre><code>@Transactional\n"
                    + "public UserFlashcardHistory recordFlashcardAnswer(\n"
                    + "        Long flashcardId, String userId, boolean correct) {\n"
                    + "\n"
                    + "    Flashcard flashcard = findById(flashcardId);\n"
                    + "\n"
                    + "    // Buscar o crear historial\n"
                    + "    UserFlashcardHistory history = historyRepository\n"
                    + "        .findByUserIdAndFlashcardId(userId, flashcardId)\n"
                    + "        .orElse(new UserFlashcardHistory(userId, flashcard));\n"
                    + "\n"
                    + "    history.setLastSeen(LocalDateTime.now());\n"
                    + "\n"
                    + "    if (correct) {\n"
                    + "        history.setTimesCorrect(history.getTimesCorrect() + 1);\n"
                    + "        // Bajar prioridad (mínimo 0)\n"
                    + "        history.setPriority(\n"
                    + "            Math.max(0, history.getPriority() - 1));\n"
                    + "    } else {\n"
                    + "        history.setTimesWrong(history.getTimesWrong() + 1);\n"
                    + "        // Subir prioridad (máximo 10)\n"
                    + "        history.setPriority(\n"
                    + "            Math.min(10, history.getPriority() + 2));\n"
                    + "    }\n"
                    + "\n"
                    + "    return historyRepository.save(history);\n"
                    + "}</code></pre>"),

                section("5. Endpoints en FlashcardController",
                    "<p>Dos endpoints nuevos en <code>FlashcardController.java</code>:</p>"
                    + "<pre><code>// Flashcards priorizadas para un usuario\n"
                    + "// GET /flashcards/next?difficulty=BLANCO&userId=berto\n"
                    + "@GetMapping(\"/next\")\n"
                    + "public ResponseEntity&lt;List&lt;Flashcard&gt;&gt; getNext(\n"
                    + "        @RequestParam String difficulty,\n"
                    + "        @RequestParam(required = false) String userId) {\n"
                    + "    return ResponseEntity.ok(\n"
                    + "        flashcardService.findNextForUser(difficulty, userId));\n"
                    + "}\n"
                    + "\n"
                    + "// Registrar respuesta de un usuario a una flashcard\n"
                    + "// POST /flashcards/5/answer?userId=berto&correct=true\n"
                    + "@PostMapping(\"/{id}/answer\")\n"
                    + "public ResponseEntity&lt;Map&lt;String, Object&gt;&gt; recordAnswer(\n"
                    + "        @PathVariable Long id,\n"
                    + "        @RequestParam String userId,\n"
                    + "        @RequestParam boolean correct) {\n"
                    + "    UserFlashcardHistory history =\n"
                    + "        flashcardService.recordFlashcardAnswer(\n"
                    + "            id, userId, correct);\n"
                    + "    return ResponseEntity.ok(Map.of(\n"
                    + "        \"flashcardId\", id,\n"
                    + "        \"priority\", history.getPriority(),\n"
                    + "        \"timesCorrect\", history.getTimesCorrect(),\n"
                    + "        \"timesWrong\", history.getTimesWrong()));\n"
                    + "}</code></pre>"
                    + "<table class='table table-sm table-dark'>"
                    + "<thead><tr><th>Endpoint</th><th>Qué hace</th></tr></thead>"
                    + "<tbody>"
                    + "<tr><td><code>GET /flashcards/next?difficulty=BLANCO&amp;userId=berto</code></td>"
                    + "<td>Devuelve flashcards ordenadas: nuevas primero, luego las que más fallas</td></tr>"
                    + "<tr><td><code>POST /flashcards/5/answer?userId=berto&amp;correct=false</code></td>"
                    + "<td>Registra que el usuario falló la flashcard 5 → sube prioridad a 7</td></tr>"
                    + "</tbody></table>"),

                section("6. Cómo se conecta con el frontend",
                    "<p>El <code>StudyController</code> del frontend (capítulo 8) ya usa estos endpoints:</p>"
                    + "<pre><code>// En GET /study:\n"
                    + "// Pide flashcards priorizadas\n"
                    + "restTemplate.exchange(\n"
                    + "    gatewayUrl + \"/api/content/flashcards/next\"\n"
                    + "    + \"?difficulty=\" + difficulty\n"
                    + "    + \"&userId=\" + username, ...);\n"
                    + "\n"
                    + "// En POST /study/answer:\n"
                    + "// Registra la respuesta\n"
                    + "restTemplate.exchange(\n"
                    + "    gatewayUrl + \"/api/content/flashcards/\"\n"
                    + "    + flashcardId + \"/answer?userId=\" + username\n"
                    + "    + \"&correct=\" + correct, ...);</code></pre>"
                    + "<p>Así cuando el usuario estudia:</p>"
                    + "<ol>"
                    + "<li>Entra a Study → frontend pide <code>/flashcards/next</code> → ve las que más necesita repasar</li>"
                    + "<li>Responde \"Lo sabía\" → prioridad baja → la próxima vez aparece más abajo</li>"
                    + "<li>Responde \"No lo sabía\" → prioridad sube → la próxima vez aparece arriba</li>"
                    + "</ol>"),

                section("7. Ejemplo de evolución de prioridades",
                    "<pre><code>Flashcard: \"¿Qué es @Autowired?\"\n"
                    + "Usuario: berto\n"
                    + "\n"
                    + "Intento 1: ❌ No lo sabía  → prioridad: 5 → 7\n"
                    + "Intento 2: ❌ No lo sabía  → prioridad: 7 → 9\n"
                    + "Intento 3: ✅ Lo sabía     → prioridad: 9 → 8\n"
                    + "Intento 4: ✅ Lo sabía     → prioridad: 8 → 7\n"
                    + "Intento 5: ✅ Lo sabía     → prioridad: 7 → 6\n"
                    + "...\n"
                    + "Intento 10: ✅ Lo sabía    → prioridad: 2 → 1\n"
                    + "\n"
                    + "Flashcard: \"¿Qué es Spring Boot?\"\n"
                    + "Intento 1: ✅ Lo sabía     → prioridad: 5 → 4\n"
                    + "Intento 2: ✅ Lo sabía     → prioridad: 4 → 3\n"
                    + "\n"
                    + "Orden de aparición:\n"
                    + "  1. Flashcards nuevas (no vistas)\n"
                    + "  2. \"¿Qué es @Autowired?\" (prioridad 1)\n"
                    + "  3. ... (otras flashcards con prioridad &gt; 0)\n"
                    + "  Nota: aunque @Autowired tiene prioridad 1,\n"
                    + "  antes iba con 9 — el sistema se autocorrige</code></pre>"),

                section("⚠️ Errores comunes",
                    "<table class='table table-sm table-dark'>"
                    + "<thead><tr><th>Error</th><th>Causa</th><th>Solución</th></tr></thead>"
                    + "<tbody>"
                    + "<tr><td>Las flashcards siempre aparecen en el mismo orden</td>"
                    + "<td><code>userId</code> no se está pasando en la petición</td>"
                    + "<td>Sin userId, el endpoint devuelve todas sin ordenar. Verifica que el frontend envía <code>&amp;userId=username</code></td></tr>"
                    + "<tr><td><code>LazyInitializationException</code></td>"
                    + "<td>Acceder a <code>history.getFlashcard()</code> fuera de una transacción</td>"
                    + "<td>Usa <code>@Transactional</code> en el Service o cambia a <code>FetchType.EAGER</code> (no recomendado para listas grandes)</td></tr>"
                    + "<tr><td>La prioridad no cambia</td>"
                    + "<td>El endpoint <code>/answer</code> no se llama correctamente</td>"
                    + "<td>Revisa en la consola de content-service que se ejecuta el INSERT/UPDATE en <code>user_flashcard_history</code></td></tr>"
                    + "</tbody></table>"),

                section("💡 Conceptos para la entrevista",
                    "<ul>"
                    + "<li><b>Spaced Repetition</b> — Técnica de aprendizaje basada en el \"efecto de espaciado\": "
                    + "repasas más lo que no sabes y menos lo que ya dominas. Anki, Quizlet y Duolingo lo usan</li>"
                    + "<li><b>@ManyToOne / @OneToMany</b> — Relaciones JPA. ManyToOne = muchos historiales apuntan a una flashcard. "
                    + "LAZY loading = no cargar la relación hasta que se acceda</li>"
                    + "<li><b>@Query (JPQL)</b> — Cuando los Derived Query Methods no son suficientes, "
                    + "escribes JPQL directamente. Usa nombres de entidades Java, no tablas SQL</li>"
                    + "<li><b>Math.max / Math.min</b> — Patrón simple para acotar valores: "
                    + "<code>Math.max(0, x)</code> asegura que nunca baje de 0, <code>Math.min(10, x)</code> asegura que nunca suba de 10</li>"
                    + "</ul>"),

                section("✅ Checklist antes de continuar",
                    "<ul>"
                    + "<li>☐ <code>UserFlashcardHistory.java</code> creada en content-service/entity/</li>"
                    + "<li>☐ <code>UserFlashcardHistoryRepository.java</code> con @Query personalizada</li>"
                    + "<li>☐ <code>findNextForUser()</code> en FlashcardService</li>"
                    + "<li>☐ <code>recordFlashcardAnswer()</code> en FlashcardService</li>"
                    + "<li>☐ Endpoints <code>/flashcards/next</code> y <code>/flashcards/{id}/answer</code></li>"
                    + "<li>☐ El modo Study prioriza flashcards que fallas</li>"
                    + "<li>☐ Commit: <code>git commit -m \"Add spaced repetition for flashcards\"</code></li>"
                    + "</ul>"
                    + "<p>¡Repetición espaciada funcionando! 🧠 Ahora vamos con el <b>Sistema de Cinturones</b> — "
                    + "desbloqueo progresivo basado en tu progreso. 🥋</p>")
            ));
    }
}
