package com.dojo.frontend.controller.guia;

import java.util.*;
import static com.dojo.frontend.controller.guia.GuiaHelper.*;

public class GuiaCapitulo10 {

    public static Map<String, Object> getPaso() {
        return crearPaso(
            10, "Progress Service", "bi-graph-up-arrow",
                "El Progress Service es un microservicio independiente que rastrea el progreso de cada usuario: "
                + "total de aciertos, racha de días estudiados, y progreso por cinturón. "
                + "Es el servicio que hace que el Dashboard tenga datos reales y que los cinturones se desbloqueen.",
                List.of(

                    section("1. ¿Por qué un servicio separado?",
                        "<p>Podríamos haber metido el progreso dentro de Content Service, pero lo separamos porque:</p>"
                        + "<ul>"
                        + "<li><b>Responsabilidad única</b> — Content gestiona el contenido (flashcards, quizzes). "
                        + "Progress gestiona el avance del usuario. Son dominios diferentes</li>"
                        + "<li><b>Independencia</b> — Si Content Service cae, el progreso no se pierde</li>"
                        + "<li><b>Escalabilidad</b> — En producción, el progreso podría recibir muchas escrituras (cada respuesta). "
                        + "Poder escalarlo por separado es una ventaja</li>"
                        + "</ul>"
                        + "<p>Es un buen ejemplo de cuándo separar un microservicio: <b>cuando el dominio y la carga son distintos</b>.</p>"),

                    section("2. Crear el proyecto progress-service",
                        "<p><b>Spring Initializr</b> con:</p>"
                        + "<table class='table table-sm table-dark'>"
                        + "<thead><tr><th>Dependencia</th><th>Para qué</th></tr></thead>"
                        + "<tbody>"
                        + "<tr><td><b>Spring Web</b></td><td>API REST</td></tr>"
                        + "<tr><td><b>Spring Data JPA</b></td><td>Entidades y repositorios</td></tr>"
                        + "<tr><td><b>H2 Database</b></td><td>BD en memoria</td></tr>"
                        + "<tr><td><b>Validation</b></td><td>Validar requests</td></tr>"
                        + "<tr><td><b>Eureka Discovery Client</b></td><td>Registrarse en Eureka</td></tr>"
                        + "</tbody></table>"
                        + "<p>Mismas dependencias que Content Service (sin Security ni JWT — la protección la hace el Gateway).</p>"),

                    section("3. Estructura de carpetas",
                        "<pre><code>com.dojo.progress/\n"
                        + "├── ProgressServiceApplication.java\n"
                        + "├── controller/\n"
                        + "│   └── ProgressController.java\n"
                        + "├── dto/\n"
                        + "│   └── AnswerRequest.java\n"
                        + "├── entity/\n"
                        + "│   ├── UserProgress.java     ← Stats globales del usuario\n"
                        + "│   └── BeltProgress.java      ← Stats por cinturón\n"
                        + "├── repository/\n"
                        + "│   ├── UserProgressRepository.java\n"
                        + "│   └── BeltProgressRepository.java\n"
                        + "└── service/\n"
                        + "    └── ProgressService.java</code></pre>"),

                    section("4. Entity: UserProgress.java",
                        "<p><b>Ruta</b>: <code>.../entity/UserProgress.java</code></p>"
                        + "<p>Almacena las estadísticas globales del usuario:</p>"
                        + "<pre><code>package com.dojo.progress.entity;\n"
                        + "\n"
                        + "import jakarta.persistence.*;\n"
                        + "import java.time.LocalDate;\n"
                        + "\n"
                        + "@Entity\n"
                        + "@Table(name = \"user_progress\")\n"
                        + "public class UserProgress {\n"
                        + "\n"
                        + "    @Id\n"
                        + "    @GeneratedValue(strategy = GenerationType.IDENTITY)\n"
                        + "    private Long id;\n"
                        + "\n"
                        + "    @Column(nullable = false, unique = true)\n"
                        + "    private String userId;          // Username\n"
                        + "\n"
                        + "    @Column(nullable = false)\n"
                        + "    private int totalCorrect;       // Total aciertos\n"
                        + "\n"
                        + "    @Column(nullable = false)\n"
                        + "    private int totalAttempted;      // Total intentos\n"
                        + "\n"
                        + "    @Column(nullable = false)\n"
                        + "    private int currentStreak;       // Racha actual (días seguidos)\n"
                        + "\n"
                        + "    @Column(nullable = false)\n"
                        + "    private int bestStreak;           // Mejor racha histórica\n"
                        + "\n"
                        + "    private LocalDate lastStudyDate;  // Último día que estudió\n"
                        + "\n"
                        + "    public UserProgress() {}\n"
                        + "\n"
                        + "    public UserProgress(String userId) {\n"
                        + "        this.userId = userId;\n"
                        + "        this.totalCorrect = 0;\n"
                        + "        this.totalAttempted = 0;\n"
                        + "        this.currentStreak = 0;\n"
                        + "        this.bestStreak = 0;\n"
                        + "    }\n"
                        + "\n"
                        + "    // Getters y setters de todos los campos...\n"
                        + "}</code></pre>"
                        + "<p>📌 <code>LocalDate</code> (no <code>LocalDateTime</code>) porque la racha se cuenta por <b>días</b>, "
                        + "no por horas. JPA convierte <code>LocalDate</code> a columna DATE automáticamente.</p>"),

                    section("5. Entity: BeltProgress.java",
                        "<p><b>Ruta</b>: <code>.../entity/BeltProgress.java</code></p>"
                        + "<p>Progreso específico por cinturón:</p>"
                        + "<pre><code>package com.dojo.progress.entity;\n"
                        + "\n"
                        + "import jakarta.persistence.*;\n"
                        + "\n"
                        + "@Entity\n"
                        + "@Table(name = \"belt_progress\",\n"
                        + "    uniqueConstraints = {\n"
                        + "        @UniqueConstraint(\n"
                        + "            columnNames = {\"userId\", \"beltLevel\"})\n"
                        + "    })\n"
                        + "public class BeltProgress {\n"
                        + "\n"
                        + "    @Id\n"
                        + "    @GeneratedValue(strategy = GenerationType.IDENTITY)\n"
                        + "    private Long id;\n"
                        + "\n"
                        + "    @Column(nullable = false)\n"
                        + "    private String userId;\n"
                        + "\n"
                        + "    @Column(nullable = false)\n"
                        + "    private String beltLevel;   // BLANCO, AMARILLO...\n"
                        + "\n"
                        + "    @Column(nullable = false)\n"
                        + "    private int correctCount;    // Aciertos en este cinturón\n"
                        + "\n"
                        + "    @Column(nullable = false)\n"
                        + "    private int attemptCount;    // Intentos en este cinturón\n"
                        + "\n"
                        + "    @Column(nullable = false)\n"
                        + "    private boolean mastered;    // ¿Dominado?\n"
                        + "\n"
                        + "    public BeltProgress() {}\n"
                        + "\n"
                        + "    public BeltProgress(String userId, String beltLevel) {\n"
                        + "        this.userId = userId;\n"
                        + "        this.beltLevel = beltLevel;\n"
                        + "        this.correctCount = 0;\n"
                        + "        this.attemptCount = 0;\n"
                        + "        this.mastered = false;\n"
                        + "    }\n"
                        + "\n"
                        + "    // Getters y setters...\n"
                        + "}</code></pre>"
                        + "<p><b>Novedad</b>: <code>@UniqueConstraint(columnNames = {\"userId\", \"beltLevel\"})</code> — "
                        + "Esto crea una <b>restricción compuesta</b> en la base de datos: no puede haber dos filas con el mismo "
                        + "userId + beltLevel. Así cada usuario tiene máximo una fila por cinturón.</p>"
                        + "<p>La condición de <b>mastered</b> (cinturón dominado) se calcula así: "
                        + "<b>≥80% de acierto con mínimo 10 intentos</b>.</p>"),

                    section("6. Repositories",
                        "<p><b>UserProgressRepository.java</b>:</p>"
                        + "<pre><code>public interface UserProgressRepository\n"
                        + "        extends JpaRepository&lt;UserProgress, Long&gt; {\n"
                        + "\n"
                        + "    Optional&lt;UserProgress&gt; findByUserId(String userId);\n"
                        + "}</code></pre>"
                        + "<p><b>BeltProgressRepository.java</b>:</p>"
                        + "<pre><code>public interface BeltProgressRepository\n"
                        + "        extends JpaRepository&lt;BeltProgress, Long&gt; {\n"
                        + "\n"
                        + "    Optional&lt;BeltProgress&gt; findByUserIdAndBeltLevel(\n"
                        + "        String userId, String beltLevel);\n"
                        + "\n"
                        + "    List&lt;BeltProgress&gt; findByUserId(String userId);\n"
                        + "}</code></pre>"
                        + "<p>Simples y limpios. Spring Data genera las queries automáticamente.</p>"),

                    section("7. ProgressService.java — La lógica de negocio",
                        "<p>Este es el corazón del servicio. El método <code>recordAnswer()</code> hace varias cosas en una transacción:</p>"
                        + "<pre><code>@Service\n"
                        + "public class ProgressService {\n"
                        + "\n"
                        + "    private final UserProgressRepository userProgressRepo;\n"
                        + "    private final BeltProgressRepository beltProgressRepo;\n"
                        + "\n"
                        + "    // Constructor con inyección...\n"
                        + "\n"
                        + "    @Transactional  // Todo dentro de una transacción\n"
                        + "    public UserProgress recordAnswer(AnswerRequest request) {\n"
                        + "\n"
                        + "        // 1. Buscar o crear progreso del usuario\n"
                        + "        UserProgress progress = userProgressRepo\n"
                        + "            .findByUserId(request.getUsername())\n"
                        + "            .orElse(new UserProgress(request.getUsername()));\n"
                        + "\n"
                        + "        // 2. Actualizar contadores\n"
                        + "        progress.setTotalAttempted(\n"
                        + "            progress.getTotalAttempted() + 1);\n"
                        + "        if (request.isCorrect()) {\n"
                        + "            progress.setTotalCorrect(\n"
                        + "                progress.getTotalCorrect() + 1);\n"
                        + "        }\n"
                        + "\n"
                        + "        // 3. Calcular racha\n"
                        + "        LocalDate today = LocalDate.now();\n"
                        + "        if (progress.getLastStudyDate() == null\n"
                        + "                || !progress.getLastStudyDate().equals(today)) {\n"
                        + "\n"
                        + "            if (progress.getLastStudyDate() != null\n"
                        + "                && progress.getLastStudyDate()\n"
                        + "                    .plusDays(1).equals(today)) {\n"
                        + "                // Estudió ayer → incrementar racha\n"
                        + "                progress.setCurrentStreak(\n"
                        + "                    progress.getCurrentStreak() + 1);\n"
                        + "            } else {\n"
                        + "                // No estudió ayer → racha a 1\n"
                        + "                progress.setCurrentStreak(1);\n"
                        + "            }\n"
                        + "            progress.setLastStudyDate(today);\n"
                        + "        }\n"
                        + "\n"
                        + "        // 4. Actualizar mejor racha\n"
                        + "        if (progress.getCurrentStreak()\n"
                        + "                > progress.getBestStreak()) {\n"
                        + "            progress.setBestStreak(\n"
                        + "                progress.getCurrentStreak());\n"
                        + "        }\n"
                        + "\n"
                        + "        userProgressRepo.save(progress);\n"
                        + "\n"
                        + "        // 5. Actualizar progreso del cinturón\n"
                        + "        BeltProgress belt = beltProgressRepo\n"
                        + "            .findByUserIdAndBeltLevel(\n"
                        + "                request.getUsername(), request.getBeltLevel())\n"
                        + "            .orElse(new BeltProgress(\n"
                        + "                request.getUsername(), request.getBeltLevel()));\n"
                        + "\n"
                        + "        belt.setAttemptCount(belt.getAttemptCount() + 1);\n"
                        + "        if (request.isCorrect()) {\n"
                        + "            belt.setCorrectCount(belt.getCorrectCount() + 1);\n"
                        + "        }\n"
                        + "\n"
                        + "        // 6. ¿Cinturón dominado? (≥80% en 10+ intentos)\n"
                        + "        if (belt.getAttemptCount() >= 10) {\n"
                        + "            double pct = (double) belt.getCorrectCount()\n"
                        + "                / belt.getAttemptCount() * 100;\n"
                        + "            belt.setMastered(pct >= 80.0);\n"
                        + "        }\n"
                        + "\n"
                        + "        beltProgressRepo.save(belt);\n"
                        + "\n"
                        + "        return progress;\n"
                        + "    }\n"
                        + "}</code></pre>"
                        + "<p><b>Detalle del cálculo de racha:</b></p>"
                        + "<ul>"
                        + "<li>Si <b>nunca estudió</b> o <b>es un día nuevo</b> → comprobar si estudió ayer</li>"
                        + "<li>Si estudió <b>ayer</b> (<code>lastStudyDate + 1 día == hoy</code>) → incrementar racha</li>"
                        + "<li>Si NO estudió ayer → reiniciar racha a 1</li>"
                        + "<li>Si ya estudió <b>hoy</b> → no tocar la racha (puede responder 50 preguntas en un día)</li>"
                        + "</ul>"
                        + "<p>📌 <code>@Transactional</code> — Si algo falla a mitad (por ejemplo al guardar BeltProgress), "
                        + "se hace rollback de todo. O se guardan los dos o ninguno.</p>"),

                    section("8. ProgressController.java",
                        "<p><b>Ruta</b>: <code>.../controller/ProgressController.java</code></p>"
                        + "<pre><code>@RestController\n"
                        + "@RequestMapping(\"/progress\")\n"
                        + "public class ProgressController {\n"
                        + "\n"
                        + "    private final ProgressService progressService;\n"
                        + "\n"
                        + "    // Constructor...\n"
                        + "\n"
                        + "    // Registrar una respuesta\n"
                        + "    @PostMapping(\"/record\")\n"
                        + "    public ResponseEntity&lt;UserProgress&gt; recordAnswer(\n"
                        + "            @Valid @RequestBody AnswerRequest request) {\n"
                        + "        return ResponseEntity.ok(\n"
                        + "            progressService.recordAnswer(request));\n"
                        + "    }\n"
                        + "\n"
                        + "    // Obtener progreso completo de un usuario\n"
                        + "    @GetMapping(\"/{username}\")\n"
                        + "    public ResponseEntity&lt;Map&lt;String, Object&gt;&gt; getProgress(\n"
                        + "            @PathVariable String username) {\n"
                        + "        UserProgress progress =\n"
                        + "            progressService.getProgress(username);\n"
                        + "        List&lt;BeltProgress&gt; belts =\n"
                        + "            progressService.getBeltProgress(username);\n"
                        + "        return ResponseEntity.ok(Map.of(\n"
                        + "            \"userProgress\", progress,\n"
                        + "            \"beltProgress\", belts));\n"
                        + "    }\n"
                        + "\n"
                        + "    // Obtener solo racha\n"
                        + "    @GetMapping(\"/{username}/streak\")\n"
                        + "    public ResponseEntity&lt;Map&lt;String, Object&gt;&gt; getStreak(\n"
                        + "            @PathVariable String username) { ... }\n"
                        + "\n"
                        + "    // Obtener progreso de todos los cinturones\n"
                        + "    @GetMapping(\"/{username}/belts\")\n"
                        + "    public ResponseEntity&lt;List&lt;BeltProgress&gt;&gt; getBeltProgress(\n"
                        + "            @PathVariable String username) { ... }\n"
                        + "\n"
                        + "    // Obtener progreso de un cinturón específico\n"
                        + "    @GetMapping(\"/{username}/belts/{beltLevel}\")\n"
                        + "    public ResponseEntity&lt;BeltProgress&gt; getBeltProgressForLevel(\n"
                        + "            @PathVariable String username,\n"
                        + "            @PathVariable String beltLevel) { ... }\n"
                        + "}</code></pre>"
                        + "<table class='table table-sm table-dark'>"
                        + "<thead><tr><th>Endpoint</th><th>Qué devuelve</th></tr></thead>"
                        + "<tbody>"
                        + "<tr><td><code>POST /progress/record</code></td><td>Registra respuesta → devuelve UserProgress actualizado</td></tr>"
                        + "<tr><td><code>GET /progress/berto</code></td><td>Stats globales + progreso de todos los cinturones</td></tr>"
                        + "<tr><td><code>GET /progress/berto/streak</code></td><td>Racha actual + mejor racha</td></tr>"
                        + "<tr><td><code>GET /progress/berto/belts</code></td><td>Lista de BeltProgress</td></tr>"
                        + "<tr><td><code>GET /progress/berto/belts/BLANCO</code></td><td>Progreso de un cinturón específico</td></tr>"
                        + "</tbody></table>"),

                    section("9. AnswerRequest DTO",
                        "<pre><code>package com.dojo.progress.dto;\n"
                        + "\n"
                        + "import jakarta.validation.constraints.NotBlank;\n"
                        + "\n"
                        + "public class AnswerRequest {\n"
                        + "\n"
                        + "    @NotBlank\n"
                        + "    private String username;    // Quién respondió\n"
                        + "\n"
                        + "    @NotBlank\n"
                        + "    private String beltLevel;   // En qué cinturón\n"
                        + "\n"
                        + "    private boolean correct;     // ¿Acertó?\n"
                        + "\n"
                        + "    // Getters y setters...\n"
                        + "}</code></pre>"
                        + "<p>Solo 3 campos. El frontend envía este JSON cada vez que respondes una flashcard o quiz.</p>"),

                    section("10. application.yml",
                        "<pre><code>server:\n"
                        + "  port: 8084\n"
                        + "\n"
                        + "spring:\n"
                        + "  application:\n"
                        + "    name: progress-service\n"
                        + "  datasource:\n"
                        + "    url: jdbc:h2:mem:progressdb\n"
                        + "    driver-class-name: org.h2.Driver\n"
                        + "    username: sa\n"
                        + "    password:\n"
                        + "  jpa:\n"
                        + "    hibernate:\n"
                        + "      ddl-auto: create-drop\n"
                        + "    show-sql: true\n"
                        + "  h2:\n"
                        + "    console:\n"
                        + "      enabled: true\n"
                        + "\n"
                        + "eureka:\n"
                        + "  client:\n"
                        + "    service-url:\n"
                        + "      defaultZone: http://localhost:8761/eureka/</code></pre>"
                        + "<p>Puerto <b>8084</b>, BD propia (<code>progressdb</code>). Mismo patrón que auth y content.</p>"),

                    section("11. Arrancar y probar",
                        "<pre><code>cd progress-service && mvn spring-boot:run</code></pre>"
                        + "<p>Probar directamente:</p>"
                        + "<pre><code># Registrar una respuesta\n"
                        + "curl -s -X POST http://localhost:8084/progress/record \\\n"
                        + "  -H 'Content-Type: application/json' \\\n"
                        + "  -d '{\"username\":\"berto\",\n"
                        + "       \"beltLevel\":\"BLANCO\",\n"
                        + "       \"correct\":true}' | jq\n"
                        + "\n"
                        + "# Ver progreso\n"
                        + "curl -s http://localhost:8084/progress/berto | jq\n"
                        + "\n"
                        + "# Ver racha\n"
                        + "curl -s http://localhost:8084/progress/berto/streak | jq</code></pre>"
                        + "<p>Vía Gateway (con token):</p>"
                        + "<pre><code>curl -s http://localhost:8080/api/progress/berto \\\n"
                        + "  -H \"Authorization: Bearer $TOKEN\" | jq</code></pre>"
                        + "<p>Verifica en Eureka que aparece <code>PROGRESS-SERVICE</code>.</p>"),

                    section("⚠️ Errores comunes",
                        "<table class='table table-sm table-dark'>"
                        + "<thead><tr><th>Error</th><th>Causa</th><th>Solución</th></tr></thead>"
                        + "<tbody>"
                        + "<tr><td>Racha siempre en 1</td>"
                        + "<td>Necesitas estudiar en <b>días consecutivos</b> para que suba</td>"
                        + "<td>Normal. La racha solo incrementa si <code>lastStudyDate + 1 == today</code></td></tr>"
                        + "<tr><td>Cinturón no se marca como mastered</td>"
                        + "<td>Menos de 10 intentos o menos del 80% de acierto</td>"
                        + "<td>Necesitas ≥10 intentos Y ≥80% correcto en ese cinturón</td></tr>"
                        + "<tr><td><code>UniqueConstraint violation</code></td>"
                        + "<td>Intentar crear dos BeltProgress con mismo userId + beltLevel</td>"
                        + "<td>Usa <code>findByUserIdAndBeltLevel().orElse(new ...)</code> para buscar primero y crear solo si no existe</td></tr>"
                        + "</tbody></table>"),

                    section("💡 Conceptos para la entrevista",
                        "<ul>"
                        + "<li><b>@Transactional</b> — Asegura que todas las operaciones dentro del método se ejecutan como una unidad. "
                        + "Si una falla, se hace rollback de todas. Esencial para consistencia de datos</li>"
                        + "<li><b>Composite Unique Constraint</b> — <code>@UniqueConstraint(columnNames = {\"userId\", \"beltLevel\"})</code> "
                        + "crea un índice único compuesto. Cada combinación userId+beltLevel es única</li>"
                        + "<li><b>orElse vs orElseThrow</b> — <code>orElse(new ...)</code> crea uno nuevo si no existe (upsert pattern). "
                        + "<code>orElseThrow()</code> lanza excepción si no existe (error 404)</li>"
                        + "<li><b>LocalDate vs LocalDateTime</b> — Date para fechas sin hora. DateTime para timestamps completos. "
                        + "Aquí usamos Date porque la racha se cuenta por días</li>"
                        + "</ul>"),

                    section("✅ Checklist antes de continuar",
                        "<ul>"
                        + "<li>☐ Proyecto <code>progress-service</code> creado</li>"
                        + "<li>☐ Entidades: UserProgress, BeltProgress</li>"
                        + "<li>☐ Repositories: UserProgressRepository, BeltProgressRepository</li>"
                        + "<li>☐ ProgressService con lógica de racha y mastered</li>"
                        + "<li>☐ ProgressController con 5 endpoints</li>"
                        + "<li>☐ Funciona vía curl directo y vía Gateway con token</li>"
                        + "<li>☐ El Dashboard ahora muestra stats reales</li>"
                        + "<li>☐ Commit: <code>git commit -m \"Add progress-service with streaks and belt progress\"</code></li>"
                        + "</ul>"
                        + "<p>¡Progreso funcionando! 📊 Ahora vamos con un feature más avanzado: "
                        + "<b>Repetición Espaciada</b> — para que las flashcards que más fallas aparezcan más. 🧠</p>")
                ));
    }
}
