package com.dojo.frontend.controller.guia;

import java.util.*;
import static com.dojo.frontend.controller.guia.GuiaHelper.*;

public class GuiaCapitulo05 {

    public static Map<String, Object> getPaso() {
        return crearPaso(
            5, "Content Service (API REST + JPA)", "bi-database",
                "El Content Service es el corazón del contenido de aprendizaje. Gestiona flashcards, quizzes y ejercicios de código. "
                + "Aquí aprenderás el patrón completo de Spring Boot: Entity → Repository → Service → Controller → DTO. "
                + "Es el servicio con más código, pero todo sigue la misma estructura.",
                List.of(

                    section("1. Crear el proyecto content-service",
                        "<p><b>Spring Initializr</b> con estas dependencias:</p>"
                        + "<table class='table table-sm table-dark'>"
                        + "<thead><tr><th>Dependencia</th><th>Para qué</th></tr></thead>"
                        + "<tbody>"
                        + "<tr><td><b>Spring Web</b></td><td>API REST</td></tr>"
                        + "<tr><td><b>Spring Data JPA</b></td><td>Acceso a BD con entidades y repos</td></tr>"
                        + "<tr><td><b>H2 Database</b></td><td>BD en memoria</td></tr>"
                        + "<tr><td><b>Validation</b></td><td>Validar DTOs</td></tr>"
                        + "<tr><td><b>Eureka Discovery Client</b></td><td>Registrarse en Eureka</td></tr>"
                        + "</tbody></table>"
                        + "<p>📌 A diferencia del Auth Service, aquí <b>NO necesitamos</b> Spring Security ni JWT. "
                        + "La seguridad la gestiona el Gateway — Content Service solo recibe peticiones ya validadas.</p>"),

                    section("2. Estructura de carpetas",
                        "<pre><code>com.dojo.content/\n"
                        + "├── ContentServiceApplication.java\n"
                        + "├── config/\n"
                        + "│   └── DataSeeder.java          ← Carga datos iniciales al arrancar\n"
                        + "├── controller/\n"
                        + "│   ├── FlashcardController.java\n"
                        + "│   ├── QuizController.java\n"
                        + "│   └── CodeExerciseController.java\n"
                        + "├── dto/\n"
                        + "│   ├── FlashcardRequest.java\n"
                        + "│   └── QuizRequest.java\n"
                        + "├── entity/\n"
                        + "│   ├── Flashcard.java\n"
                        + "│   ├── Quiz.java\n"
                        + "│   ├── CodeExercise.java\n"
                        + "│   └── UserFlashcardHistory.java  ← Para repetición espaciada\n"
                        + "├── repository/\n"
                        + "│   ├── FlashcardRepository.java\n"
                        + "│   ├── QuizRepository.java\n"
                        + "│   ├── CodeExerciseRepository.java\n"
                        + "│   └── UserFlashcardHistoryRepository.java\n"
                        + "└── service/\n"
                        + "    ├── FlashcardService.java\n"
                        + "    ├── QuizService.java\n"
                        + "    └── CodeExerciseService.java</code></pre>"
                        + "<p>Es el servicio con más archivos — pero todos siguen el mismo patrón. "
                        + "Si entiendes la Flashcard (Entity→Repo→Service→Controller), entiendes Quiz y CodeExercise.</p>"),

                    section("3. El patrón: Entity → Repository → Service → Controller",
                        "<p>Antes de ver el código, entiende el patrón que se repite en <b>TODOS</b> los servicios Spring Boot:</p>"
                        + "<pre><code>Petición HTTP\n"
                        + "     │\n"
                        + "     ▼\n"
                        + "┌─────────────┐  Recibe la petición, valida entrada,\n"
                        + "│ Controller  │  devuelve respuesta HTTP (200, 404, etc.)\n"
                        + "└──────┬──────┘\n"
                        + "       │\n"
                        + "       ▼\n"
                        + "┌─────────────┐  Lógica de negocio: reglas, cálculos,\n"
                        + "│   Service   │  transformaciones, validaciones complejas\n"
                        + "└──────┬──────┘\n"
                        + "       │\n"
                        + "       ▼\n"
                        + "┌─────────────┐  Acceso a datos: queries SQL generadas\n"
                        + "│ Repository  │  automáticamente por Spring Data\n"
                        + "└──────┬──────┘\n"
                        + "       │\n"
                        + "       ▼\n"
                        + "┌─────────────┐  Mapeo Java ↔ tabla de BD.\n"
                        + "│   Entity    │  Cada campo = una columna\n"
                        + "└─────────────┘\n"
                        + "\n"
                        + "   DTO = lo que viaja por la API (no exponer Entity)</code></pre>"
                        + "<p>Vamos a crear cada capa para Flashcard. Después, Quiz y CodeExercise son copy-paste con variaciones.</p>"),

                    section("4. Entity: Flashcard.java",
                        "<p><b>Ruta</b>: <code>content-service/src/main/java/com/dojo/content/entity/Flashcard.java</code></p>"
                        + "<pre><code>package com.dojo.content.entity;\n"
                        + "\n"
                        + "import jakarta.persistence.*;\n"
                        + "import java.time.LocalDateTime;\n"
                        + "\n"
                        + "@Entity\n"
                        + "@Table(name = \"flashcards\")\n"
                        + "public class Flashcard {\n"
                        + "\n"
                        + "    @Id\n"
                        + "    @GeneratedValue(strategy = GenerationType.IDENTITY)\n"
                        + "    private Long id;\n"
                        + "\n"
                        + "    @Column(nullable = false)\n"
                        + "    private String question;\n"
                        + "\n"
                        + "    @Column(nullable = false, length = 2000)\n"
                        + "    private String answer;\n"
                        + "\n"
                        + "    @Column(nullable = false)\n"
                        + "    private String category;    // FUNDAMENTOS, REST_API, SECURITY...\n"
                        + "\n"
                        + "    @Column(nullable = false)\n"
                        + "    private String difficulty;   // BLANCO, AMARILLO, NARANJA...\n"
                        + "\n"
                        + "    @Column(name = \"created_at\", nullable = false, updatable = false)\n"
                        + "    private LocalDateTime createdAt;\n"
                        + "\n"
                        + "    @PrePersist  // Se ejecuta antes de guardar por primera vez\n"
                        + "    protected void onCreate() {\n"
                        + "        this.createdAt = LocalDateTime.now();\n"
                        + "    }\n"
                        + "\n"
                        + "    public Flashcard() {}\n"
                        + "\n"
                        + "    public Flashcard(String question, String answer,\n"
                        + "                    String category, String difficulty) {\n"
                        + "        this.question = question;\n"
                        + "        this.answer = answer;\n"
                        + "        this.category = category;\n"
                        + "        this.difficulty = difficulty;\n"
                        + "    }\n"
                        + "\n"
                        + "    // Getters y setters de todos los campos\n"
                        + "    public Long getId() { return id; }\n"
                        + "    public void setId(Long id) { this.id = id; }\n"
                        + "    public String getQuestion() { return question; }\n"
                        + "    public void setQuestion(String question) { this.question = question; }\n"
                        + "    public String getAnswer() { return answer; }\n"
                        + "    public void setAnswer(String answer) { this.answer = answer; }\n"
                        + "    public String getCategory() { return category; }\n"
                        + "    public void setCategory(String category) { this.category = category; }\n"
                        + "    public String getDifficulty() { return difficulty; }\n"
                        + "    public void setDifficulty(String difficulty) { this.difficulty = difficulty; }\n"
                        + "    public LocalDateTime getCreatedAt() { return createdAt; }\n"
                        + "    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }\n"
                        + "}</code></pre>"
                        + "<p><b>Novedades respecto a User:</b></p>"
                        + "<ul>"
                        + "<li><code>@Column(length = 2000)</code> — Por defecto las columnas String son VARCHAR(255). "
                        + "Las respuestas pueden ser largas, así que le damos más espacio</li>"
                        + "<li><code>@PrePersist</code> — Callback de JPA que se ejecuta automáticamente antes del primer <code>save()</code>. "
                        + "Así el <code>createdAt</code> se rellena solo sin que tú lo hagas</li>"
                        + "<li><code>updatable = false</code> — La fecha de creación no se puede modificar después</li>"
                        + "</ul>"),

                    section("5. Entity: Quiz.java",
                        "<p><b>Ruta</b>: <code>content-service/src/main/java/com/dojo/content/entity/Quiz.java</code></p>"
                        + "<pre><code>package com.dojo.content.entity;\n"
                        + "\n"
                        + "import jakarta.persistence.*;\n"
                        + "import java.time.LocalDateTime;\n"
                        + "\n"
                        + "@Entity\n"
                        + "@Table(name = \"quizzes\")\n"
                        + "public class Quiz {\n"
                        + "\n"
                        + "    @Id\n"
                        + "    @GeneratedValue(strategy = GenerationType.IDENTITY)\n"
                        + "    private Long id;\n"
                        + "\n"
                        + "    @Column(nullable = false)\n"
                        + "    private String question;\n"
                        + "\n"
                        + "    @Column(nullable = false)\n"
                        + "    private String optionA;\n"
                        + "    @Column(nullable = false)\n"
                        + "    private String optionB;\n"
                        + "    @Column(nullable = false)\n"
                        + "    private String optionC;\n"
                        + "    @Column(nullable = false)\n"
                        + "    private String optionD;\n"
                        + "\n"
                        + "    @Column(nullable = false)\n"
                        + "    private int correctOption;  // 0=A, 1=B, 2=C, 3=D\n"
                        + "\n"
                        + "    @Column(nullable = false)\n"
                        + "    private String category;\n"
                        + "    @Column(nullable = false)\n"
                        + "    private String difficulty;\n"
                        + "\n"
                        + "    @Column(name = \"created_at\", nullable = false, updatable = false)\n"
                        + "    private LocalDateTime createdAt;\n"
                        + "\n"
                        + "    @PrePersist\n"
                        + "    protected void onCreate() {\n"
                        + "        this.createdAt = LocalDateTime.now();\n"
                        + "    }\n"
                        + "\n"
                        + "    public Quiz() {}\n"
                        + "\n"
                        + "    public Quiz(String question, String optionA, String optionB,\n"
                        + "               String optionC, String optionD, int correctOption,\n"
                        + "               String category, String difficulty) {\n"
                        + "        this.question = question;\n"
                        + "        this.optionA = optionA;\n"
                        + "        this.optionB = optionB;\n"
                        + "        this.optionC = optionC;\n"
                        + "        this.optionD = optionD;\n"
                        + "        this.correctOption = correctOption;\n"
                        + "        this.category = category;\n"
                        + "        this.difficulty = difficulty;\n"
                        + "    }\n"
                        + "\n"
                        + "    // Getters y setters (todos los campos)\n"
                        + "    public Long getId() { return id; }\n"
                        + "    public void setId(Long id) { this.id = id; }\n"
                        + "    public String getQuestion() { return question; }\n"
                        + "    public void setQuestion(String question) { this.question = question; }\n"
                        + "    public String getOptionA() { return optionA; }\n"
                        + "    public void setOptionA(String optionA) { this.optionA = optionA; }\n"
                        + "    public String getOptionB() { return optionB; }\n"
                        + "    public void setOptionB(String optionB) { this.optionB = optionB; }\n"
                        + "    public String getOptionC() { return optionC; }\n"
                        + "    public void setOptionC(String optionC) { this.optionC = optionC; }\n"
                        + "    public String getOptionD() { return optionD; }\n"
                        + "    public void setOptionD(String optionD) { this.optionD = optionD; }\n"
                        + "    public int getCorrectOption() { return correctOption; }\n"
                        + "    public void setCorrectOption(int correctOption) { this.correctOption = correctOption; }\n"
                        + "    public String getCategory() { return category; }\n"
                        + "    public void setCategory(String category) { this.category = category; }\n"
                        + "    public String getDifficulty() { return difficulty; }\n"
                        + "    public void setDifficulty(String difficulty) { this.difficulty = difficulty; }\n"
                        + "    public LocalDateTime getCreatedAt() { return createdAt; }\n"
                        + "    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }\n"
                        + "}</code></pre>"
                        + "<p>Mismo patrón que Flashcard pero con 4 opciones y un <code>correctOption</code> (índice 0-3).</p>"),

                    section("6. Repositories",
                        "<p>Los repositorios son interfaces — Spring genera la implementación:</p>"
                        + "<p><b>FlashcardRepository.java</b>:</p>"
                        + "<pre><code>package com.dojo.content.repository;\n"
                        + "\n"
                        + "import com.dojo.content.entity.Flashcard;\n"
                        + "import org.springframework.data.jpa.repository.JpaRepository;\n"
                        + "import java.util.List;\n"
                        + "\n"
                        + "public interface FlashcardRepository\n"
                        + "        extends JpaRepository&lt;Flashcard, Long&gt; {\n"
                        + "\n"
                        + "    List&lt;Flashcard&gt; findByCategory(String category);\n"
                        + "    List&lt;Flashcard&gt; findByDifficulty(String difficulty);\n"
                        + "    List&lt;Flashcard&gt; findByCategoryAndDifficulty(\n"
                        + "            String category, String difficulty);\n"
                        + "}</code></pre>"
                        + "<p><b>QuizRepository.java</b>: Idéntico pero con <code>Quiz</code> en vez de <code>Flashcard</code>.</p>"
                        + "<pre><code>package com.dojo.content.repository;\n"
                        + "\n"
                        + "import com.dojo.content.entity.Quiz;\n"
                        + "import org.springframework.data.jpa.repository.JpaRepository;\n"
                        + "import java.util.List;\n"
                        + "\n"
                        + "public interface QuizRepository\n"
                        + "        extends JpaRepository&lt;Quiz, Long&gt; {\n"
                        + "\n"
                        + "    List&lt;Quiz&gt; findByCategory(String category);\n"
                        + "    List&lt;Quiz&gt; findByDifficulty(String difficulty);\n"
                        + "    List&lt;Quiz&gt; findByCategoryAndDifficulty(\n"
                        + "            String category, String difficulty);\n"
                        + "}</code></pre>"
                        + "<p><b>CodeExerciseRepository.java</b>:</p>"
                        + "<pre><code>package com.dojo.content.repository;\n"
                        + "\n"
                        + "import com.dojo.content.entity.CodeExercise;\n"
                        + "import org.springframework.data.jpa.repository.JpaRepository;\n"
                        + "import java.util.List;\n"
                        + "\n"
                        + "public interface CodeExerciseRepository\n"
                        + "        extends JpaRepository&lt;CodeExercise, Long&gt; {\n"
                        + "    List&lt;CodeExercise&gt; findByBelt(String belt);\n"
                        + "}</code></pre>"
                        + "<p>📌 <b>Derived Query Methods en acción:</b></p>"
                        + "<ul>"
                        + "<li><code>findByDifficulty(\"BLANCO\")</code> → <code>SELECT * FROM flashcards WHERE difficulty = 'BLANCO'</code></li>"
                        + "<li><code>findByCategoryAndDifficulty(\"REST_API\", \"AMARILLO\")</code> → <code>WHERE category = 'REST_API' AND difficulty = 'AMARILLO'</code></li>"
                        + "</ul>"
                        + "<p>Spring lee el nombre del método y construye la query automáticamente. No escribes SQL.</p>"),

                    section("7. DTOs",
                        "<p><b>FlashcardRequest.java</b>:</p>"
                        + "<pre><code>package com.dojo.content.dto;\n"
                        + "\n"
                        + "import jakarta.validation.constraints.NotBlank;\n"
                        + "\n"
                        + "public class FlashcardRequest {\n"
                        + "    @NotBlank private String question;\n"
                        + "    @NotBlank private String answer;\n"
                        + "    @NotBlank private String category;\n"
                        + "    @NotBlank private String difficulty;\n"
                        + "\n"
                        + "    // Getters y setters de los 4 campos\n"
                        + "    public String getQuestion() { return question; }\n"
                        + "    public void setQuestion(String question) { this.question = question; }\n"
                        + "    public String getAnswer() { return answer; }\n"
                        + "    public void setAnswer(String answer) { this.answer = answer; }\n"
                        + "    public String getCategory() { return category; }\n"
                        + "    public void setCategory(String category) { this.category = category; }\n"
                        + "    public String getDifficulty() { return difficulty; }\n"
                        + "    public void setDifficulty(String difficulty) { this.difficulty = difficulty; }\n"
                        + "}</code></pre>"
                        + "<p><b>QuizRequest.java</b>:</p>"
                        + "<pre><code>package com.dojo.content.dto;\n"
                        + "\n"
                        + "import jakarta.validation.constraints.*;\n"
                        + "\n"
                        + "public class QuizRequest {\n"
                        + "    @NotBlank private String question;\n"
                        + "    @NotBlank private String optionA;\n"
                        + "    @NotBlank private String optionB;\n"
                        + "    @NotBlank private String optionC;\n"
                        + "    @NotBlank private String optionD;\n"
                        + "    @Min(0) @Max(3) private int correctOption;\n"
                        + "    @NotBlank private String category;\n"
                        + "    @NotBlank private String difficulty;\n"
                        + "\n"
                        + "    // Getters y setters de todos los campos...\n"
                        + "}</code></pre>"
                        + "<p><code>@Min(0) @Max(3)</code> valida que correctOption sea 0, 1, 2 o 3 (las 4 opciones A-D).</p>"),

                    section("8. FlashcardService.java",
                        "<p><b>Ruta</b>: <code>content-service/src/main/java/com/dojo/content/service/FlashcardService.java</code></p>"
                        + "<pre><code>package com.dojo.content.service;\n"
                        + "\n"
                        + "import com.dojo.content.dto.FlashcardRequest;\n"
                        + "import com.dojo.content.entity.Flashcard;\n"
                        + "import com.dojo.content.repository.FlashcardRepository;\n"
                        + "import org.springframework.stereotype.Service;\n"
                        + "import java.util.List;\n"
                        + "\n"
                        + "@Service\n"
                        + "public class FlashcardService {\n"
                        + "\n"
                        + "    private final FlashcardRepository flashcardRepository;\n"
                        + "\n"
                        + "    public FlashcardService(FlashcardRepository flashcardRepository) {\n"
                        + "        this.flashcardRepository = flashcardRepository;\n"
                        + "    }\n"
                        + "\n"
                        + "    public List&lt;Flashcard&gt; findAll() {\n"
                        + "        return flashcardRepository.findAll();\n"
                        + "    }\n"
                        + "\n"
                        + "    public Flashcard findById(Long id) {\n"
                        + "        return flashcardRepository.findById(id)\n"
                        + "            .orElseThrow(() -> new IllegalArgumentException(\n"
                        + "                \"Flashcard not found with id: \" + id));\n"
                        + "    }\n"
                        + "\n"
                        + "    public List&lt;Flashcard&gt; findByCategory(String category) {\n"
                        + "        return flashcardRepository.findByCategory(category);\n"
                        + "    }\n"
                        + "\n"
                        + "    public List&lt;Flashcard&gt; findByDifficulty(String difficulty) {\n"
                        + "        return flashcardRepository.findByDifficulty(difficulty);\n"
                        + "    }\n"
                        + "\n"
                        + "    public Flashcard create(FlashcardRequest request) {\n"
                        + "        Flashcard flashcard = new Flashcard(\n"
                        + "            request.getQuestion(), request.getAnswer(),\n"
                        + "            request.getCategory(), request.getDifficulty());\n"
                        + "        return flashcardRepository.save(flashcard);\n"
                        + "    }\n"
                        + "\n"
                        + "    public Flashcard update(Long id, FlashcardRequest request) {\n"
                        + "        Flashcard flashcard = findById(id);\n"
                        + "        flashcard.setQuestion(request.getQuestion());\n"
                        + "        flashcard.setAnswer(request.getAnswer());\n"
                        + "        flashcard.setCategory(request.getCategory());\n"
                        + "        flashcard.setDifficulty(request.getDifficulty());\n"
                        + "        return flashcardRepository.save(flashcard);\n"
                        + "    }\n"
                        + "\n"
                        + "    public void delete(Long id) {\n"
                        + "        if (!flashcardRepository.existsById(id)) {\n"
                        + "            throw new IllegalArgumentException(\n"
                        + "                \"Flashcard not found with id: \" + id);\n"
                        + "        }\n"
                        + "        flashcardRepository.deleteById(id);\n"
                        + "    }\n"
                        + "}</code></pre>"
                        + "<p>📌 El QuizService sigue exactamente el mismo patrón. Cambia <code>Flashcard</code> por <code>Quiz</code> "
                        + "y <code>FlashcardRequest</code> por <code>QuizRequest</code>. No lo repito aquí para no duplicar.</p>"),

                    section("9. FlashcardController.java",
                        "<p><b>Ruta</b>: <code>content-service/src/main/java/com/dojo/content/controller/FlashcardController.java</code></p>"
                        + "<pre><code>package com.dojo.content.controller;\n"
                        + "\n"
                        + "import com.dojo.content.dto.FlashcardRequest;\n"
                        + "import com.dojo.content.entity.Flashcard;\n"
                        + "import com.dojo.content.service.FlashcardService;\n"
                        + "import jakarta.validation.Valid;\n"
                        + "import org.springframework.http.HttpStatus;\n"
                        + "import org.springframework.http.ResponseEntity;\n"
                        + "import org.springframework.web.bind.annotation.*;\n"
                        + "import java.util.List;\n"
                        + "import java.util.Map;\n"
                        + "\n"
                        + "@RestController\n"
                        + "@RequestMapping(\"/flashcards\")\n"
                        + "public class FlashcardController {\n"
                        + "\n"
                        + "    private final FlashcardService flashcardService;\n"
                        + "\n"
                        + "    public FlashcardController(FlashcardService flashcardService) {\n"
                        + "        this.flashcardService = flashcardService;\n"
                        + "    }\n"
                        + "\n"
                        + "    // GET /flashcards\n"
                        + "    // GET /flashcards?category=REST_API\n"
                        + "    // GET /flashcards?difficulty=BLANCO\n"
                        + "    @GetMapping\n"
                        + "    public ResponseEntity&lt;List&lt;Flashcard&gt;&gt; getAll(\n"
                        + "            @RequestParam(required = false) String category,\n"
                        + "            @RequestParam(required = false) String difficulty) {\n"
                        + "        List&lt;Flashcard&gt; flashcards;\n"
                        + "        if (category != null) {\n"
                        + "            flashcards = flashcardService.findByCategory(category);\n"
                        + "        } else if (difficulty != null) {\n"
                        + "            flashcards = flashcardService.findByDifficulty(difficulty);\n"
                        + "        } else {\n"
                        + "            flashcards = flashcardService.findAll();\n"
                        + "        }\n"
                        + "        return ResponseEntity.ok(flashcards);\n"
                        + "    }\n"
                        + "\n"
                        + "    // GET /flashcards/5\n"
                        + "    @GetMapping(\"/{id}\")\n"
                        + "    public ResponseEntity&lt;Flashcard&gt; getById(@PathVariable Long id) {\n"
                        + "        return ResponseEntity.ok(flashcardService.findById(id));\n"
                        + "    }\n"
                        + "\n"
                        + "    // POST /flashcards\n"
                        + "    @PostMapping\n"
                        + "    public ResponseEntity&lt;Flashcard&gt; create(\n"
                        + "            @Valid @RequestBody FlashcardRequest request) {\n"
                        + "        return ResponseEntity.status(HttpStatus.CREATED)\n"
                        + "                .body(flashcardService.create(request));\n"
                        + "    }\n"
                        + "\n"
                        + "    // PUT /flashcards/5\n"
                        + "    @PutMapping(\"/{id}\")\n"
                        + "    public ResponseEntity&lt;Flashcard&gt; update(\n"
                        + "            @PathVariable Long id,\n"
                        + "            @Valid @RequestBody FlashcardRequest request) {\n"
                        + "        return ResponseEntity.ok(flashcardService.update(id, request));\n"
                        + "    }\n"
                        + "\n"
                        + "    // DELETE /flashcards/5\n"
                        + "    @DeleteMapping(\"/{id}\")\n"
                        + "    public ResponseEntity&lt;Void&gt; delete(@PathVariable Long id) {\n"
                        + "        flashcardService.delete(id);\n"
                        + "        return ResponseEntity.noContent().build();  // 204\n"
                        + "    }\n"
                        + "\n"
                        + "    @ExceptionHandler(IllegalArgumentException.class)\n"
                        + "    public ResponseEntity&lt;Map&lt;String, String&gt;&gt; handleNotFound(\n"
                        + "            IllegalArgumentException e) {\n"
                        + "        return ResponseEntity.status(HttpStatus.NOT_FOUND)\n"
                        + "                .body(Map.of(\"error\", e.getMessage()));\n"
                        + "    }\n"
                        + "}</code></pre>"
                        + "<p><b>Esto es un CRUD completo</b> (Create, Read, Update, Delete):</p>"
                        + "<table class='table table-sm table-dark'>"
                        + "<thead><tr><th>Método HTTP</th><th>URL</th><th>Acción</th><th>Código resp.</th></tr></thead>"
                        + "<tbody>"
                        + "<tr><td>GET</td><td>/flashcards</td><td>Listar todas (con filtros opcionales)</td><td>200</td></tr>"
                        + "<tr><td>GET</td><td>/flashcards/5</td><td>Obtener una por ID</td><td>200 / 404</td></tr>"
                        + "<tr><td>POST</td><td>/flashcards</td><td>Crear nueva</td><td>201</td></tr>"
                        + "<tr><td>PUT</td><td>/flashcards/5</td><td>Actualizar existente</td><td>200 / 404</td></tr>"
                        + "<tr><td>DELETE</td><td>/flashcards/5</td><td>Eliminar</td><td>204 / 404</td></tr>"
                        + "</tbody></table>"),

                    section("10. DataSeeder: cargar datos iniciales",
                        "<p>Necesitamos flashcards y quizzes desde el primer arranque. El <code>DataSeeder</code> los crea automáticamente:</p>"
                        + "<p><b>Ruta</b>: <code>content-service/src/main/java/com/dojo/content/config/DataSeeder.java</code></p>"
                        + "<pre><code>package com.dojo.content.config;\n"
                        + "\n"
                        + "import com.dojo.content.entity.Flashcard;\n"
                        + "import com.dojo.content.entity.Quiz;\n"
                        + "import com.dojo.content.repository.FlashcardRepository;\n"
                        + "import com.dojo.content.repository.QuizRepository;\n"
                        + "import org.springframework.boot.CommandLineRunner;\n"
                        + "import org.springframework.context.annotation.Bean;\n"
                        + "import org.springframework.context.annotation.Configuration;\n"
                        + "import java.util.List;\n"
                        + "\n"
                        + "@Configuration\n"
                        + "public class DataSeeder {\n"
                        + "\n"
                        + "    @Bean\n"
                        + "    CommandLineRunner seedFlashcards(FlashcardRepository repo) {\n"
                        + "        return args -> {\n"
                        + "            if (repo.count() == 0) {  // Solo si no hay datos\n"
                        + "                repo.saveAll(List.of(\n"
                        + "                    new Flashcard(\n"
                        + "                        \"¿Qué hace @SpringBootApplication?\",\n"
                        + "                        \"Combina @Configuration, @EnableAutoConfiguration \"\n"
                        + "                        + \"y @ComponentScan. Marca la clase principal.\",\n"
                        + "                        \"FUNDAMENTOS\", \"BLANCO\"),\n"
                        + "                    new Flashcard(\n"
                        + "                        \"¿Qué es la Inyección de Dependencias?\",\n"
                        + "                        \"Patrón donde los objetos reciben sus dependencias \"\n"
                        + "                        + \"desde fuera en vez de crearlas ellos.\",\n"
                        + "                        \"FUNDAMENTOS\", \"BLANCO\")\n"
                        + "                    // ... más flashcards por cinturón\n"
                        + "                ));\n"
                        + "            }\n"
                        + "        };\n"
                        + "    }\n"
                        + "\n"
                        + "    @Bean\n"
                        + "    CommandLineRunner seedQuizzes(QuizRepository repo) {\n"
                        + "        return args -> {\n"
                        + "            if (repo.count() == 0) {\n"
                        + "                repo.saveAll(List.of(\n"
                        + "                    new Quiz(\n"
                        + "                        \"¿Qué anotación marca la clase principal?\",\n"
                        + "                        \"@SpringBootApplication\",  // A ✓\n"
                        + "                        \"@MainClass\",              // B\n"
                        + "                        \"@StartApplication\",       // C\n"
                        + "                        \"@RunApplication\",         // D\n"
                        + "                        0,  // Respuesta correcta: A (índice 0)\n"
                        + "                        \"FUNDAMENTOS\", \"BLANCO\")\n"
                        + "                    // ... más quizzes por cinturón\n"
                        + "                ));\n"
                        + "            }\n"
                        + "        };\n"
                        + "    }\n"
                        + "}</code></pre>"
                        + "<p><b>¿Cómo funciona?</b></p>"
                        + "<ul>"
                        + "<li><code>CommandLineRunner</code> — Interfaz que Spring ejecuta automáticamente al arrancar la app</li>"
                        + "<li><code>repo.count() == 0</code> — Solo carga datos si la tabla está vacía (evita duplicados)</li>"
                        + "<li>El archivo real del proyecto tiene 530+ líneas con flashcards y quizzes organizados por cinturón "
                        + "(BLANCO, AMARILLO, NARANJA, VERDE, MARRÓN, NEGRO)</li>"
                        + "</ul>"
                        + "<p>💡 <b>Consejo</b>: Los datos se pierden al reiniciar porque H2 es en memoria. "
                        + "El DataSeeder los recrea cada vez. En producción usarías migraciones Flyway/Liquibase.</p>"),

                    section("11. application.yml",
                        "<p><b>Ruta</b>: <code>content-service/src/main/resources/application.yml</code></p>"
                        + "<pre><code>server:\n"
                        + "  port: 8083\n"
                        + "\n"
                        + "spring:\n"
                        + "  application:\n"
                        + "    name: content-service\n"
                        + "  datasource:\n"
                        + "    url: jdbc:h2:mem:contentdb\n"
                        + "    driver-class-name: org.h2.Driver\n"
                        + "    username: sa\n"
                        + "    password:\n"
                        + "  jpa:\n"
                        + "    hibernate:\n"
                        + "      ddl-auto: create-drop\n"
                        + "    show-sql: true\n"
                        + "  h2:\n"
                        + "    console:\n"
                        + "      enabled: true\n"
                        + "\n"
                        + "eureka:\n"
                        + "  client:\n"
                        + "    service-url:\n"
                        + "      defaultZone: http://localhost:8761/eureka/</code></pre>"
                        + "<p>Prácticamente igual que auth-service pero sin las propiedades JWT (no las necesita) "
                        + "y con su propia base de datos (<code>contentdb</code> vs <code>authdb</code>). "
                        + "Puerto: <b>8083</b>.</p>"),

                    section("12. Arrancar y probar",
                        "<p>Con Eureka corriendo:</p>"
                        + "<pre><code>cd content-service && mvn spring-boot:run</code></pre>"
                        + "<p>Prueba los endpoints directamente (sin Gateway por ahora):</p>"
                        + "<pre><code># Todas las flashcards\n"
                        + "curl -s http://localhost:8083/flashcards | jq\n"
                        + "\n"
                        + "# Solo las del cinturón blanco\n"
                        + "curl -s 'http://localhost:8083/flashcards?difficulty=BLANCO' | jq\n"
                        + "\n"
                        + "# Todos los quizzes\n"
                        + "curl -s http://localhost:8083/quizzes | jq\n"
                        + "\n"
                        + "# Crear una flashcard nueva\n"
                        + "curl -s -X POST http://localhost:8083/flashcards \\\n"
                        + "  -H 'Content-Type: application/json' \\\n"
                        + "  -d '{\"question\":\"¿Qué es REST?\",\n"
                        + "       \"answer\":\"Arquitectura para APIs web\",\n"
                        + "       \"category\":\"REST_API\",\n"
                        + "       \"difficulty\":\"AMARILLO\"}' | jq</code></pre>"
                        + "<p>📌 <code>| jq</code> formatea el JSON en la terminal. Si no tienes jq instalado: "
                        + "<code>sudo dnf install jq</code> (Fedora) o <code>sudo apt install jq</code> (Ubuntu).</p>"
                        + "<p>Verifica en Eureka (<a href='http://localhost:8761'>localhost:8761</a>) que aparece <code>CONTENT-SERVICE</code>.</p>"),

                    section("⚠️ Errores comunes",
                        "<table class='table table-sm table-dark'>"
                        + "<thead><tr><th>Error</th><th>Causa</th><th>Solución</th></tr></thead>"
                        + "<tbody>"
                        + "<tr><td><code>Column 'QUESTION' not found</code> o errores de mapeo</td>"
                        + "<td>Los nombres de campos en la Entity no coinciden con lo que espera H2</td>"
                        + "<td>Revisa que <code>ddl-auto: create-drop</code> esté activo — recrea las tablas al arrancar</td></tr>"
                        + "<tr><td><code>DataSeeder</code> no carga datos</td>"
                        + "<td>La condición <code>count() == 0</code> no se cumple o hay error en los datos</td>"
                        + "<td>Revisa la consola por excepciones. Abre H2 console y haz <code>SELECT COUNT(*) FROM FLASHCARDS</code></td></tr>"
                        + "<tr><td>Respuestas vacías <code>[]</code></td>"
                        + "<td>Los datos no se cargaron</td>"
                        + "<td>Comprueba que el DataSeeder se ejecuta (pon un <code>System.out.println</code> dentro del runner)</td></tr>"
                        + "<tr><td><code>@RequestMapping</code> no incluye <code>/api/</code></td>"
                        + "<td>En content-service las rutas son <code>/flashcards</code>, <code>/quizzes</code> sin prefijo. "
                        + "El Gateway añade el prefijo</td>"
                        + "<td>Es correcto así. Al probar directamente: <code>localhost:8083/flashcards</code>. "
                        + "Vía Gateway: <code>localhost:8080/api/content/flashcards</code></td></tr>"
                        + "</tbody></table>"),

                    section("💡 Conceptos para la entrevista",
                        "<ul>"
                        + "<li><b>CRUD</b> — Create (POST), Read (GET), Update (PUT), Delete (DELETE). Las 4 operaciones básicas de cualquier API</li>"
                        + "<li><b>DTO vs Entity</b> — Entity = mapeo de BD, puede tener campos sensibles. "
                        + "DTO = lo que expones en la API. Nunca exponer la Entity directamente (aunque en proyectos pequeños se hace)</li>"
                        + "<li><b>@RequestParam vs @PathVariable</b> — <code>/flashcards?difficulty=BLANCO</code> (RequestParam) vs "
                        + "<code>/flashcards/5</code> (PathVariable). RequestParam para filtrar, PathVariable para identificar</li>"
                        + "<li><b>CommandLineRunner</b> — Se ejecuta al arrancar. Útil para seed data, migraciones, o tareas de inicio</li>"
                        + "<li><b>ResponseEntity</b> — Permite controlar el código HTTP de respuesta (200, 201, 204, 404...)</li>"
                        + "</ul>"),

                    section("✅ Checklist antes de continuar",
                        "<ul>"
                        + "<li>☐ Proyecto <code>content-service</code> creado</li>"
                        + "<li>☐ Entidades: Flashcard.java, Quiz.java</li>"
                        + "<li>☐ Repositories: FlashcardRepository, QuizRepository</li>"
                        + "<li>☐ Services: FlashcardService, QuizService</li>"
                        + "<li>☐ Controllers: FlashcardController, QuizController</li>"
                        + "<li>☐ DataSeeder carga flashcards y quizzes al arrancar</li>"
                        + "<li>☐ <code>curl localhost:8083/flashcards</code> devuelve datos</li>"
                        + "<li>☐ Aparece en Eureka como CONTENT-SERVICE</li>"
                        + "<li>☐ Commit: <code>git commit -m \"Add content-service with flashcards and quizzes\"</code></li>"
                        + "</ul>"
                        + "<p>¡Content Service listo! 📚 Ahora vamos con el <b>API Gateway</b> — el que conecta todo. 🔌</p>")
                ));

    }
}
